NNP VBZ RB RB RB that PRP RB RB VBP PRP .
RB EX VBD RB JJ NNS that PRP VBD RP PDT DT JJ NNS .
PRP VBZ JJ JJ NN that PRP MD VB TO VB TO DT NN .
PRP VBD RB JJ that PRP MD RB VB TO VB DT NN .
PRP VBD so that PRP MD RB VB .
PRP VBD RB VB because PRP VBD JJ .
DT MD VB JJ because DT NNP NN VBZ RB VBN TO VB VBN IN NN IN NNP .
Since PRP VBP DT NN , PRP MD RB DObj PRP .
PRP MD RB VB VBN PRP , for PRP VBD RB RB .
PRP VBD PRP because PRP VBD JJ .
PRP MD VB RBR so that PRP MD VB VBN IN DT .
PRP VBZ JJ IN LogN that PRP$ NN MD VB JJ .
JJS NNS VBP TO NN so that PRP MD VB NNS , NNS CC NNS .
DT NN VBD PRP$ NN IN NN that DT NNS IN DT NN MD VB JJR RB .
PRP DObj RP RB RB that PRP MD VB DT JJ NN .
PRP RB JJ DObj CC RB PRP VBP NN .
PRP$ NN VBZ DT NN CC PRP$ NN VBZ DT NN .
PRP VBD VBN VBN CC PRP VBD VBN .
PRP RB VBD PRP$ NN , PRP MD CC VBP RB .
PRP RB JJ VBD it CC RB PRP VBD it .
PRP VBZ as if NN VBZ VBG IN DT NN .
NN VBD .
PRP VBP SOLOC TO DObj JJ IN NNS , for PRP RB DObj TO DT JJ NNS .
DT NN , whose NNS VBZ DT NN , VBZ RB JJ .
If PRP DObj JJ NN TO DT NN , PRP MD VB DT JJR NN .
PRP VBP RB VB NN CC PRP VBP NN .
SOLOR PRP VBD as though PRP VBD VBN NNP IN NNS .
EX VBZ DT LogN that PRP VBZ VBN IN DT NN .
PRP VBD RB VBG DT DObj when PRP VBD IN PRP$ NN .
PRP VBP TO VB RB RB , for PRP VBP NNS IN NN TO VB .
PRP VBD DT DObj TO PRP$ NN .
PRP VBD VBG PRP$ NN when PRP VBD .
DT VBZ DT PLACE where PRP VBD DT NN .
PRP VBP VBN DT NN IN JJ NNS IN PRP since PRP VBD RB IN RB .
VB JJ as PRP MD , PRP RB VBZ JJ TO VB DT NN RB .
DT NNS VBD VBG PRP$ JJ NN when DT NN VBD RP .
Though PRP VBD VBN , RB PRP VBD IN VBG .
NNP VBD PRP RB JJ when PRP VBD PRP$ NNS IN NNP NNP .
Where EX VBZ DT NN , EX VBZ DT NN .
If PRP VBD NN , WP VBD PRP VB .
PRP MD RB VB VBN RB though PRP VBP CD NNS .
NNP VBZ NN which VBZ NN , RB SOLOCCS .
DT LogN VBZ JJ , DT LogN VBZ JJ CC DT LogN VBZ JJ .
Though PRP VBZ JJ , PRP VBZ JJ .
PRP VBD RBR JJ than PRP VBD JJ NN .
MD PRP RB VB RB CC VB PRP that_insert VBP VBN RP .
VB it where PRP MD VB it .
PRP$ LogN VBZ which NN TO DObj .
PRP VBZ JJ .
PRP MD VB RP DT NN IN JJ NN , when PRP MD RB VB RB JJ .
PRP VBD RB RB IN VBG DT NN .
PRP$ NN RB VBD RP IN DT JJ JJ NNS , IN where PRP MD VB NN CC NNS .
Though PRP VBZ RB JJ , RB PRP VBZ RB JJ .
While PRP$ NN VBD VBG DT NN , PRP VBD VBG NN .
PRP VBZ JJ TO VB PRP$ LogN how PRP VBD it .
PRP VBP NN while PRP VBZ NN .
When RB VBN IN NN , WDT PRP RB VBD , PRP MD VB DT IN VBG CC VBG .
NNP , which VBZ IN DT NN , VBZ , RB , JJ IN JJ JJ NN .
Whatever PRP VBD VBZ JJ .
PRP VBP NN IN DT NN IN DT NNPS , CC IN DT NN PRP VBZ JJR .
PRP VBD DT JJ NN that VBD RB .
PRP VBP DT DObj whose NN VBZ JJ .
PRP MD VB PRP NN CC FW MD RB VB PRP .
DT NNS NN VBZ DT NN which PRP MD RB VB RP .
PRP VBZ CD IN DT NNS that VBP RB JJ .
RB though PRP VBZ JJ , PRP VBZ PRP .
PRP VBD RP whether PRP MD VB CC DObj DT NN .
NN VBD whether PRP MD DObj DT NN .
JJ NN VBZ JJR NN CC JJR NNS : RB PRP VBZ PRP$ NN TO VB it .
Unless NNP VB PRP$ NN PRP VBP VBG TO VB DT NN .
EX VBZ DT JJ NN which VBZ NN TO DT NN .
PRP DObj PRP whether PRP VBD VBN PDT DT NN PRP CC IN PRP VBD VBN DT NN .
PRP MD VB PRP VB .
DT NN VBZ RB RB JJ as PRP VBD JJ .
NO Matter how JJ PRP VBP VBN , PRP MD RB DObj DT NN .
DT NN , who VBD VBN RB IN RB CD NNS , VBD TO VB PRP$ NNS .
DT MD VB DT VBG NN IN DT NN , who RB VBZ CD JJR NNS IN DT NN .
DT PLACE where PRP VBD CD NNS RB VBZ VBN VBN RP .
PRP MD VB RB till DT NN VBZ .
Though PRP VBZ JJ , PRP DObj JJ NN .
DT NN who PRP VBD VBZ VBN NNP .
DT VBZ RB JJ DT NN as PRP MD VB IN .
DT LogN VBD TO PRP that RB DT NN VBD VBN DT NN .
NNP VBD RBR than NNS VBP .
PRP VBD RB JJ IN DT NNS , which PRP$ NN RB VBD .
Whether PRP MD VB PRP VBD DT LogN .
How DT VBD VBZ RB JJ TO NN .
When PRP MD VB VBZ RB VBN DObj JJ .
NNS who VBP IN DT NN VBP JJ TO DT NN .
DT VBZ DT TIME when DT NN VBZ JJ IN NNS .
DT NN VBZ that PRP VBP VBN PRP$ NN .
DT NNS RB VBP IN DT NN , which VBZ RB JJ TO NNS .
PRP VBZ as if PRP VBD VBN VBN IN NN .
PRP DObj PRP DT LogN that PRP MD RB VB JJ NN .
PRP MD VB SOLOC that PRP VBZ RB VB .
PRP VBP it JJR so DT NN MD VB PRP .
PRP VBP VBN IN NNP since PRP DObj .
PRP VBP DT LogN how PRP VBD RB , RB IN NN .
PRP$ LogN VBZ that PRP MD VB JJ NN .
PRP VBZ DT JJ NN that PRP VBD TO VB .
DT LogN that DT JJ NN VB VBN VBD DT NN .
PRP VBD that PRP MD VB RP TO DT NNP RB .
NNP VBZ JJ CC PRP VBZ RB JJ TO VB NNS .
PRP VBP it RB JJ that PRP VBZ RP VBG RB DT NN .
PRP VBD that_insert PRP MD VB DT NN DT NN .
PRP VBP DObj PRP DT NN that PRP VBP NNS .
NNP VBD JJ IN DT NNS which DT NN VBD .
PRP VBP RB VB whether CC RB PRP MD VB .
PRP VBZ as though PRP VBD VBN VBN IN NN .
PRP MD VB TO VB NNS VB DT NNS that PRP VBP IN PRP$ NNS .
RB PRP VBD , PRP VBD RB VBN .
DT NN VBZ where NNP NNP RB VBD .
PRP MD VB where PRP VBP JJ .
PRP DT VBP that PRP MD VB , IN NNS IN PRP$ NN VBP JJR .
JJ NNS VBG IN CD MD VB CD JJ NNS , CC RB RB CD VBP JJ IN NN .
DT LogN who MD DObj PRP$ NN VBZ RB RB JJ .
PRP MD VB PRP when PRP DObj NN .
Whether PRP VBZ VBG CC RB VBZ RB VB RB RB .
PRP VBZ DT JJ NN IN JJ NNS TO VB , CC PRP VBZ RB JJ JJ NN NN .
PRP VBP it DT NN that PRP VBP RB VBN TO DT NN .
PRP VBP JJ that PRP VBP VBN PRP RB JJ .
PRP VBP it RB JJ as PRP VBP .
NO Matter which DObj PRP DObj , PRP MD DObj PRP IN DT NN .
PRP VBZ NN , for DT NNS VBP VBG .
PRP$ NN VBD that NNP VBZ DT JJ NN IN DT NN .
VB PRP VB , PRP MD VB PRP .
PRP VBP DT NN , who VBZ VBG DT NN .
PRP MD VB DT LogN whether PRP VBZ TO PRP CC RB .
DT LogN that PRP VBD VBN DT NN RB VBN IN DT JJ NN .
PRP DObj PRP where PRP MD VB CC VB .
PRP VBP DT LogN what VBP NNS PRP VBZ .
NNP NNP VBD DT NN who DObj JJ IN VBG IN NNPS .
PRP VBZ DT JJ NN that PRP VBD NN NN .
PRP VBP RB VB that_insert PRP VBZ DT JJ NN .
PRP MD VB TO VB PRP$ NNS CC PRP$ NN when PRP VBP DT LogN .
NNP VBZ RB VBG IN JJ NNS TO VB DT NN VBN TO DObj NNS TO NNP .
PRP VBD RB DObj PRP when PRP MD VB RB .
DT JJS NN that PRP VBP JJ IN VBD IN DT NN .
PRP VBZ VBN IN NN , as PRP RB VBD .
PRP DObj PRP JJ that PRP MD VB it IN PDT DT JJ NN .
Where EX VBZ JJ EX VBZ JJ TO VB NN .
DT NN VBZ RB IN DT NN , CC RB VBZ IN NN .
PRP VBZ VBN where PRP VBD NN IN DT NN .
PRP VBZ JJR IN PRP$ NN than PRP VBZ IN PRP$ NN .
PRP VBD PRP that NNP VBD RB DObj NN WRB PRP VBD .
Although PRP VBD VBN RP , PRP VBD IN VBG .
PRP MD VB IN NNP unless PRP VBP JJ .
PRP MD VB RP DT NN IN NNP , when PRP MD VB JJ .
NNP NNP , IN whom PRP VBP VBN DT NN , VBZ DT JJ NN .
NO Matter what VBD , PRP MD RB VB .
VBG as PRP VBZ , PRP DObj JJ NN .
PRP VBZ DT NN that NNP MD VB VBN DT NN .
PRP VBP DT NN TO VB PRP$ NN , IN NNS MD VB JJ DT IN DT NN CC IN NNP .
RB as PRP VBZ PRP$ NNS , RB PRP MD VB RB NNS IN PRP$ NNS .
DT LogN VBZ that PRP VBZ RB RB VB .
EX VBP CD NNS IN DT JJ NN , JJS IN which VBP JJ .
NNS VBD DT NN IN NN differently than PRP VBP NN .
JJ NNS IN DT TIME when PRP MD VB VBG DT NN IN DT NN .
When PRP MD VB VBZ RB VBN .
PRP MD RB VB whether CC RB NN MD VB IN NN .
NNS , whose JJ NN VBZ JJ , MD DObj CC DObj IN JJ JJ NNS .
NNP VBZ DT RBS JJ JJ NN that PRP VBP RB VBN RP .
PRP VBZ VBN that NNP NNP VBZ VBN IN NNP .
DT CD NNS VBD JJ IN DT LogN , as VBD VBN RB .
PRP VBP VBN NN , IN EX VBZ DT NN NN .
NNP NNP , whom NN VBZ RB JJ , VBZ CD IN DT JJS NNS IN PRP$ NN .
DT JJ NN that PRP VBD VBD VBN RP IN NN RB .
Where EX VBZ DT NN , EX VBZ DT NN .
PRP DObj VB PRP$ LogN that PRP MD VB JJ TO VB TO NN .
NNP VBD RB JJ when PRP VBD NN IN PRP$ NN TO VB NNP .
PRP VBZ RB VBN RB , IN DT VBZ DT NN IN JJ LogN LogN .
RB SOLOR PRP DObj CD TO CD NNS TO DObj DT NN NN NNS , CC DT VBZ DT RB JJ .
PRP VB RP , CC RB PRP MD VB JJ .
Whatever VBD , PRP MD RB VB .
PRP VBP it JJ that PRP DObj DT NN TO NN .
PRP VBZ VBN what PRP VBD TO VB CD NNS RB .
DT NN VBZ VBN DT NN IN PRP$ JJ JJ NN NN .
DT DObj MD DObj PRP what DT JJS NNS VBP .
NNP VBZ VBN DT LogN why DT NN VBD RB IN LogN .
PRP VBZ RBR than PRP VBZ JJ IN PRP .
When DT NN VBD , NNS VBD VBN VBN .
NNP NNP VBZ that_insert DT JJ NN NN VBZ VBG .
PRP VBD DT NN , which VBD PRP .
PRP MD VB RB , CC PRP MD DObj NNS IN NN .
DT VBZ DT NN how PRP RB VBZ PRP .
PRP VBD NN CC NN , RB , PRP VBD JJ TO DObj DT NNS NN .
DT VBD DT NN why PRP DObj TO VB IN DT NN .
PRP VBZ RB DT JJ NN as PRP VBD .
When PRP MD VB VBZ DT NN .
DT LogN VBZ who PRP MD DObj TO VB PRP .
NO Matter who PRP VBP , PRP MD VB DT NN .
PRP VBD PRP TO VB , IN PRP DObj .
PRP DObj PRP that PRP MD VB TO DT NN DT JJ NN .
PRP VBP JJ NN NNS that PRP RB VB PRP IN JJ NN .
PRP VBP DT NN , who VBZ DT JJ NN .
Where PRP MD DObj PRP VBZ DT LogN .
NNPS MD DObj PRP NN CC PRP MD RB RB VB PRP RB .
PRP VBZ NN SOLOR , RB DT NN MD VB JJR .
PRP VBZ RB DObj DT LogN whether PRP MD VB RB .
PRP VBD RB VBN RB when PRP VBD DT JJ NN IN PRP$ NN .
