DT NN VBZ RB JJ that PRP MD RB VB it .
RB EX VBD RB JJ NNS that PRP VBD RP PDT DT JJ NNS .
PRP VBD so that PRP MD RB VB .
PRP VBZ RB JJ NN that PRP MD RB VB TO DT NN IN PRP .
PRP VBZ JJ JJ NN that PRP MD VB TO VB TO DT NN .
Since PRP VBP DT NN , PRP MD RB DObj PRP .
SOLOR that PRP VBP RB RB , PRP MD VB .
PRP VBD IN NN because PRP VBD JJR .
As PDT DT NNS VBD JJ , PRP VBD RP .
PRP VBD RB VB because PRP VBD JJ .
PRP VBP VBG DT NN lest PRP MD DObj DT JJ DObj .
PRP DObj DT NN RB IN NN that PRP MD VB it .
PRP VBP DT DObj lest PRP MD VB it .
PRP VBZ JJ IN LogN that PRP$ NN MD VB JJ .
NN DObj DT DObj , so that DT NN VBD VBN IN NN .
PRP RB JJ DObj PRP$ JJ DObj , PRP RB VBZ IN PRP .
DT VBZ PRP VBD PRP$ NN , CC MD PRP VB RB .
RB SOLOR PRP VBZ DT JJ NN CC PRP VBP VBG PRP$ NN IN DT NN .
DT VBD that_insert DT JJ NN VBP NN CC VBD PRP$ NN NN IN PRP .
RB SOLOR PRP VBZ DT JJ NN CC PRP VBP VBG PRP$ NN IN DT NN .
PRP MD VB RB JJ if PRP VBZ PRP VB IN DT NN .
NO Matter when PRP VBZ , DT NN VBZ VBN .
That PRP MD VB NNS VBZ DT LogN .
PRP VBP SOLOC TO DObj JJ IN NNS , for PRP RB DObj TO DT JJ NNS .
PRP VBD DT NN , for PRP VBD RB JJ .
PRP$ LogN VBZ that PRP MD DObj PRP .
DT VBZ what PRP VBP RB IN .
Where EX VBZ JJ EX VBZ JJ TO VB NN .
DT LogN that DT JJ NN VB VBN VBD DT NN .
DT NN who VBD VBD DT NN IN NNP .
DT JJ NN VBZ DT NN , who VBZ IN DT NN .
DT LogN VBZ who PRP MD DObj TO VB PRP .
PRP VBZ RBR than PRP$ NN VBZ .
PRP VBZ RB as DT VBZ WP PRP VBP , IN PRP VBD VBG RB IN RB .
PRP MD RB DObj JJ RB because DT NNS VBP JJ IN PRP .
PRP VBZ TO VB IN NNP , which PRP VBZ RB VB .
DT NN VBZ RB JJ , which DObj PRP RB JJ .
PRP VBZ JJ that PRP MD VB RB IN DT NNP .
DT NNS VBD RP DT JJ NN where PRP VBD RP CC VBD .
DT LogN VBZ when PRP MD DObj DT DObj NN .
PRP$ LogN VBZ which NN TO DObj .
DT NN VBZ IN DT TIME when NNS VBD NNS .
PRP VBZ JJ .
If PRP VB PRP$ NN IN DT JJ NN , DT NN NN MD RB DObj PRP .
PRP RB VBD IN DT NN whose NNS has VBN IN .
If PRP VBD PRP , PRP MD VB PRP TO DT NN .
PRP VBP NN IN DT NN IN DT NNPS , CC IN DT NN PRP VBZ JJR .
PRP MD VB RB SOLOC that_insert DT NN VBZ IN PRP .
VBG as PRP VBZ , PRP VBP DT NN .
NNP VBZ RB RB what PRP VBD TO VB .
DT JJ NN that PRP VBP TO VB SOLOR VBZ TO VB DT NN .
PRP MD RB DObj DObj IN DT NN NN before PRP DObj PRP$ NN NN .
PRP VBP DT DObj whose NN VBZ JJ .
That PRP MD RB VB TO DT NN DT NN VBZ JJ .
NNP MD VB DT JJ NN NN IN JJ NNS CC JJR NNS .
DT NNS who VBD IN NNP IN DT CD NNS VBD NNP NNP VBD DT IN PRP$ NN IN NNP .
Which NN MD VB VBZ RB JJ .
PRP MD RBR VB SOLOR , RB PRP MD VB DT NN .
PRP$ NN VBD PRP DT LogN how PRP MD VB DT NN .
PRP VBZ DT JJ NN that PRP VBD TO VB .
DT NN MD VB JJ CC PRP MD VB JJ .
DT NN VBZ that PRP VBP JJ IN NNS .
DT who VBP TO VB TO DT NN MD VB IN DT NN NN IN CD NN NN .
PRP VBD TO NN IN CD , IN when PRP VBD VBG IN DT NN .
NNP NNP VBZ RB DT NN whom PRP VBP TO VB .
PRP VBZ DT JJ NN that PRP VBP .
DT VBZ DT JJ NN that DObj IN NN DT NN IN RB .
PRP MD VB IN NNP unless PRP VBP JJ .
NNS who VBP IN DT NN VBP JJ TO DT NN .
NNP , which VBZ DT JJ JJ , VBZ JJ NNS .
WP VBD that_insert DT NN VBZ DT LogN .
DT NN VBZ RB JJ as PRP VBD RB JJ .
NN VBD .
NNP CC JJ NN VBZ what PRP VBP IN .
DT NN whom PRP VBP VBG IN VBZ VBN .
PRP VBP TO VB RB RB , for PRP VBP NNS IN NN TO VB .
DT LogN VBZ whether PRP MD VB JJ TO VB PRP .
RB VBZ DT NN that PRP VBD DObj PRP IN .
DT NN VBZ RB IN DT NN , CC RB VBZ IN NN .
PRP VBZ JJR IN PRP$ NN than PRP VBZ IN PRP$ NN .
PRP VBD TO NN after PRP VBD PRP$ NN .
WP MD PRP VB if PRP DObj DT NN IN NN .
PRP VBP as PRP MD VB JJ IN NN .
PRP MD VB RB if PRP MD RB DObj DT NN .
NNP VBP TO DT NNS as PRP MD VB VBN IN .
PRP VBP VBN RB JJR NN DT NN than PRP VBD DT NN .
PRP VBP JJ that PRP MD VB PRP .
NNP though PRP VBZ , PRP DObj JJ NN .
PRP$ LogN VBZ that PRP MD VB JJ NN .
While NNP VBD VBG PRP$ NN , NNP VBD TO VB PRP .
DT NN why PRP VBD VBN VBZ JJ TO PRP .
Whatever PRP VBD VBZ JJ .
DT LogN that DT NN IN DT NN NN MD VB IN NN VBZ RB VBN .
PRP MD DObj PRP$ NNS TO VB DT NNS .
DT VBZ where PRP VBP JJ .
How DT VBD VBZ RB JJ TO NN .
CD NNS VBD RB JJ IN NNP IN JJ NNS , CC PRP VBD JJ IN DT NNP .
DT NN NNS , which PRP VBD CD NNS RB , VBP RB VBN DT NN .
As NN VBZ TO NN , RB NN VBZ TO NN .
PRP VBD DT NN where DT NN IN NNS VBD VBN .
RB as PRP VBZ PRP$ NNS , RB PRP MD VB RB NNS IN PRP$ NNS .
PRP VBP JJ .
What PRP VBP VBZ JJR NN .
EX VBZ DT NN who VBZ TO VB PRP .
PRP VBD RB VB TO NN until PRP$ NN VBD RB .
RB though PRP VBZ JJ , PRP VBZ PRP .
DT NNPS , which VBZ SOLOR JJ RB TO VB RP , VBD JJ IN IN DT CD NNS .
NO Matter what VBD , PRP MD RB VB .
DT NNS DObj RBR when NNP VBZ .
If PRP VBP NN IN DT , PRP MD RB VB TO VB it .
Though PRP VBZ JJ , PRP RB VBZ .
PRP VBZ JJ LogN that DT NN VBZ RB DT NN .
PRP DObj that PRP MD VB TO DT NN DT JJ NN .
RB PRP VBD , PRP VBD RB VBN .
PRP VBZ DT JJ NN IN DT NNS that VBZ VBN TO VB .
Whether DT NN MD VB VBN RP VBZ RB VBN VBN RB .
VB RB CC RB PRP MD VB DT JJ NN .
As VBZ VBN TO DT NNP , NNP VBZ DT JJ JJ NN .
SOLOC that_insert EX VBZ DT NN , PRP MD VB DT NN RB .
Unless NNP VB PRP$ NN PRP VBP VBG TO VB DT NN .
NNP NNP , IN whom PRP VBP VBN DT NN , VBZ DT JJ NN .
PRP VBD whether TO VB RB .
When PRP MD VB NN MD VB DObj RB .
PRP MD VB DT LogN whether PRP VBZ TO PRP CC RB .
PRP DObj PRP where PRP MD VB CC VB .
DT NN why PRP VBD RB DObj DT NN VBD IN PRP$ NNP VBD RB RB JJ .
IN DT NN PRP VBD RB , PRP VBD VBN DT DObj .
PRP VBZ RB VBN RB , IN DT VBZ DT NN IN JJ LogN LogN .
PRP MD VB RB , RB PRP MD RB DObj DT NN .
PRP VBD DT JJ NN , though DT NNS VBD VBN .
PRP VBD DObj IN DT JJ NN , where EX VBD DT VBG NN .
DT VBZ why PRP VBP TO DT LogN .
DT NN whose NN PRP VBP RP DObj JJ NN TO VBG PRP$ VBG NNS .
PRP VBP JJ NN NNS that PRP RB VB PRP IN JJ NN .
NO Matter which DObj PRP DObj , PRP MD DObj PRP IN DT NN .
PRP MD VB PRP NN CC FW MD RB VB PRP .
DT VBZ what PRP VBP .
PRP VBP DT NN TO VB PRP$ NN , IN NNS MD VB JJ DT IN DT NN CC IN NNP .
Though PRP VBD VBN RP , RB PRP VBD IN VBG .
DT VBZ why PRP VBD RB VB .
DT LogN that PRP MD VB RB JJ NN VBZ TO VB VBN .
Whether PRP VB it CC RB , PRP VBZ JJ .
That PRP MD VB DT NN VBZ JJ .
After PRP VBD VBN DT NN , PRP VBD NN .
DT LogN VBZ whether DT NN VBZ VBG IN PRP .
NNP VBD PRP RB JJ when PRP VBD PRP$ NNS IN NNP NNP .
PRP VBD VBG IN DT when PRP VBD PRP$ NN VBD .
PRP VBZ as if NN VBZ VBG IN DT NN .
PRP VBZ NN IN NN IN DT NN NN , IN DT NN PRP VBP IN NN IN NN .
PRP VBZ RB JJR TO DObj NNS when PRP VBP JJ NNS .
PRP VBZ as if PRP VBD DT NN .
DT JJR DT NN VBZ , DT JJR DT NN VBZ .
NNS VBZ JJ TO VB once PRP VBP DT NNS .
Although PRP VBD VBN RP , RB PRP VBD IN VBG .
PRP$ LogN VBZ that PRP MD VB it DT NN IN RB .
VB it where PRP MD VB it .
VB PRP$ LogN whether PRP VBP VBG .
DT LogN VBZ who MD VB DT NN .
Whenever PRP VBZ , DT NN VBZ VBN .
SOLOCCS that PRP VBP DObj DT NN , PRP MD RB VB VBN .
PRP VBP JJ , for PRP VBZ JJ .
VB PRP PRP$ LogN that PRP MD VB TO PRP$ NN DT NN .
PRP VBP RBR than PRP VBP JJ IN PRP .
PRP$ NN , who VBZ PRP RB JJ , VBZ JJ IN PRP .
If PRP VBP IN DT NN , PRP MD VB PRP RP .
VB RP where PRP VBD IN .
PRP RB VBD RP DT JJS NN , which RB VBD CD NNS .
Though PRP VBD VBN , RB PRP VBD IN VBG .
DT JJ NN VBD IN DT JJ TIME when PRP RB VBD it .
DT LogN whether PRP MD VB IN DT NN VBD VBN IN JJ NN .
NN PRP VBD DT JJ NN who VBD VBN PRP$ NN .
PRP VBP it JJR so DT NN MD VB PRP .
PRP VBZ JJ that PRP MD VB RB IN PRP$ NN .
PRP VBP VBN IN NNP VBG IN DT LogN that PRP MD RB VB JJ TO VB PRP DT NN .
DT NN that PRP VBD TO PRP VBZ RB JJ .
NO Matter what PRP VBP , PRP MD RB VB PRP .
PRP VBD TO DObj PRP$ NN IN PRP , as VBD RB DT NN .
PRP VBZ RB VB whether PRP MD VB CC RB .
Though PRP VBZ JJ , PRP DObj JJ NN .
VB IN DT NNS IN NNS where PRP VBZ JJ .
PRP MD RB VB VBN RB though PRP VBP CD NNS .
PRP VBP PRP DT JJR , DT JJR PRP VBP PRP .
PRP MD VB PRP VB .
PRP MD VB SOLOR , for PRP$ NN VBZ VBG IN PRP .
DT NN VBD VBN IN DT NNP PRP , who VBD DT JJ NN IN NNP NNP .
If PRP DObj PRP , PRP MD VB PRP .
DT NN which VBZ IN NNP VBZ NN .
RB VBD that_insert DT NN MD VB , DT JJ MD RB VB JJR CC JJR .
NNS IN NN VBP VBN JJ NNS IN VBG NN IN DT NN .
Whatever PRP VBP , PRP MD RB VB PRP .
PRP DObj if PRP VBD RB VB TO NN NN .
PRP VBZ DT NN that NNP MD VB VBN DT NN .
PRP VBD RB VBG DT DObj when PRP VBD IN PRP$ NN .
PRP VBD RB VBD PRP$ NN when DT NN VBD IN PRP .
VBZ PRP DT NN that DObj NNS .
PRP VBZ VBG when MD PRP VB DT difficult NN .
RBS JJ JJ JJ NNS SOLOR VBP IN NNS IN PRP$ NN , so DT NN IN DT NN VBZ JJ NNS IN JJ NN .
Although NN VBZ JJ , PRP VBZ NN .
VB as PRP MD , PRP MD VB .
NNP VBD JJ , IN PRP VBD RB VB TO NN .
