PRP VBZ RB JJ IN PRP MD VB TO NN .
PRP VBZ RB RB IN DT NN MD VB PRP .
RB EX VBD RB JJ NNS IN PRP VBD RP PDT DT JJ NNS .
EX VBZ RB JJ DT NN IN NN IN DT NN NN VBZ VBN .
PRP VBZ PDT DT JJ NN IN PRP MD RB VB PRP .
PRP VBP RB IN PRP VBP TO VB DT NN NN IN DT NN .
RB IN PRP VBP RB RB , PRP MD VB .
PRP VBD PRP IN PRP VBD JJ .
RB IN PRP VBP RB , PRP MD RBR VB .
IN PRP VBP DT NN , PRP MD RB VB PRP .
PRP VBD RP RB RB IN PRP MD VB DT JJ NN .
JJS NNS VBP TO NN RB IN PRP MD VB NNS , NNS CC NNS .
PRP VBP DT NN IN PRP MD VB PRP .
PRP VBD DT NN RB IN NN IN PRP MD VB PRP .
PRP VBD RB RB IN PRP MD RB VB PRP$ NNS .
PRP RB JJ VBZ JJ CC RB PRP VBZ JJ .
PRP$ NN VBZ DT NN CC PRP$ NN VBZ DT NN .
PRP RB JJ VBZ JJ CC RB PRP VBZ JJ .
DT NNS IN NNS VBP VBG PRP NN IN VBG CC VBG JJ NN , CC DT VBZ RB JJ VBG DT NN IN NNS .
PRP VBP VBG NN , PRP$ NN VBZ VBG NN CC PRP$ NN VBZ VBG NN .
PRP VBD PRP JJ IN PRP MD VB PRP IN PDT DT JJ NN .
PRP VBD IN JJ NNS IN PRP VBP VBN TO VB VBN .
DT VBZ DT JJ NN WDT VBD IN NN DT NN IN RB .
IN PRP VBZ JJ , CC PRP VBZ JJ .
PRP VBP DT NN , WP VBZ DT JJ NN .
IN PRP VBP TO VB NN PRP MD VB JJR NN .
IN NN VBZ TO NN , RB NN VBZ TO NN .
IN PRP VBZ , DT NN MD VB VBN .
DT VBZ RB JJ DT NN IN PRP MD VB IN .
DT NN VBD DT NN IN DT NNS MD VB DT NN IN RB .
WP MD PRP VB IN PRP VBP DT NN IN NN .
PRP DT VBP WP PRP VBD TO VB JJ .
NNP IN PRP VBN IN DT NN VBZ RB DT NN .
NNP VBZ DT NN WDT VBZ VBN IN JJS NNS .
DT NN VBN IN NNS IN NNP IN NNS , CC PRP MD RB VB DT NN .
DT VBZ DT NN WRB PRP RB VBZ PRP .
PRP VBZ JJR IN PRP$ NN IN PRP VBZ IN PRP$ NN .
PRP VBZ JJ IN PRP MD VB JJ TO VB .
RB IN PRP VBZ PRP$ NNS , RB PRP MD VB RB NNS IN PRP$ NNS .
IN PRP VBD VBN RP , RB PRP VBD IN VBG .
IN NN , RB , DT NNP NNP VBZ VBN TO VB NN WRB EX VBZ JJ NN .
PRP VBP RB IN NN RB CC PRP VBP DT NNS TO VB .
NNP VBZ TO VB DT JJR NN IN VBG NNS IN JJ NN .
PRP VBP DT NN IN DT VBG NNS CC DT VBZ VBN IN PRP$ NN TO VB IN NN NNS .
IN PRP VBZ RB JJ , PRP MD VB JJ TO VB PRP$ NN POS NN NN RBR .
PRP MD VB TO VB DT JJ NN WP PRP VBP RB VBN IN .
PRP VBZ NNP RB JJ .
PRP VBP , VB CC VB WRB PRP$ NNS VBP VBN CC VBN .
PRP MD VB PRP RB RB IN PRP VBP NN .
PRP$ NN MD VB NN .
DT JJR DT NN VBZ , DT JJR DT NN VBZ .
PRP VBD DT NN IN PRP MD VB PRP .
EX VBZ DT NN WP VBZ TO VB PRP .
PRP MD RB VB NNS IN DT NN NN IN PRP VBP PRP$ NN NN .
WDT IN DT NNS IN PRP VBD NN VBD VBN IN NNP .
DT VBZ WRB PRP VBD RB VB .
PRP VBZ TO VB VBN IN PRP MD VB PRP JJ CC JJ .
NNS VBP VBN IN DT NN VBZ IN DT NN .
DT NN , WP$ NNS VBZ RB JJ , VBZ JJ IN DT NN .
PRP MD RB VB DT CD NNS IN PRP VBD IN DT JJ JJ NN .
IN PRP VB PRP$ NN IN DT JJ NN , DT NN NN MD RB VB PRP .
PRP VBD PRP DT NNS .
PRP VBP RB VBN PDT DT NN IN PRP VBD RP .
DT NN WDT PRP VBD TO VB JJ NN VBD RB JJ IN DT .
PRP VBP RB VBN IN NN WDT MD VB IN NN TO PRP .
PRP VBD DT NN .
WP MD PRP VB IN PRP VBP DT NN IN NN .
PRP VBD DT JJ NN WDT VBD RB .
DT NNPS , WDT VBZ RB JJ RB TO VB RP , VBD JJ IN IN DT CD NNS .
PRP MD VB WRB PRP VBP JJ .
PRP$ NN VBD PRP DT NN WRB PRP MD VB DT NN .
PRP VBD VBG DT NNS CC NNS WDT VBD DT NN .
PRP VBD DT NN IN DT NN VB VBN .
PRP VBD IN NN IN DT NN , RB PRP MD VB VBN PRP DT NN .
WRB JJ PRP VBP VBN , PRP MD RB VB DT NN .
PRP VBZ VBN TO PDT DT JJ NNS IN JJ NNS .
PRP VBD DT NN JJ .
PRP MD VB DT NN IN PRP VBZ TO PRP CC RB .
PRP MD VB VBN DT NN WRB PRP VBD PRP .
NNS IN NN VBP VBN JJ NNS IN VBG NN IN DT NN .
PRP VBP PRP DT NN WRB PRP VBD DT NN .
PRP RB VBD JJ NNS IN PRP VBZ .
WP VBD DT NN VBZ DT NN .
DT NN VBD RB VB RB RB IN PRP VBD .
PRP VBP PRP RB JJ IN PRP VBP .
DT NNS WP VBP VBG NN VBP IN NNP CD .
PRP VBZ DT JJ NN IN PRP VBD NN NN .
DT NN , WDT PRP$ NN VBD PRP IN NNP , VBZ RB JJ IN VBG PRP$ NNP NNP .
PRP MD RBR VB DT NN IN PRP , IN PRP VBZ VBG TO VB .
MD PRP VB VB DT JJ NNS IN PRP VBP .
PRP VBD DT JJ NN WDT MD VB RP DT NNS .
PRP VBP RB JJ IN JJ CC PRP VBP DT JJ NN .
DT NN MD VB JJ CC PRP MD VB JJ .
PRP VBD DT NN IN WP PRP VBD CD NNS .
DT NN IN NN VBP JJR RP IN PRP VBD TO VB .
PRP VBZ JJ .
DT NN NNS , WDT PRP VBD CD NNS RB , VBP RB VBN DT NN .
NNP VBZ DT RB JJ CC PRP VBZ RB JJ .
PRP VBZ DT NN , WP VBZ DT NN .
PRP VBZ JJ TO VB PRP$ NN WRB PRP VBD PRP .
DT NN WP VBD VBD DT NN IN NNP .
NNP VBZ DT NN .
NNP VBD RB JJ WRB PRP VBD NN IN PRP$ NN TO VB NNP .
PRP VBP DT NN TO VB PRP$ NN , IN NNS MD VB JJ DT IN DT NN CC IN NNP .
DT NN IN PRP MD VB DT JJ NNS TO VB DT JJ NNS VBD VBN NN .
PRP VBZ DT NN NN IN PRP VBP RB VBD TO .
PRP VBD IN PRP VBD RB VBN PRP RB , WDT VBD RB JJ .
DT JJ NN VBZ RB IN PRP VBZ DT JJ NN .
VBP PRP VBN DT NN NN , WP$ JJ NN VBZ NN JJ .
PRP VBD VBG IN DT WRB PRP VBD PRP$ NN VBD .
PRP VBZ WRB EX VBP DT NN NN .
PRP VBD VBN IN DT NN IN DT NN VB VBN .
DT WP VBD VBN IN DT NNS RB VBD VBD .
EX VBZ DT JJ NN WDT VBZ NN TO DT NN .
PRP$ NN VBZ IN PRP MD VB VBG NNS RB RB .
PRP VBP RB VB NNS MD VB .
PRP VBP VBN DT NN IN NNP VBD VBN DT NN .
PRP DT VBP IN PRP MD VB , IN NNS IN PRP$ NN VBP JJR .
PRP MD VB RB JJ IN PRP VBZ PRP VB IN DT NN .
PRP MD RB VB IN CC RB NN MD VB IN NN .
PRP DT VB RP WRB PRP VBD DT NN IN PRP$ NN VBD DT JJ NN .
PRP VBD PRP MD VB DT NN DT NN .
DT NN VBD VBN IN DT NNP PRP , WP VBD DT JJ NN IN NNP NNP .
DT NN , WP$ NNS VBZ JJ , VBZ JJ IN DT JJ NNS .
DT NN VBZ WRB NNP NNP RB VBD .
DT NN VBZ DT RBR , DT JJR NN PRP VBZ .
MD PRP VB PRP IN PRP MD VB CC RB NN .
IN PRP VBP JJ NN TO DT NN , PRP MD VB DT JJR NN .
DT NN , WDT PRP VBD JJ NN , VBZ RB JJ .
VB PRP VB , PRP MD VB PRP .
EX VBD JJ NNS WRB PRP VBD DT NN IN PRP .
PRP VBZ JJ CC JJ , CC RB NNS VBP PRP .
NNP NNP VBZ RB DT NN WP PRP VBP TO VB .
PRP MD VB VBN IN PRP VBZ RB VB .
PRP VBZ NN , IN DT NNS VBP VBG .
DT NN VBD IN DT NN VBZ IN DT NN NN .
PRP MD RB VB VBN RB IN PRP VBP CD NNS .
NNP MD VB DT JJ NN NN IN JJ NNS CC JJR NNS .
WRB PRP VBZ , DT NN VBZ VBN .
PRP VBZ RB RB IN PRP VBD JJ .
DT NN , WP$ NNS VBZ RB JJ , VBZ JJ IN DT NN .
PRP MD VB VBG IN PRP$ NNS VBP VBN .
IN PRP VBP DT NN , PRP VBP RB VB DT NN .
PRP MD VB RB , RB PRP MD VB DT NN .
IN PRP VBZ JJ , PRP VBZ JJ .
NNPS MD VB PRP NN CC PRP MD RB RB VB PRP RB .
DT JJ NN IN PRP VBD VBD VBN RP IN NN RB .
NNS VBD DT NN IN NN RB IN PRP VBP NN .
PRP MD VB DT NN WP$ NNS VBZ RP IN DT NN .
PRP VBD VBG PRP$ NN WRB PRP VBD .
DT JJ NN DT VBZ NN CC JJ JJ NNS .
WRB PRP VBP EX VBP RB IN NNS .
PRP VBZ RB VB DT NN IN PRP VBZ CC RB .
PRP VBD VB PRP$ NN IN PRP MD VB JJ TO VB TO NN .
PRP VBD DT NN IN PRP VBP DT NN .
PRP MD VB TO VB NNS VB DT NNS IN PRP VBP IN PRP$ NNS .
PRP VBD NN WDT VBD PRP JJ .
PRP MD VB DT NN VBG IN PRP MD VB PRP IN PRP$ JJ NN .
PRP VBD VBN VBN CC PRP VBD VBN .
PRP RB VBD RP DT JJ NNS WDT VBD TO VB VBN RB IN VBG .
PRP VBZ DT NN TO PRP WRB PRP DT VBD .
DT NN WP MD VB PRP$ NN VBZ RB RB JJ .
VBG PRP VBP VBN DT NN , PRP MD RB VB VBN .
PRP VBD JJ DT NN , RB PRP MD VB VBN NN IN DT NNS VB .
DT NNP NNP CC JJ JJ NNS RB RB VBD RP NNS IN NN , CC NNP VBZ RB VBD .
DT VBZ DT NN WRB PRP VBD DT NN .
PRP VBD RB VB PRP WRB PRP MD VB RB .
PRP VBD WP PRP VBD VBN TO VB JJ .
NNP VBZ PRP JJ .
WP PRP VBP TO VB VBZ DT .
WRB PRP VBP TO VB DT NN , PRP VBP RB JJ IN PRP VBP .
PRP$ NN VBZ WDT NN TO VB .
PRP VBP VBN , CC PRP MD VB RB .
PRP WP VBZ JJ NNS RBS .
DT NN WRB PRP VBD CD NNS RB VBZ VBN VBN RP .
NN PRP MD VB RB DT NN WDT PRP VBD IN .
PRP VBP RB RB RB IN PRP VBZ VBD RP .
IN PRP VBD VBN DT NN , PRP VBD NN .
DT NN VBZ WRB PRP MD VB DT NNS PRP VBP .
PRP VBZ NN , IN DT NNS VBP VBG .
PRP VBD DT NN WRB DT NN IN NNS VBD VBN .
PRP MD VB RB , CC PRP MD VB NNS IN NN .
NNP DT NN VBZ RB JJ , CC PRP VBP TO VB .
PRP VBD DT RBR VBN DT NN IN PRP VBD VBN IN NN .
PRP VBD DT NN IN PRP$ NN VBD VBN .
NNP NNP VBZ DT JJ NN IN DT NNP NNP NNP VBZ TO VB DT JJ NN IN NN VBG NNS IN DT NN .
NN PRP VBD DT NN WDT VBD IN NNP .
PRP VBD DT JJ NN , IN DT NNS VBD VBN .
PRP MD VB JJ WRB PRP VBP JJ CC JJ .
DT JJR PRP VBP , DT JJR PRP VBP PRP$ NN .
IN PRP$ NN EX VBP CD NNS , DT JJS IN WP VBZ NNP NNP .
RB IN PRP VBZ JJ , PRP VBZ PRP .
PRP VBP RB VB WP PRP MD VB RP .
PRP MD VB PRP WRB PRP VBP NN .
PRP VBD VBG DT NNS , CC PRP RB VBD RB IN NN .
PRP MD VB TO VB DT NN IN PRP VBP JJ CC JJ .
JJ NNS IN DT NN WRB PRP MD VB VBG DT NN IN DT NN .
PRP VBZ RB IN NN VBZ VBG IN DT NN .
VB IN PRP VBD , PRP MD RB VB DT NN RB RB .
DT NN WP PRP VBD VBZ VBN NNP .
