PRP VBZ RB JJ that PRP MD VB TO NN .
PRP VBZ RB RB that DT NN MD VB PRP .
RB EX VBD RB JJ NNS that PRP VBD RP PDT DT JJ NNS .
EX VBZ RB JJ DT increase IN NN that DT NN NN VBZ VBN .
PRP VBZ PDT DT JJ NN that PRP MD RB VB PRP .
PRP VBP RB because PRP VBP TO VB DT NN NN IN DT NN .
RB that PRP VBP RB RB , PRP MD VB .
PRP VBD PRP because PRP VBD JJ .
RB that PRP VBP RB , PRP MD RBR VB .
As PRP VBP DT NN , PRP MD RB VB PRP .
PRP VBD RP RB RB that PRP MD VB DT JJ NN .
JJS NNS VBP TO NN so that PRP MD VB NNS , NNS CC NNS .
PRP VBP DT NN lest PRP MD VB PRP .
PRP VBD DT NN RB IN NN that PRP MD VB PRP .
PRP VBD RB RB that PRP MD RB VB PRP$ NNS .
PRP RB JJ VBZ JJ CC RB PRP VBZ JJ .
PRP$ NN VBZ DT NN CC PRP$ NN VBZ DT NN .
PRP RB JJ VBZ JJ CC RB PRP VBZ JJ .
DT NNS IN NNS VBP VBG PRP NN IN VBG CC VBG JJ NN , CC DT VBZ RB JJ VBG DT NN IN NNS .
PRP VBP VBG NN , PRP$ NN VBZ VBG NN CC PRP$ NN VBZ VBG NN .
PRP VBD PRP JJ that PRP MD VB PRP IN PDT DT JJ NN .
PRP VBD IN JJ NNS as PRP VBP VBN TO VB VBN .
DT VBZ DT JJ NN that VBD IN NN DT NN IN RB .
Though PRP VBZ JJ , CC PRP VBZ JJ .
PRP VBP DT NN , who VBZ DT JJ NN .
If PRP VBP TO VB NN PRP MD VB JJR NN .
As NN VBZ TO NN , RB NN VBZ TO NN .
Unless PRP VBZ , DT NN MD VB VBN .
DT VBZ RB JJ DT NN as PRP MD VB IN .
DT NN VBD DT NN that DT NNS MD VB DT NN IN RB .
WP MD PRP VB if PRP VBP DT NN IN NN .
PRP DT VBP what PRP VBD TO VB JJ .
NNP IN PRP VBN IN DT NN VBZ RB DT NN .
NNP VBZ DT NN which VBZ VBN IN JJS NNS .
DT NN VBN IN NNS IN NNP IN NNS , CC PRP MD RB VB DT NN .
DT VBZ DT NN how PRP RB VBZ PRP .
PRP VBZ JJR IN PRP$ NN than PRP VBZ IN PRP$ NN .
PRP VBZ JJ whether PRP MD VB JJ TO VB .
RB as PRP VBZ PRP$ NNS , RB PRP MD VB RB NNS IN PRP$ NNS .
Though PRP VBD VBN RP , RB PRP VBD IN VBG .
IN NN , RB , DT NNP NNP VBZ VBN TO VB NN wherever EX VBZ JJ NN .
PRP VBP RB IN NN RB CC PRP VBP DT NNS TO VB .
NNP VBZ TO VB DT JJR NN IN VBG NNS IN JJ NN .
PRP VBP DT NN IN DT VBG NNS CC DT VBZ VBN IN PRP$ NN TO VB IN NN NNS .
if PRP VBZ RB JJ , PRP MD VB JJ TO VB PRP$ NN POS NN NN RBR .
PRP MD VB TO VB DT JJ NN whom PRP VBP RB VBN IN .
PRP VBZ NNP RB JJ .
PRP VBP , VB CC VB where PRP$ NNS VBP VBN CC VBN .
PRP MD VB PRP RB RB as PRP VBP NN .
PRP$ NN MD VB NN .
DT JJR DT NN VBZ , DT JJR DT NN VBZ .
PRP VBD DT NN whether PRP MD VB PRP .
EX VBZ DT NN who VBZ TO VB PRP .
PRP MD RB VB NNS IN DT NN NN before PRP VBP PRP$ NN NN .
WDT IN DT NNS that PRP VBD NN VBD VBN IN NNP .
DT VBZ why PRP VBD RB VB .
PRP VBZ TO VB VBN whether PRP MD VB PRP JJ CC JJ .
NNS VBP VBN that DT NN VBZ IN DT NN .
DT NN , whose NNS VBZ RB JJ , VBZ JJ IN DT NN .
PRP MD RB VB DT CD NNS that PRP VBD IN DT JJ JJ NN .
If PRP VB PRP$ NN IN DT JJ NN , DT NN NN MD RB VB PRP .
PRP VBD PRP DT NNS .
PRP VBP RB VBN PDT DT NN as PRP VBD RP .
DT NN which PRP VBD TO VB JJ NN VBD RB JJ IN DT .
PRP VBP RB VBN IN NN which MD VB IN NN TO PRP .
PRP VBD DT NN .
WP MD PRP VB if PRP VBP DT NN IN NN .
PRP VBD DT JJ NN that VBD RB .
DT NNPS , which VBZ RB JJ RB TO VB RP , VBD JJ IN IN DT CD NNS .
PRP MD VB where PRP VBP JJ .
PRP$ NN VBD PRP DT NN how PRP MD VB DT NN .
PRP VBD VBG DT NNS CC NNS that VBD DT NN .
PRP VBD DT NN that DT NN VB VBN .
PRP VBD IN NN IN DT NN , RB PRP MD VB VBN PRP DT NN .
However JJ PRP VBP VBN , PRP MD RB VB DT NN .
PRP VBZ VBN TO PDT DT JJ NNS IN JJ NNS .
PRP VBD DT NN JJ .
PRP MD VB DT NN whether PRP VBZ TO PRP CC RB .
PRP MD VB VBN DT NN where PRP VBD PRP .
NNS IN NN VBP VBN JJ NNS IN VBG NN IN DT NN .
PRP VBP PRP DT NN why PRP VBD DT NN .
PRP RB VBD JJ NNS as PRP VBZ .
WP VBD that_insert DT NN VBZ DT NN .
DT NN VBD RB VB RB RB as PRP VBD .
PRP VBP PRP RB JJ as PRP VBP .
DT NNS who VBP VBG NN VBP IN NNP CD .
PRP VBZ DT JJ NN that PRP VBD NN NN .
DT NN , which PRP$ NN VBD PRP IN NNP , VBZ RB JJ IN VBG PRP$ NNP NNP .
PRP MD RBR VB DT NN IN PRP , for PRP VBZ VBG TO VB .
MD PRP VB VB DT JJ NNS that PRP VBP .
PRP VBD DT JJ NN that MD VB RP DT NNS .
PRP VBP RB JJ IN JJ CC PRP VBP DT JJ NN .
DT NN MD VB JJ CC PRP MD VB JJ .
PRP VBD DT NN IN whom PRP VBD CD NNS .
DT NN IN NN VBP JJR RP than PRP VBD TO VB .
PRP VBZ JJ .
DT NN NNS , which PRP VBD CD NNS RB , VBP RB VBN DT NN .
NNP VBZ DT RB JJ CC PRP VBZ RB JJ .
PRP VBZ DT NN , who VBZ DT NN .
PRP VBZ JJ TO VB PRP$ NN how PRP VBD PRP .
DT NN who VBD VBD DT NN IN NNP .
NNP VBZ DT NN .
NNP VBD RB JJ when PRP VBD NN IN PRP$ NN TO VB NNP .
PRP VBP DT NN TO VB PRP$ NN , IN NNS MD VB JJ DT IN DT NN CC IN NNP .
DT NN that PRP MD VB DT JJ NNS TO VB DT JJ NNS VBD VBN NN .
PRP VBZ DT NN NN that PRP VBP RB VBD TO .
PRP VBD that PRP VBD RB VBN PRP RB , WDT VBD RB JJ .
DT JJ NN VBZ as if PRP VBZ DT JJ NN .
VBP PRP VBN DT NN NN , whose JJ NN VBZ NN JJ .
PRP VBD VBG IN DT when PRP VBD PRP$ NN VBD .
PRP VBZ where EX VBP DT NN NN .
PRP VBD VBN IN DT NN that DT NN VB VBN .
DT who VBD VBN IN DT NNS RB VBD VBD .
EX VBZ DT JJ NN which VBZ NN TO DT NN .
PRP$ NN VBZ that PRP MD VB VBG NNS RB RB .
PRP VBP RB VB that_insert NNS MD VB .
PRP VBP VBN DT NN that NNP VBD VBN DT NN .
PRP DT VBP that PRP MD VB , IN NNS IN PRP$ NN VBP JJR .
PRP MD VB RB JJ if PRP VBZ PRP VB IN DT NN .
PRP MD RB VB whether CC RB NN MD VB IN NN .
PRP DT VB RP when PRP VBD DT NN IN PRP$ NN VBD DT JJ NN .
PRP VBD that_insert PRP MD VB DT NN DT NN .
DT NN VBD VBN IN DT NNP PRP , who VBD DT JJ NN IN NNP NNP .
DT NN , whose NNS VBZ JJ , VBZ JJ IN DT JJ NNS .
DT NN VBZ where NNP NNP RB VBD .
DT NN that_insert VBZ DT RBR , DT JJR NN PRP VBZ .
MD PRP VB PRP whether PRP MD VB CC RB NN .
If PRP VBP JJ NN TO DT NN , PRP MD VB DT JJR NN .
DT NN , which PRP VBD JJ NN , VBZ RB JJ .
VB PRP VB , PRP MD VB PRP .
EX VBD JJ NNS when PRP VBD DT NN IN PRP .
PRP VBZ JJ CC JJ , CC RB NNS VBP PRP .
NNP NNP VBZ RB DT NN whom PRP VBP TO VB .
PRP MD VB VBN that PRP VBZ RB VB .
PRP VBZ NN , for DT NNS VBP VBG .
DT NN VBD that DT NN VBZ IN DT NN NN .
PRP MD RB VB VBN RB though PRP VBP CD NNS .
NNP MD VB DT JJ NN NN IN JJ NNS CC JJR NNS .
Whenever PRP VBZ , DT NN VBZ VBN .
PRP VBZ RB as though PRP VBD JJ .
DT NN , whose NNS VBZ RB JJ , VBZ JJ IN DT NN .
PRP MD VB VBG that PRP$ NNS VBP VBN .
While PRP VBP DT NN , PRP VBP RB VB DT NN .
PRP MD VB RB , RB PRP MD VB DT NN .
Though PRP VBZ JJ , PRP VBZ JJ .
NNPS MD VB PRP NN CC PRP MD RB RB VB PRP RB .
DT JJ NN that PRP VBD VBD VBN RP IN NN RB .
NNS VBD DT NN IN NN differently than PRP VBP NN .
PRP MD VB DT NN whose NNS VBZ RP IN DT NN .
PRP VBD VBG PRP$ NN when PRP VBD .
DT JJ NN DT VBZ NN CC JJ JJ NNS .
Where PRP VBP EX VBP RB IN NNS .
PRP VBZ RB VB DT NN whether PRP VBZ CC RB .
PRP VBD VB PRP$ NN that PRP MD VB JJ TO VB TO NN .
PRP VBD DT NN that PRP VBP DT NN .
PRP MD VB TO VB NNS VB DT NNS that PRP VBP IN PRP$ NNS .
PRP VBD NN that VBD PRP JJ .
PRP MD VB DT NN VBG that PRP MD VB PRP IN PRP$ JJ NN .
PRP VBD VBN VBN CC PRP VBD VBN .
PRP RB VBD RP DT JJ NNS that VBD TO VB VBN RB IN VBG .
PRP VBZ DT NN TO PRP how PRP DT VBD .
DT NN who MD VB PRP$ NN VBZ RB RB JJ .
VBG that_insert PRP VBP VBN DT NN , PRP MD RB VB VBN .
PRP VBD JJ DT NN , RB PRP MD VB VBN NN IN DT NNS VB .
DT NNP NNP CC JJ JJ NNS RB RB VBD RP NNS IN NN , CC NNP VBZ RB VBD .
DT VBZ DT NN where PRP VBD DT NN .
PRP VBD RB VB PRP when PRP MD VB RB .
PRP VBD what PRP VBD VBN TO VB JJ .
NNP VBZ PRP JJ .
What PRP VBP TO VB VBZ DT .
Whenever PRP VBP TO VB DT NN , PRP VBP RB JJ IN PRP VBP .
PRP$ NN VBZ which NN TO VB .
PRP VBP VBN , CC PRP MD VB RB .
PRP who VBZ JJ NNS RBS .
DT NN where PRP VBD CD NNS RB VBZ VBN VBN RP .
NN PRP MD VB RB DT NN which PRP VBD IN .
PRP VBP RB RB RB as PRP VBZ VBD RP .
After PRP VBD VBN DT NN , PRP VBD NN .
DT NN VBZ how PRP MD VB DT NNS PRP VBP .
PRP VBZ NN , for DT NNS VBP VBG .
PRP VBD DT NN where DT NN IN NNS VBD VBN .
PRP MD VB RB , CC PRP MD VB NNS IN NN .
NNP DT NN VBZ RB JJ , CC PRP VBP TO VB .
PRP VBD DT RBR VBN DT NN than PRP VBD VBN IN NN .
PRP VBD DT NN that PRP$ NN VBD VBN .
NNP NNP VBZ that_insert DT JJ NN IN DT NNP NNP NNP VBZ TO VB DT JJ NN IN NN VBG NNS IN DT NN .
NN PRP VBD DT NN which VBD IN NNP .
PRP VBD DT JJ NN , though DT NNS VBD VBN .
PRP MD VB JJ when PRP VBP JJ CC JJ .
DT JJR PRP VBP , DT JJR PRP VBP PRP$ NN .
IN PRP$ NN EX VBP CD NNS , DT JJS IN whom VBZ NNP NNP .
RB if PRP VBZ JJ , PRP VBZ PRP .
PRP VBP RB VB whom PRP MD VB RP .
PRP MD VB PRP when PRP VBP NN .
PRP VBD VBG DT NNS , CC PRP RB VBD RB IN NN .
PRP MD VB TO VB DT NN whether PRP VBP JJ CC JJ .
JJ NNS IN DT NN when PRP MD VB VBG DT NN IN DT NN .
PRP VBZ as if NN VBZ VBG IN DT NN .
VB as PRP VBD , PRP MD RB VB DT NN RB RB .
DT NN who PRP VBD VBZ VBN NNP .
