NNP VBZ RB RB RB IN PRP RB RB VBP PRP .
RB EX VBD RB JJ NNS IN PRP VBD RP PDT DT JJ NNS .
PRP VBZ JJ JJ NN IN PRP MD VB TO VB TO DT NN .
PRP VBD RB JJ IN PRP MD RB VB TO VB DT NN .
PRP VBD RB IN PRP MD RB VB .
PRP VBD RB VB IN PRP VBD JJ .
DT MD VB JJ IN DT NNP NN VBZ RB VBN TO VB VBN IN NN IN NNP .
IN PRP VBP DT NN , PRP MD RB VB PRP .
PRP MD RB VB VBN PRP , IN PRP VBD RB RB .
PRP VBD PRP IN PRP VBD JJ .
PRP MD VB RBR RB IN PRP MD VB VBN IN DT .
PRP VBZ JJ IN NN IN PRP$ NN MD VB JJ .
JJS NNS VBP TO NN RB IN PRP MD VB NNS , NNS CC NNS .
DT NN VBD PRP$ NN IN NN IN DT NNS IN DT NN MD VB JJR RB .
PRP VBD RP RB RB IN PRP MD VB DT JJ NN .
PRP RB JJ VBP CC RB PRP VBP NN .
PRP$ NN VBZ DT NN CC PRP$ NN VBZ DT NN .
PRP VBD VBN VBN CC PRP VBD VBN .
PRP RB VBD PRP$ NN , PRP MD CC VBP RB .
PRP RB JJ VBD PRP CC RB PRP VBD PRP .
PRP VBZ RB IN NN VBZ VBG IN DT NN .
NN VBD .
PRP VBP VBN TO VB JJ IN NNS , IN PRP RB VBZ TO DT JJ NNS .
DT NN , WP$ NNS VBZ DT NN , VBZ RB JJ .
IN PRP VBP JJ NN TO DT NN , PRP MD VB DT JJR NN .
PRP VBP RB VB NN CC PRP VBP NN .
RB PRP VBD RB IN PRP VBD VBN NNP IN NNS .
EX VBZ DT NN IN PRP VBZ VBN IN DT NN .
PRP VBD RB VBG DT NN WRB PRP VBD IN PRP$ NN .
PRP VBP TO VB RB RB , IN PRP VBP NNS IN NN TO VB .
PRP VBD DT NN TO PRP$ NN .
PRP VBD VBG PRP$ NN WRB PRP VBD .
DT VBZ DT NN WRB PRP VBD DT NN .
PRP VBP VBN DT NN IN JJ NNS IN PRP IN PRP VBD RB IN RB .
VB JJ IN PRP MD , PRP RB VBZ JJ TO VB DT NN RB .
DT NNS VBD VBG PRP$ JJ NN WRB DT NN VBD RP .
IN PRP VBD VBN , RB PRP VBD IN VBG .
NNP VBD PRP RB JJ WRB PRP VBD PRP$ NNS IN NNP NNP .
WRB EX VBZ DT NN , EX VBZ DT NN .
IN PRP VBD NN , WP VBD PRP VB .
PRP MD RB VB VBN RB IN PRP VBP CD NNS .
NNP VBZ NN WDT VBZ NN , RB VBN .
DT NN VBZ JJ , DT NN VBZ JJ CC DT NN VBZ JJ .
IN PRP VBZ JJ , PRP VBZ JJ .
PRP VBD RBR JJ IN PRP VBD JJ NN .
MD PRP RB VB RB CC VB PRP VBP VBN RP .
VB PRP WRB PRP MD VB PRP .
PRP$ NN VBZ WDT NN TO VB .
PRP VBZ JJ .
PRP MD VB RP DT NN IN JJ NN , WRB PRP MD RB VB RB JJ .
PRP VBD RB RB IN VBG DT NN .
PRP$ NN RB VBD RP IN DT JJ JJ NNS , IN WRB PRP MD VB NN CC NNS .
IN PRP VBZ RB JJ , RB PRP VBZ RB JJ .
IN PRP$ NN VBD VBG DT NN , PRP VBD VBG NN .
PRP VBZ JJ TO VB PRP$ NN WRB PRP VBD PRP .
PRP VBP NN IN PRP VBZ NN .
WRB RB VBN IN NN , WDT PRP RB VBD , PRP MD VB DT IN VBG CC VBG .
NNP , WDT VBZ IN DT NN , VBZ , RB , JJ IN JJ JJ NN .
WDT PRP VBD VBZ JJ .
PRP VBP NN IN DT NN IN DT NNPS , CC IN DT NN PRP VBZ JJR .
PRP VBD DT JJ NN WDT VBD RB .
PRP VBP DT NN WP$ NN VBZ JJ .
PRP MD VB PRP NN CC FW MD RB VB PRP .
DT NNS NN VBZ DT NN WDT PRP MD RB VB RP .
PRP VBZ CD IN DT NNS WDT VBP RB JJ .
RB IN PRP VBZ JJ , PRP VBZ PRP .
PRP VBD RP IN PRP MD VB CC VB DT NN .
NN VBD IN PRP MD VB DT NN .
JJ NN VBZ JJR NN CC JJR NNS : RB PRP VBZ PRP$ NN TO VB PRP .
IN NNP VB PRP$ NN PRP VBP VBG TO VB DT NN .
EX VBZ DT JJ NN WDT VBZ NN TO DT NN .
PRP VBD PRP IN PRP VBD VBN PDT DT NN PRP CC IN PRP VBD VBN DT NN .
PRP MD VB PRP VB .
DT NN VBZ RB RB JJ IN PRP VBD JJ .
DT NN WRB JJ PRP VBP VBN , PRP MD RB VB DT NN .
DT NN , WP VBD VBN RB IN RB CD NNS , VBD TO VB PRP$ NNS .
DT MD VB DT VBG NN IN DT NN , WP RB VBZ CD JJR NNS IN DT NN .
DT NN WRB PRP VBD CD NNS RB VBZ VBN VBN RP .
PRP MD VB RB IN DT NN VBZ .
IN PRP VBZ JJ , PRP VBZ JJ NN .
DT NN WP PRP VBD VBZ VBN NNP .
DT VBZ RB JJ DT NN IN PRP MD VB IN .
DT NN VBD TO PRP IN RB DT NN VBD VBN DT NN .
NNP VBD RBR IN NNS VBP .
PRP VBD RB JJ IN DT NNS , WDT PRP$ NN RB VBD .
IN PRP MD VB PRP VBD DT NN .
WRB DT VBD VBZ RB JJ TO NN .
WRB PRP MD VB VBZ RB VBN VBN JJ .
NNS WP VBP IN DT NN VBP JJ TO DT NN .
DT VBZ DT NN WRB DT NN VBZ JJ IN NNS .
DT NN VBZ IN PRP VBP VBN PRP$ NN .
DT NNS RB VBP IN DT NN , WDT VBZ RB JJ TO NNS .
PRP VBZ RB IN PRP VBD VBN VBN IN NN .
PRP VBD PRP DT NN IN PRP MD RB VB JJ NN .
PRP MD VB VBN IN PRP VBZ RB VB .
PRP VBP PRP JJR IN DT NN MD VB PRP .
PRP VBP VBN IN NNP IN PRP VBD .
PRP VBP DT NN WRB PRP VBD RB , RB IN NN .
PRP$ NN VBZ IN PRP MD VB JJ NN .
PRP VBZ DT JJ NN IN PRP VBD TO VB .
DT NN IN DT JJ NN VB VBN VBD DT NN .
PRP VBD IN PRP MD VB RP TO DT NNP RB .
NNP VBZ JJ CC PRP VBZ RB JJ TO VB NNS .
PRP VBP PRP RB JJ IN PRP VBZ RP VBG RB DT NN .
PRP VBD PRP MD VB DT NN DT NN .
PRP VBP VBN PRP DT NN IN PRP VBP NNS .
NNP VBD JJ IN DT NNS WDT DT NN VBD .
PRP VBP RB VB IN CC RB PRP MD VB .
PRP VBZ RB IN PRP VBD VBN VBN IN NN .
PRP MD VB TO VB NNS VB DT NNS IN PRP VBP IN PRP$ NNS .
RB PRP VBD , PRP VBD RB VBN .
DT NN VBZ WRB NNP NNP RB VBD .
PRP MD VB WRB PRP VBP JJ .
PRP DT VBP IN PRP MD VB , IN NNS IN PRP$ NN VBP JJR .
JJ NNS VBG IN CD MD VB CD JJ NNS , CC RB RB CD VBP JJ IN NN .
DT NN WP MD VB PRP$ NN VBZ RB RB JJ .
PRP MD VB PRP WRB PRP VBP NN .
IN PRP VBZ VBG CC RB VBZ RB VB RB RB .
PRP VBZ DT JJ NN IN JJ NNS TO VB , CC PRP VBZ RB JJ JJ NN NN .
PRP VBP PRP DT NN IN PRP VBP RB VBN TO DT NN .
PRP VBP JJ IN PRP VBP VBN PRP RB JJ .
PRP VBP PRP RB JJ IN PRP VBP .
DT NN WDT NN PRP VBP , PRP MD VB PRP IN DT NN .
PRP VBZ NN , IN DT NNS VBP VBG .
PRP$ NN VBD IN NNP VBZ DT JJ NN IN DT NN .
VB PRP VB , PRP MD VB PRP .
PRP VBP DT NN , WP VBZ VBG DT NN .
PRP MD VB DT NN IN PRP VBZ TO PRP CC RB .
DT NN IN PRP VBD VBN DT NN RB VBN IN DT JJ NN .
PRP VBD PRP WRB PRP MD VB CC VB .
PRP VBP DT NN WP VBP NNS PRP VBZ .
NNP NNP VBD DT NN WP VBD JJ IN VBG IN NNPS .
PRP VBZ DT JJ NN IN PRP VBD NN NN .
PRP VBP RB VB PRP VBZ DT JJ NN .
PRP MD VB TO VB PRP$ NNS CC PRP$ NN WRB PRP VBP DT NN .
NNP VBZ RB VBG IN JJ NNS TO VB DT NN VBN TO VB NNS TO NNP .
PRP VBD RB VB PRP WRB PRP MD VB RB .
DT JJS NN IN PRP VBP JJ IN VBD IN DT NN .
PRP VBZ VBN IN NN , IN PRP RB VBD .
PRP VBD PRP JJ IN PRP MD VB PRP IN PDT DT JJ NN .
WRB EX VBZ JJ EX VBZ JJ TO VB NN .
DT NN VBZ RB IN DT NN , CC RB VBZ IN NN .
PRP VBZ VBN WRB PRP VBD NN IN DT NN .
PRP VBZ JJR IN PRP$ NN IN PRP VBZ IN PRP$ NN .
PRP VBD PRP IN NNP VBD RB VB NN WRB PRP VBD .
IN PRP VBD VBN RP , PRP VBD IN VBG .
PRP MD VB IN NNP IN PRP VBP JJ .
PRP MD VB RP DT NN IN NNP , WRB PRP MD VB JJ .
NNP NNP , IN WP PRP VBP VBN DT NN , VBZ DT JJ NN .
DT NN WP VBD , PRP MD RB VB .
VBG IN PRP VBZ , PRP VBZ JJ NN .
PRP VBZ DT NN IN NNP MD VB VBN DT NN .
PRP VBP DT NN TO VB PRP$ NN , IN NNS MD VB JJ DT IN DT NN CC IN NNP .
RB IN PRP VBZ PRP$ NNS , RB PRP MD VB RB NNS IN PRP$ NNS .
DT NN VBZ IN PRP VBZ RB RB VB .
EX VBP CD NNS IN DT JJ NN , JJS IN WDT VBP JJ .
NNS VBD DT NN IN NN RB IN PRP VBP NN .
JJ NNS IN DT NN WRB PRP MD VB VBG DT NN IN DT NN .
WRB PRP MD VB VBZ RB VBN .
PRP MD RB VB IN CC RB NN MD VB IN NN .
NNS , WP$ JJ NN VBZ JJ , MD VB CC VB IN JJ JJ NNS .
NNP VBZ DT RBS JJ JJ NN IN PRP VBP RB VBN RP .
PRP VBZ VBN IN NNP NNP VBZ VBN IN NNP .
DT CD NNS VBD JJ IN DT NN , IN VBD VBN RB .
PRP VBP VBN NN , IN EX VBZ DT NN NN .
NNP NNP , WP NN VBZ RB JJ , VBZ CD IN DT JJS NNS IN PRP$ NN .
DT JJ NN IN PRP VBD VBD VBN RP IN NN RB .
WRB EX VBZ DT NN , EX VBZ DT NN .
PRP VBD VB PRP$ NN IN PRP MD VB JJ TO VB TO NN .
NNP VBD RB JJ WRB PRP VBD NN IN PRP$ NN TO VB NNP .
PRP VBZ RB VBN RB , IN DT VBZ DT NN IN JJ NN VBG .
RB RB PRP VBZ CD TO CD NNS TO VB DT NN NN NNS , CC DT VBZ DT RB JJ .
PRP VB RP , CC RB PRP MD VB JJ .
WDT VBD , PRP MD RB VB .
PRP VBP PRP JJ IN PRP VBD DT NN TO NN .
PRP VBZ VBN WP PRP VBD TO VB CD NNS RB .
DT NN VBZ VBN DT NN IN PRP$ JJ JJ NN NN .
DT NN MD VB PRP WP DT JJS NNS VBP .
NNP NNP VBZ VBN DT NN WRB DT NN VBD RB IN NN .
PRP VBZ RBR IN PRP VBZ JJ IN PRP .
WRB DT NN VBD , NNS VBD VBN VBN .
NNP NNP VBZ DT JJ NN NN VBZ VBG .
PRP VBD DT NN , WDT VBD PRP .
PRP MD VB RB , CC PRP MD VB NNS IN NN .
DT VBZ DT NN WRB PRP RB VBZ PRP .
PRP VBD NN CC NN , RB , PRP VBD JJ TO VB DT NNS NN .
DT VBD DT NN WRB PRP VBD TO VB IN DT NN .
PRP VBZ RB DT JJ NN IN PRP VBD .
WRB PRP MD VB VBZ DT NN .
DT NN VBZ WP PRP MD VB TO VB PRP .
DT NN WP PRP VBP , PRP MD VB DT NN .
PRP VBD PRP TO VB , IN PRP VBP .
PRP VBD PRP IN PRP MD VB TO DT NN DT JJ NN .
PRP VBP JJ NN NNS IN PRP RB VB PRP IN JJ NN .
PRP VBP DT NN , WP VBZ DT JJ NN .
WRB PRP MD VB PRP VBZ DT NN .
NNPS MD VB PRP NN CC PRP MD RB RB VB PRP RB .
PRP VBZ NN RB , RB DT NN MD VB JJR .
PRP VBZ RB VBN DT NN IN PRP MD VB RB .
PRP VBD RB VBN RB WRB PRP VBD DT JJ NN IN PRP$ NN .
