DT NN VBZ RB JJ IN PRP MD RB VB PRP .
RB EX VBD RB JJ NNS IN PRP VBD RP PDT DT JJ NNS .
PRP VBD RB IN PRP MD RB VB .
PRP VBZ RB JJ NN IN PRP MD RB VB TO DT NN IN PRP .
PRP VBZ JJ JJ NN IN PRP MD VB TO VB TO DT NN .
IN PRP VBP DT NN , PRP MD RB VB PRP .
RB IN PRP VBP RB RB , PRP MD VB .
PRP VBD IN NN IN PRP VBD JJR .
IN PDT DT NNS VBD JJ , PRP VBD RP .
PRP VBD RB VB IN PRP VBD JJ .
PRP VBP VBG DT NN IN PRP MD VB DT JJ NN .
PRP VBD DT NN RB IN NN IN PRP MD VB PRP .
PRP VBP DT NN IN PRP MD VB PRP .
PRP VBZ JJ IN NN IN PRP$ NN MD VB JJ .
NN VBP DT NN , RB IN DT NN VBD VBN IN NN .
PRP RB JJ VBZ PRP$ JJ NNS , PRP RB VBZ IN PRP .
DT VBZ PRP VBD PRP$ NN , CC MD PRP VB RB .
RB RB PRP VBZ DT JJ NN CC PRP VBP VBG PRP$ NN IN DT NN .
DT VBD DT JJ NN VBP NN CC VBD PRP$ NN NN IN PRP .
RB RB PRP VBZ DT JJ NN CC PRP VBP VBG PRP$ NN IN DT NN .
PRP MD VB RB JJ IN PRP VBZ PRP VB IN DT NN .
DT NN WRB PRP VBZ , DT NN VBZ VBN .
IN PRP MD VB NNS VBZ DT NN .
PRP VBP VBN TO VB JJ IN NNS , IN PRP RB VBZ TO DT JJ NNS .
PRP VBD DT NN , IN PRP VBD RB JJ .
PRP$ NN VBZ IN PRP MD VB PRP .
DT VBZ WP PRP VBP RB IN .
WRB EX VBZ JJ EX VBZ JJ TO VB NN .
DT NN IN DT JJ NN VB VBN VBD DT NN .
DT NN WP VBD VBD DT NN IN NNP .
DT JJ NN VBZ DT NN , WP VBZ IN DT NN .
DT NN VBZ WP PRP MD VB TO VB PRP .
PRP VBZ RBR IN PRP$ NN VBZ .
PRP VBZ RB IN DT VBZ WP PRP VBP , IN PRP VBD VBG RB IN RB .
PRP MD RB VB JJ RB IN DT NNS VBP JJ IN PRP .
PRP VBZ TO VB IN NNP , WDT PRP VBZ RB VB .
DT NN VBZ RB JJ , WDT VBD PRP RB JJ .
PRP VBZ JJ IN PRP MD VB RB IN DT NNP .
DT NNS VBD RP DT JJ NN WRB PRP VBD RP CC VBD .
DT NN VBZ WRB PRP MD VB DT NN NN .
PRP$ NN VBZ WDT NN TO VB .
DT NN VBZ IN DT NNS WRB NNS VBD NNS .
PRP VBZ JJ .
IN PRP VB PRP$ NN IN DT JJ NN , DT NN NN MD RB VB PRP .
PRP RB VBD IN DT NN WP$ NNS VBZ VBN IN .
IN PRP VBD PRP , PRP MD VB PRP TO DT NN .
PRP VBP NN IN DT NN IN DT NNPS , CC IN DT NN PRP VBZ JJR .
PRP MD VB RB VBG DT NN VBZ IN PRP .
VBG IN PRP VBZ , PRP VBP DT NN .
NNP VBZ RB RB WP PRP VBD TO VB .
DT JJ NN IN PRP VBP TO VB RB VBZ TO VB DT NN .
PRP MD RB VB NNS IN DT NN NN IN PRP VBP PRP$ NN NN .
PRP VBP DT NN WP$ NN VBZ JJ .
IN PRP MD RB VB TO DT NN DT NN VBZ JJ .
NNP MD VB DT JJ NN NN IN JJ NNS CC JJR NNS .
DT NNS WP VBD IN NNP IN DT CD NNS VBD NNP NNP VBD DT IN PRP$ NN IN NNP .
WDT NN MD VB VBZ RB JJ .
PRP MD RBR VB RB , RB PRP MD VB DT NN .
PRP$ NN VBD PRP DT NN WRB PRP MD VB DT NN .
PRP VBZ DT JJ NN IN PRP VBD TO VB .
DT NN MD VB JJ CC PRP MD VB JJ .
DT NN VBZ IN PRP VBP JJ IN NNS .
DT WP VBP TO VB TO DT NN MD VB IN DT NN NN IN CD NN NN .
PRP VBD TO NN IN CD , IN WRB PRP VBD VBG IN DT NN .
NNP NNP VBZ RB DT NN WP PRP VBP TO VB .
PRP VBZ DT JJ NN IN PRP VBP .
DT VBZ DT JJ NN WDT VBD IN NN DT NN IN RB .
PRP MD VB IN NNP IN PRP VBP JJ .
NNS WP VBP IN DT NN VBP JJ TO DT NN .
NNP , WDT VBZ DT JJ JJ , VBZ JJ NNS .
WP VBD DT NN VBZ DT NN .
DT NN VBZ RB JJ IN PRP VBD RB JJ .
NN VBD .
NNP CC JJ NN VBZ WP PRP VBP IN .
DT NN WP PRP VBP VBG IN VBZ VBN .
PRP VBP TO VB RB RB , IN PRP VBP NNS IN NN TO VB .
DT NN VBZ IN PRP MD VB JJ TO VB PRP .
RB VBZ DT NN IN PRP VBD VBN PRP IN .
DT NN VBZ RB IN DT NN , CC RB VBZ IN NN .
PRP VBZ JJR IN PRP$ NN IN PRP VBZ IN PRP$ NN .
PRP VBD TO NN IN PRP VBD PRP$ NN .
WP MD PRP VB IN PRP VBP DT NN IN NN .
PRP VBP IN PRP MD VB JJ IN NN .
PRP MD VB RB IN PRP MD RB VB DT NN .
NNP VBP TO DT NNS IN PRP MD VB VBN IN .
PRP VBP VBN RB JJR NN DT NN IN PRP VBD DT NN .
PRP VBP JJ IN PRP MD VB PRP .
NNP IN PRP VBZ , PRP VBZ JJ NN .
PRP$ NN VBZ IN PRP MD VB JJ NN .
IN NNP VBD VBG PRP$ NN , NNP NNP VBD TO VB PRP .
DT NN WRB PRP VBD VBN VBZ JJ TO PRP .
WDT PRP VBD VBZ JJ .
DT NN IN DT NN IN DT NN NN MD VB IN NN VBZ RB VBN .
PRP MD VB PRP$ NNS TO VB DT NNS .
DT VBZ WRB PRP VBP JJ .
WRB DT VBD VBZ RB JJ TO NN .
CD NNS VBD RB JJ IN NNP IN JJ NNS , CC PRP VBD JJ IN DT NNP .
DT NN NNS , WDT PRP VBD CD NNS RB , VBP RB VBN DT NN .
IN NN VBZ TO NN , RB NN VBZ TO NN .
PRP VBD DT NN WRB DT NN IN NNS VBD VBN .
RB IN PRP VBZ PRP$ NNS , RB PRP MD VB RB NNS IN PRP$ NNS .
PRP VBP JJ .
WP PRP VBP VBZ JJR NN .
EX VBZ DT NN WP VBZ TO VB PRP .
PRP VBD RB VB TO NN IN PRP$ NN VBD RB .
RB IN PRP VBZ JJ , PRP VBZ PRP .
DT NNPS , WDT VBZ RB JJ RB TO VB RP , VBD JJ IN IN DT CD NNS .
DT NN WP VBD , PRP MD RB VB .
DT NNS VBP RBR WRB NNP VBZ .
IN PRP VBP NN IN DT , PRP MD RB VB TO VB PRP .
IN PRP VBZ JJ , PRP RB VBZ .
PRP VBZ JJ NN IN DT NN VBZ RB DT NN .
PRP VBD IN PRP MD VB TO DT NN DT JJ NN .
RB PRP VBD , PRP VBD RB VBN .
PRP VBZ DT JJ NN IN DT NNS WDT VBZ VBN TO VB .
IN DT NN MD VB VBN RP VBZ RB VBN VBN RB .
VB RB CC RB PRP MD VB DT JJ NN .
IN VBZ VBN TO DT NNP , NNP NNP VBZ DT JJ JJ NN .
VBG EX VBZ DT NN , PRP MD VB DT NN RB .
IN NNP VB PRP$ NN PRP VBP VBG TO VB DT NN .
NNP NNP , IN WP PRP VBP VBN DT NN , VBZ DT JJ NN .
PRP VBD IN TO VB RB .
WRB PRP MD VB NN MD VB VBN RB .
PRP MD VB DT NN IN PRP VBZ TO PRP CC RB .
PRP VBD PRP WRB PRP MD VB CC VB .
DT NN WRB PRP VBD RB VB DT NN VBD IN PRP$ NNP VBD RB RB JJ .
IN DT NN PRP VBD RB , PRP VBD VBN DT NN .
PRP VBZ RB VBN RB , IN DT VBZ DT NN IN JJ NN VBG .
PRP MD VB RB , RB PRP MD RB VB DT NN .
PRP VBD DT JJ NN , IN DT NNS VBD VBN .
PRP VBD VBN IN DT JJ NN , WRB EX VBD DT VBG NN .
DT VBZ WRB PRP VBP TO DT NN .
DT NN WP$ NN PRP VBP RP VBZ JJ NN TO VBG PRP$ VBG NNS .
PRP VBP JJ NN NNS IN PRP RB VB PRP IN JJ NN .
DT NN WDT NN PRP VBP , PRP MD VB PRP IN DT NN .
PRP MD VB PRP NN CC FW MD RB VB PRP .
DT VBZ WP PRP VBP .
PRP VBP DT NN TO VB PRP$ NN , IN NNS MD VB JJ DT IN DT NN CC IN NNP .
IN PRP VBD VBN RP , RB PRP VBD IN VBG .
DT VBZ WRB PRP VBD RB VB .
DT NN IN PRP MD VB RB JJ NN VBZ TO VB VBN .
IN PRP VB PRP CC RB , PRP VBZ JJ .
IN PRP MD VB DT NN VBZ JJ .
IN PRP VBD VBN DT NN , PRP VBD NN .
DT NN VBZ IN DT NN VBZ VBG IN PRP .
NNP VBD PRP RB JJ WRB PRP VBD PRP$ NNS IN NNP NNP .
PRP VBD VBG IN DT WRB PRP VBD PRP$ NN VBD .
PRP VBZ RB IN NN VBZ VBG IN DT NN .
PRP VBZ NN IN NN IN DT NN NN , IN DT NN PRP VBP IN NN IN NN .
PRP VBZ RB JJR TO VB NNS WRB PRP VBP JJ NNS .
PRP VBZ RB IN PRP VBD DT NN .
DT JJR DT NN VBZ , DT JJR DT NN VBZ .
NNS VBZ JJ TO VB IN PRP VBP DT NNS .
IN PRP VBD VBN RP , RB PRP VBD IN VBG .
PRP$ NN VBZ IN PRP MD VB PRP DT NN IN RB .
VB PRP WRB PRP MD VB PRP .
VB PRP$ NN IN PRP VBP VBG .
DT NN VBZ WP MD VB DT NN .
WRB PRP VBZ , DT NN VBZ VBN .
VBN IN PRP VBP VBN DT NN , PRP MD RB VB VBN .
PRP VBP JJ , IN PRP VBZ JJ .
VB PRP PRP$ NN IN PRP MD VB TO PRP$ NN DT NN .
PRP VBP RBR IN PRP VBP JJ IN PRP .
PRP$ NN , WP VBZ PRP RB JJ , VBZ JJ IN PRP .
IN PRP VBP IN DT NN , PRP MD VB PRP RP .
VB RP WRB PRP VBD IN .
PRP RB VBD RP DT JJS NN , WDT RB VBD CD NNS .
IN PRP VBD VBN , RB PRP VBD IN VBG .
DT JJ NN VBD IN DT JJ NNS WRB PRP RB VBD PRP .
DT NN IN PRP MD VB IN DT NN VBD VBN IN JJ NN .
NN PRP VBD DT JJ NN WP VBD VBN PRP$ NN .
PRP VBP PRP JJR IN DT NN MD VB PRP .
PRP VBZ JJ IN PRP MD VB RB IN PRP$ NN .
PRP VBP VBN IN NNP VBG IN DT NN IN PRP MD RB VB JJ TO VB PRP DT NN .
DT NN IN PRP VBD TO PRP VBZ RB JJ .
DT NN WP PRP VBP , PRP MD RB VB PRP .
PRP VBD TO VB PRP$ NN IN PRP , IN VBD RB DT NN .
PRP VBZ RB VB IN PRP MD VB CC RB .
IN PRP VBZ JJ , PRP VBZ JJ NN .
VB IN DT NNS IN NNS WRB PRP VBZ JJ .
PRP MD RB VB VBN RB IN PRP VBP CD NNS .
PRP VBP PRP DT JJR , DT JJR PRP VBP PRP .
PRP MD VB PRP VB .
PRP MD VB RB , IN PRP$ NN VBZ VBG IN PRP .
DT NN VBD VBN IN DT NNP PRP , WP VBD DT JJ NN IN NNP NNP .
IN PRP VBP PRP , PRP MD VB PRP .
DT NN WDT VBZ IN NNP VBZ NN .
RB VBD DT NN MD VB , DT JJ MD RB VB JJR CC JJR .
NNS IN NN VBP VBN JJ NNS IN VBG NN IN DT NN .
WDT PRP VBP , PRP MD RB VB PRP .
PRP VBD IN PRP VBD RB VB TO NN NN .
PRP VBZ DT NN IN NNP MD VB VBN DT NN .
PRP VBD RB VBG DT NN WRB PRP VBD IN PRP$ NN .
PRP VBD RB VBD PRP$ NN WRB DT NN VBD IN PRP .
VBZ PRP DT NN WDT VBZ NNS .
PRP VBZ VBG WRB MD PRP VB DT JJ NN .
RBS JJ JJ JJ NNS RB VBP IN NNS IN PRP$ NN , IN DT NN IN DT NN VBZ JJ NNS IN JJ NN .
IN NN VBZ JJ , PRP VBZ NN .
VB IN PRP MD , PRP MD VB .
NNP VBD JJ , IN PRP VBD RB VB TO NN .
