PRP VBD DT LogN why PRP DObj .
PRP VBZ VBN DT LogN why DT NN VBD RB IN LogN .
PRP VBZ RB DObj DT LogN whether PRP MD VB RB .
PRP DObj DT LogN that DT NN VB VBN .
PRP DObj VB PRP$ LogN that PRP MD VB JJ TO VB TO NN .
PRP VBD TO NNP POS LogN that DT NN NNS VBP DT NN .
PRP DObj PRP DT LogN that PRP MD RB VB JJ NN .
PRP VBP VBN TO DT LogN that PRP VBD JJ TO VB DT .
PRP MD VB PRP$ LogN that PRP MD VB DT JJ NN .
PRP VBD DT LogN that PRP VBD RB .
PRP VBP DObj DT LogN that NNP VBD VBN DT NN .
PRP VBP DT LogN what VBP NNS PRP VBZ .
PRP VBP DT LogN when PRP MD VB RB .
PRP VBP DT LogN when PRP MD VB RB .
PRP VBP DT LogN how PRP VBD RB , RB IN NN .
PRP VBD DT LogN that PRP$ NN VBD VBN .
PRP VBZ JJ TO VB PRP$ LogN how PRP VBD it .
PRP$ LogN how PRP MD DObj IN NN IN PRP VBZ RB VBN VBN .
RB VBD DT LogN that PDT DT NNS MD VB DT NNS .
DT LogN that PRP VBD RB VBD NN VBN NN .
DT LogN that DT NN VBZ VBN VBZ RB VB it VBD DObj .
DT NN VBD DT LogN that DT NNS MD VB DT NN IN RB .
DT LogN that PRP MD VB DT NN RB IN VBG VBZ RB JJ .
DT LogN that PRP VBD VBN DT NN RB VBN IN DT JJ NN .
DT LogN that PRP MD DObj DT JJ NNS TO VB DT JJ NNS VBD VBN NN .
DT LogN who MD VB DT NN VBZ NN .
DT LogN who MD DObj PRP$ NN VBZ RB RB JJ .
DT LogN VBD TO PRP that RB DT NN VBD VBN DT NN .
EX VBZ DT LogN that PRP VBZ VBN IN DT NN .
EX VBD DT LogN that NNP MD VB VBN IN DT NN .
PRP VBP JJ IN DT LogN that DT NN VBZ IN NNS .
PRP VBD DT LogN that PRP VBP DT DObj .
PRP VBD VBN IN DT LogN that DT NN VB VBN .
PRP VBD VBN IN DT LogN that PRP VBD JJ .
PRP MD VB DT LogN whether DT NNS NN MD VB VBN IN NN .
PRP DT VB RP when PRP VBD DT LogN IN PRP$ NN VBD DT JJ NN .
PRP VBP RB VBG DT LogN whether PRP VBZ JJ .
PRP VBP RB VBG IN DT LogN whether PRP VBZ IN JJ .
PRP VBP RB VB DT LogN why DT VBZ DT JJS NN .
PRP VBP RB RB VBN DT LogN where PRP VBP VBG TO VB PRP$ JJ NN .
LogN VBD that PRP VBD VBN RB .
NNP VBZ VBN DT LogN why DT NN VBD RB IN LogN .
DT JJ NN DT DObj NN CC JJ JJ NNS .
PDT DT NNS that PRP$ NNS VBP PRP IN PRP$ NN MD VB VBN RP .
IN DT JJ NN PRP DObj RB JJ NN as PRP MD DObj .
NNP VBZ DT NN which VBZ VBN IN JJS NNS .
NNP VBZ NN which VBZ NN , RB SOLOCCS .
NNP , which VBZ IN DT NN , VBZ , RB , JJ IN JJ JJ NN .
PRP VBZ RB DT NN IN NN who MD VB RP IN PRP$ LogN .
PRP VBZ DT NN NN that PRP VBP RB VBD TO .
PRP VBZ DT NN whose NNS VBZ DT NN .
PRP VBZ DT JJ NN whose NNS VBP RB IN JJ .
PRP VBZ RB DT JJ NN as PRP VBD .
PRP VBZ DT JJ NN IN PRP that VBZ JJ .
PRP VBZ TO DObj DObj which VBP DObj IN JJ NNS .
PRP VBD DT NN IN whom PRP VBD CD NNS .
PRP RB VBD RP DT JJ NNS that VBD TO VB VBN RB IN VBG .
PRP VBD NN that DObj PRP JJ .
PRP VBD DT JJ NN that MD VB RP DT NNS .
PRP VBD VBG DT NNS CC NNS that VBD DT NN .
PRP who VBZ JJ NNS RBS .
PRP$ NN TO PRP VBD RB DT JJ as PRP VBD RB VBN .
PRP MD VB DT NN whose NNS VBZ RP IN DT NN .
PRP VBP RB VBN IN NN which MD VB IN NN TO PRP .
PRP VBP DT NN TO which PRP VBZ .
PRP VBP RB VB DT NN why PRP VBZ JJ NN .
PRP VBP JJ IN JJ NNS who VBP PRP$ NNS IN DT NN IN NN .
PRP VBD PRP JJ NNS which PRP DObj DT NN IN .
PRP VBP RB VBN PDT DT NN as PRP VBD RP .
PRP VBP DT NN that PRP MD DObj .
PRP VBP DT NNS that PRP MD VB NN .
PRP VBP DT NNS that VBP VBN IN NN NN .
PRP RB VBD JJ NNS as PRP DObj .
PRP VBP DT TIME when PRP VBD IN DT NN IN PRP$ NNS .
PRP RB VBP DT TIME when PRP RB VBD TO DT NN .
PRP VBD DT NN whose NN VBZ VBN DT IN DT NN .
PRP VBD RP IN NN IN DT NN where PRP MD DObj DT NN .
PRP MD RB VB DT CD NNS that PRP VBD IN DT JJ JJ NN .
If PRP VBP RB IN DT NN , PRP MD RB DObj RP DT NN IN WDT PRP DObj RB .
VBZ PRP DT NN that DObj NNS .
PRP VBZ IN DT NN that PRP RB VBD .
PRP VBZ DT JJ NN that PRP VBD NN NN .
PRP VBD DT JJS NN that PRP RB VBD .
JJ NNS IN DT TIME when PRP MD VB VBG DT NN IN DT NN .
NNP VBD JJ IN DT NNS which DT NN VBD .
NNP NNP VBZ DT NN whom PRP VBD RP IN DT NN .
NNP NNP VBD DT NN who DObj JJ IN VBG IN NNPS .
NN VBZ VBG TO DObj DT NN whose JJ NN VBZ IN DT NN NNS .
RB RB IN NNP VBD DT JJ NN which VBD IN DT NNP .
NNP VBZ NN that PRP RB VBP VBG .
NNP VBZ DT RBS JJ JJ NN that PRP VBP RB VBN RP .
VBG TO DT PLACE where PRP VBD TO VB MD VB DT VBG NN .
VB RP RB DT LogN which PRP VBP RB LogN NNP TO DObj .
PRP VBZ CD IN DT NNS that VBP RB JJ .
PRP VBD DT JJ NN that VBD RB .
DT VBZ DT NN whom PRP DObj .
DT VBZ DT NN how PRP VBP NNP .
DT VBZ DT NN why PRP MD VB SOLOR .
DT VBD DT NN why PRP DObj TO VB IN DT NN .
DT NN CC PRP$ NN that VBD VBN IN DT JJ NN VBD DObj TO DT NN NN .
DT NNS who VBP VBG NN VBP IN NNP CD .
DT NN whose NN VBZ VBN MD RB VB VBN .
DT NN that PRP VBD VBG IN VBD JJ .
DT NN which DObj NNS VBZ RB RB IN RB .
DT NN which PRP VBD TO VB JJ NN VBD RB JJ IN DT .
DT NN whom DT NN RB VBZ VBZ PRP$ NN .
DT NN IN whom PRP VBD VBN VBG IN CD NNS RB VBD PRP$ NNS CC DObj .
DT PLACE where PRP VBD CD NNS RB VBZ VBN VBN RP .
DT NN , which PRP VBP RB , VBD RB JJ .
DT NN that PRP VBD IN PRP NN VBZ RB JJ .
DT NN who PRP VBD VBZ VBN NNP .
DT NN who VBZ VBG DObj IN PRP$ NN VBZ DT NN .
DT NN whom PRP DObj DT NN TO VBZ DT NN IN NNS .
DT NN whom PRP VBD RB SOLOR VBZ PRP$ JJ NN .
DT NN IN NNS that VBP TO VB DT NN DT NN VBZ CD CD .
DT NN , who VBD VBN RB IN RB CD NNS , VBD TO VB PRP$ NNS .
DT NN whom PRP LogN TO VB VBZ VBN .
DT DObj , whose NNS VBZ RB JJ , VBZ JJ IN DT NN .
DT NN VBP VBN IN DT DT NN NNS whom PRP VBP .
DT NN why PRP VBZ JJ VBZ IN PRP$ NN VBD JJ .
DT NN whose NNS VBZ RB VBZ NN .
DT NN which PRP RB VBD RP VBZ RB JJ .
DT NN which PRP VBD DObj IN VBD RB JJ .
DT NNS NN VBZ DT NN which PRP MD RB VB RP .
DT JJ NN that PRP VBD VBD VBN RP IN NN RB .
DT TIME when PRP DObj RB RB VBD .
DT CD NNS VBD JJ IN DT LogN , as VBD VBN RB .
DT NNS RB VBP IN DT NN , which VBZ RB JJ TO NNS .
DT JJS NN that PRP VBP JJ IN VBD IN DT NN .
EX VBZ DT JJ NN which VBZ NN TO DT NN .
EX VBZ DT NN that PRP MD VB .
EX VBD JJ TIME when PRP VBD DT LogN IN PRP .
PRP VBD RP PDT DT NNS that VBD JJ IN DT JJ NN .
DT MD VB DT VBG NN IN DT NN , who RB VBZ CD JJR NNS IN DT NN .
DT VBZ CD IN DT JJ NNS why DT IN PRP$ NN MD RB VB VBN RB .
DT VBZ DT NN whom PRP DObj NN IN RB .
DT VBZ DT TIME when DT NN VBZ JJ IN NNS .
DT VBZ DT NN which PRP DObj NN .
DT VBZ DT PLACE where PRP VBD DT NN .
DT VBZ DT NN , IN which DT NNS VBP VBN .
DT VBZ DT NN which VBZ VBN IN DT NN IN NNS .
DT VBZ DT JJ DObj that PRP VBP VBN VBG IN .
DT VBZ DT NN how PRP RB VBZ PRP .
DT who VBD VBN IN DT NNS RB DObj VBD .
NNP VBD DT TIME when DT NNS POS NNP IN NNP VBD VBN .
NN PRP MD DObj RB DT NN which PRP DObj IN .
NNP IN PRP$ JJ VBN NN , which MD VB IN DT NN JJ NN .
NNP VBZ DT JJ NN IN which JJS NN VBP .
PRP MD VB TO VB DT JJ NN whom PRP VBP RB VBN IN .
PRP VBP VBN IN DT NN which MD DObj DT NN JJ CD NNS DT NN .
PRP MD RB VB NNS IN DT NN , CC DT VBZ RB NN that MD VB VBN IN .
PRP VBD IN DT NNS CC NNS that PRP VBD IN NN .
PRP MD VB TO VB NNS VB DT NNS that PRP VBP IN PRP$ NNS .
WDT IN DT DObj that PRP DObj NN VBD DObj IN NNP .
MD PRP VB VB DT JJ NNS that PRP DObj .
NN PRP VBD DT NN which VBD IN NNP .
PRP DObj PRP DT NN why PRP VBD DT NN .
PRP MD DObj DT NN SOLOC that PRP MD VB it IN PRP$ JJ NN .
PRP MD VB SOLOC that PRP VBZ RB VB .
PRP MD VB TO VB SOLOC that PRP$ NNS VBP DObj .
PRP MD VB TO VB SOLOC that PRP$ NNS VBP DObj .
PRP MD VB SOLOC that PRP$ NNS VBP DObj .
PRP MD VB RB SOLOC that_insert DT NN VBZ IN PRP .
PRP MD VB VBN RB RBR if PRP VBD RB VBN VBN IN DT NN .
PRP MD RB VB LogN DT unless PRP VBD JJ IN DT NNS .
If NNS VBP IN NN , PRP VBP NNS .
if PRP VBZ RB JJ , PRP MD VB JJ TO VB PRP$ NN POS NN NN RBR .
If PRP VBD NN , PRP MD RB VB TO DT NN .
If PRP VBD NN , PRP MD RB VB TO DT NN .
If PRP VBD NN , WP VBD PRP VB .
If PRP VBZ VBG PRP MD VB RP .
If DT NN VBZ JJ JJ NN , PRP MD VB RP DT NN .
If PRP DObj JJ NN TO DT NN , PRP MD VB DT JJR NN .
If PRP VBP TO VB NN PRP MD VB JJR NN .
If PRP VBP TO VB NN PRP MD VB JJR NN .
SOLOC PRP VB PRP$ NN IN DT NN , PRP MD VB VBN RP .
Provided PRP LogN RB TO DObj NN RB , PRP RB VBP DT NN .
SOLOC that PRP VBP JJ NN , EX VBZ DT NN WRB PRP MD RB VB TO DT JJ NN .
SOLOC PRP VB PRP$ NN IN DT NN , PRP MD VB VBN RP .
SOLOC that_insert PRP LogN RB TO DObj NN RB , PRP RB VBP DT NN .
PRP MD VB IN VBG unless PRP VBZ DObj TO VB .
RB RB as PRP VBP JJ , FW MD VB JJ .
DT NN MD VB VBN IN NN unless EX VBZ DT NN .
DT JJ NNS VBP VBG TO VB RB JJ TO VB , SOLOC that PRP VBP IN PRP VBZ DT JJ LogN .
DT JJ NN MD VB DT NNS , SOLOC that PRP DObj DObj RP IN DT JJ NN .
Unless PRP VBZ , DT NN MD VB DObj .
Unless PRP VBP DT NN IN DT NN , PRP VBZ JJ .
Unless PRP VBP RB , PRP MD RB VB DT NN .
PRP MD VB RB if PRP MD RB DObj DT NN .
PRP MD VB NN unless PRP VBD NN .
WP MD PRP VB if PRP DObj DT NN IN NN .
WP MD VB if EX VBD DT NN .
PRP MD VB IN NNP unless PRP VBP RBR .
PRP MD DObj PRP$ NN SOLOC that_insert PRP DObj PRP RB .
VBG that_insert PRP VBZ NN CC NN , PRP VBZ RB VB PRP VBZ NN TO VB DT NN .
VBG that PRP VBZ NN CC NN , PRP VBZ RB VB PRP VBZ NN TO VB DT NN .
Although PRP VBZ RB JJ , RB PRP VBZ RB JJ .
Although PRP VBD VBN , RB PRP VBD IN VBG .
Although PRP VBD VBN RP , PRP VBD IN VBG .
Although PRP MD VB , PRP MD VB .
MD PRP DObj PRP whether PRP MD VB CC RB NN .
VBG as PRP VBD , PRP VBD WP VBD DT JJ NN TO VB .
NN though PRP VBZ , PRP VBP DT NN .
NN though PRP VBD , PRP VBD WP VBD DT JJ NN TO VB .
RB if PRP VBZ JJ , PRP VBZ PRP .
VB as PRP DObj , PRP MD RB VB DT DObj RB RB .
SOLOCCS PRP VBP DObj DT NN , PRP MD RB VB VBN .
SOLOCCS that PRP VBP DObj DT NN , PRP MD RB VB VBN .
SOLOCCS that_insert PRP VBP DObj DT NN , PRP MD RB VB VBN .
VBG as PRP VBZ , PRP DObj JJ NN .
However JJ PRP MD VB , PRP MD DObj PRP .
However JJ PRP VBP VBN , PRP MD RB DObj DT NN .
RB RB PRP VBP , DT NN MD VB .
PRP VBD DT JJ NN , although DT NNS VBD VBN .
NO Matter how JJ PRP VBP VBN , PRP MD RB DObj DT NN .
NO Matter what PRP VBP CC WRB PRP VBP it , PRP RB VBZ PRP VBP JJ .
NO Matter who PRP VBP , PRP MD VB DT NN .
PRP DObj DT NN though PRP VBD RB VBN RB JJ .
Though PDT DT NN VBD IN PRP , PRP MD RB VB TO PRP$ LogN .
Though PRP VBZ RB JJ , RB PRP VBZ RB JJ .
Though PRP VBZ JJ , CC PRP VBZ JJ .
Though PRP VBZ JJ , PRP VBZ JJ .
Though PRP VBD DT NN , PRP VBD WP VBD DT JJ NN TO VB .
Though PRP VBD VBN RP , PRP VBD IN VBG .
Though PRP MD VB , PRP MD VB .
VB JJ as PRP MD , PRP RB VBZ JJ TO VB DT NN RB .
PRP MD DObj DT NN RB if DT NN VBZ JJ .
PRP MD DObj DT NN RB JJ that_insert DT NN VBZ JJ .
PRP MD DObj DT NN RB though DT NN VBZ JJ .
PRP MD RB VB VBN RB if PRP VBP CD NNS .
Whatever VBD , PRP MD RB VB .
Whether PRP NNS CC RB , PRP MD VB RP IN DT VBG NN .
JJ DObj that_insert PRP DObj , PRP MD DObj PRP IN DT NN .
While PRP VBP DT NN , PRP VBP RB VB DT NN .
Whoever PRP VBP , PRP MD VB DT NN .
PRP MD VB TO VB DT NN whether PRP VBP JJ CC JJ .
PRP VBD VBN VBN CC PRP VBD VBN .
PRP VBZ JJ CC PRP VBZ VBG TO VB NN .
PRP VBZ VBG NN CC PRP DObj RB .
PRP RB JJ VBD PRP DT NN IN LogN , CC RB PRP VBD PRP TO VB NNP .
PRP RB JJ VBZ JJ CC RB PRP VBZ JJ .
PRP VBD VBG IN DT NNS NN CC SOLOR PRP VBZ .
PRP$ NN VBZ DT NN CC PRP$ NN VBZ DT NN .
PRP$ NN VBZ DT NN CC PRP$ NN VBZ DT NN .
PRP DObj DT NN CC PRP VBZ it RB JJ .
PRP VBP PRP CC PRP VBZ PRP .
PRP VBP NNS CC PRP IN NN NNS , RB .
PRP VBP VBG NN CC PRP VBP SOLOR NN .
PRP VBP VBG NN , PRP$ NN VBZ SOLOR NN CC PRP$ NN VBZ VBG NN .
PRP VBP VBG NN CC PRP VBP VBG NN .
PRP RB JJ VBD it CC RB PRP VBD it .
PRP RB JJ DObj PRP CC RB PRP VBD PRP .
PRP VBD PRP$ JJS , CC PRP VBD RP IN PRP IN JJ .
NNP VBD PRP$ NN CC PRP VBD TO NN .
NNP RB JJ VBZ NN CC RB PRP VBZ NN .
VB VBG DT NN TO DT JJ , CC PRP MD VB NN .
JJ NN NN VBD that_insert NNP CC PRP VBD NNS .
PRP$ NN VBZ DT NN CC PRP$ NN VBZ DT NN .
PRP$ NN VBZ DT NN CC PRP$ NN VBZ DT NN .
DT MD PRP VB DT LogN CC VB PRP VB DT NN .
DT MD PRP VB DT NN CC VB PRP DObj DT NNS .
DT VBD that_insert DT JJ NN VBP NN CC VBD PRP$ NNS VBP TO VB IN PRP .
DT VBD that_insert DT JJ NN VBP NN CC VBD PRP$ NNS VBP TO VB IN PRP .
DT VBZ PRP VBD PRP$ NN , CC MD PRP VB RB .
DT PRP VBZ PRP CC PRP DObj PRP IN NN .
DT NN MD VB PRP CC PRP MD DObj PRP IN LogN .
RB JJ VBP PRP PRP$ NN , CC RB PRP VBP PRP$ NN .
RB JJ VBD DT NN NN PRP , CC PRP VBD RB DObj PRP RB .
RB RB VBD that_insert PRP DObj TO PRP CC RB PRP VBD PRP .
RB RB VBD that_insert PRP DObj TO PRP CC RB PRP VBD PRP .
RB RB PRP VBZ VBG NN , CC RB PRP$ NN VBZ .
RB JJ PRP VBN TO NN RB , CC RB PRP$ NN VBZ .
RB RB PRP VBP IN NN , CC RB PRP$ NN VBZ .
RB JJ VBZ PRP PRP$ NN , CC RB PRP VBZ PRP$ NN .
RB JJ VBZ PRP PRP$ NN , CC RB PRP VBZ PRP$ NN .
PRP RB VBD PRP$ NN , PRP MD CC VBP RB .
PRP RB JJ VBZ JJ CC RB PRP VBZ JJ .
DT NNS IN NNS VBP VBG PRP NN IN VBG CC VBG JJ NN , CC DT VBZ RB JJ VBG DT NN IN NNS .
DT NN RB JJ VBZ PRP DT NN CC RB PRP VBZ PRP NN .
DT NN POS NN VBZ JJ , CC DT NN POS NN VBZ JJ .
DT NN POS NN VBZ NNP NNP CC DT NN POS NN VBZ JJ .
PRP RB JJ DObj CC RB PRP VBP NN .
DT RB JJ VBZ DT NN , CC PRP MD VB SOLOR DT NN IN PRP IN DT JJ JJ NNS .
VB PRP$ DObj , CC PRP MD DObj DT NN .
PRP VBD VBG DT NNS , CC PRP RB VBD RB IN NN .
RB PRP VBD , RB , that_insert PRP MD RB DObj PRP .
NNS VBP DT JJ NN TO VB IN , CC PRP VBP JJ .
NNP VBZ DT RB JJ CC PRP VBZ RB JJ .
PRP VBZ JJ : RB PRP VBP RB VB PRP .
PRP VBZ JJ while PRP$ JJ NN VBZ JJ .
PRP DObj DT NN , CC PRP MD RB VB VBG it .
PRP VBD JJ , RB PRP VBD JJ .
PRP VBD PRP$ NN , CC PRP MD RB VB PRP .
VB RP CC PRP MD VB DT JJ NN .
NNP RB RB PRP MD VB DT JJ NN .
PRP VBP RB IN NN SOLOR CC PRP VBP DT NNS TO VB .
PRP VBP RB JJ IN JJ CC PRP VBP DT JJ NN .
PRP VBP JJ TO VB PRP , CC MD PRP DObj PRP DT NN TO DT NN .
PRP VBP RB VB RB , CC PRP VBP DT NN CD .
PRP VBP RB VB NNS CC PRP VBP NN NNS .
PRP VBP RB VB NN CC PRP VBP NN .
PRP VBP RB VB TO VB it CC PRP VBP TO .
PRP VBP VBN , CC PRP MD VB RB .
PRP VBP that_insert NNP CC PRP$ JJ VBZ JJ .
PRP VBP NN while PRP VBZ NN .
PRP MD VB TO VB VBN TO DT NN JJ NN CC PRP VBD TO VB JJ NNS TO VB DT LogN .
PRP VBZ DT JJ NN IN JJ NNS TO VB , CC PRP VBZ RB JJ JJ NN NN .
PRP VBZ RB JJ , CC JJ CC JJ .
PRP VBZ JJ , CC PRP VBZ JJ .
PRP RB VBZ but PRP VBZ .
NNP VBZ JJ CC PRP VBZ RB JJ TO VB NNS .
NNP DT NN VBZ RB JJ , CC PRP VBP TO VB .
PRP$ NN VBZ DT JJ NN CC PRP$ NNS VBP RB RB VB PRP$ NNS .
PRP$ NN VBZ JJ CC PRP VBP JJ TO VB JJ IN DT NN .
JJ NNS VBG IN CD MD VB CD JJ NNS , CC RB RB CD VBP JJ IN NN .
IN CD JJ NNS VBP JJ IN NN , CC RB DT NN VBZ VBG VBN .
RB SOLOR PRP DObj CD TO CD NNS TO DObj DT NN NN NNS , CC DT VBZ DT RB JJ .
JJ DT NN , RB PRP MD VB .
PRP VBZ DT JJ NN : RB PRP VBP RB VB PRP .
PRP VBZ JJ CC JJ , CC RB NNS VBP PRP .
PRP VBZ RB JJ , CC PRP VBZ RB IN PRP$ CD NNS .
PRP MD VB JJ , CC PRP VBD IN NN .
NNP VBD DT NN IN NNP POS NN , CC PRP$ NNS VBP VBN IN PRP$ JJ NN IN DT NNP NNP .
NNPS MD DObj PRP NN CC PRP MD RB RB VB PRP RB .
DT DObj VBZ JJ : RB , PRP VBZ JJ PRP .
DT NNP NNP CC JJ JJ NNS RB RB VBD RP NNS IN NN , CC NNP VBZ RB VBD .
DT JJ JJ NN IN NNP VBZ RB CD NNS IN NN , CC PRP VBP VBN DT CD NN NN IN DT IN CD NN NNS IN DT NNP .
DT NN VBN IN NNS IN JJ NNP IN NNS , CC RB PRP MD RB DObj DT .
DT NN VBN IN NNS IN NNP IN NNS , CC PRP MD RB DObj DT NN .
EX VBP RB CD JJ NNS IN NNP , CC PRP RB VBP RB CD NN IN DT NN POS NN NN .
NNP NNS VBP RB IN JJ NNS , CC NNP VBD JJ TO DObj DT NNS .
PRP VBP DT NN IN DT VBG NNS CC DT VBZ VBN IN PRP$ LogN TO VB IN NN NNS .
PRP VB DT NN while PRP VB DT NN .
PRP MD VB RB , CC PRP MD VB .
MD PRP DObj PRP TO NN CC VB PRP VB TO NN RB JJ .
NNP that_insert PRP VBP PRP TO VB PRP CC VB PRP VBP TO VB it PRP .
VBP PRP VB RB CC VBP PRP DT NN RB .
CC NNP VBZ VBG CC PRP$ NNS VBP .
CC NNP VBZ VBG CC PRP$ NNS VBP .
PRP MD VB RB , CC PRP MD DObj NNS IN NN .
PRP VBD JJ DT NN , RB PRP MD VB DObj NN IN DT NNS VB .
NNP MD VB JJ IN NN CC PRP MD RB VB VBN VBN .
PRP VBP JJ CC PRP MD VB DT JJ NN .
MD PRP RB VB RB CC VB PRP that_insert VBP VBN RP .
PRP MD DObj DT NN IN PRP$ NN CC PRP MD DObj PRP .
PRP VB RP , CC RB PRP MD VB JJ .
PRP MD VB RB , RB PRP MD VB DT NN .
PRP VBD IN NN IN DT NN , RB PRP MD VB SOLOR PRP DT DObj .
NNP RB VBZ JJ , IN PRP VBZ TO DObj PRP$ NN IN NN .
NN DObj DT DObj , IN DT NN VBD VBN IN NN .
JJ NN VBZ JJR NN CC JJR NNS : RB PRP VBZ PRP$ NN TO VB it .
PRP VBD DT NN SOLOR , for PRP VBD VBN NNS IN DT NN .
PRP VBD NN CC NN , RB , PRP VBD JJ TO DObj DT NNS NN .
PRP VBP DObj DT NN TO VB , IN PRP VBP TO VB SOLOR .
PRP VBD TO PRP , for PRP VBD VBN PRP .
PRP VBZ DT NN , IN PRP VBD it IN JJ .
PRP VBZ NN SOLOR , RB DT NN MD VB JJR .
PRP VBZ NN , for DT NNS VBP VBG .
PRP VBZ NN , for DT NNS VBP VBG .
PRP VBZ NN SOLOR , RB DT NN MD VB JJR .
PRP VBZ RB DT RB JJ NN , IN PRP RB VBP PRP$ NN .
DT NNPS VBP RB VBN JJ NN IN NN NN , IN PRP MD VB IN DT IN DT NN IN VBG JJ NN .
DT NN VBZ VBN IN NN RB , IN PRP VBP SOLOR NNS .
DT NN VBD JJ so PRP VBD IN PRP$ NN .
DT NN DObj RP RB DT NN , so PRP VBD RB VB DT JJ NN .
PRP DObj PRP TO VB , IN PRP VBD .
PRP VBP VBN NN , IN EX VBZ DT NN NN .
PRP VBD PRP TO VB , IN PRP DObj .
PRP VBP IN PRP$ NN NN , IN PRP MD VB JJ NNS IN LogN TO VB DT NN IN PRP .
PRP MD RBR DObj DT NN IN PRP , for PRP VBZ VBG TO VB .
DT NN that_insert DObj DT RBR , DT JJR NN PRP VBZ .
PRP VBZ RBR than PRP VBZ JJ IN PRP .
PRP VBZ DT RBR NN than PRP VBD NN .
PRP VBZ RBR RB than PRP$ NN VBZ .
PRP VBD RBR JJ than PRP VBD JJ NN .
PRP VBD RB IN RB as PRP VBD VBN RB .
PRP DObj IN JJ NNS as PRP VBP VBN TO VB DObj .
PRP VBZ RB RB JJ as PRP VBP .
NNP VBD RBR than NNS VBP .
NNP VBZ RBR IN DT NN that_insert PRP VBZ .
NNS VBD DT NN IN NN differently than PRP VBP NN .
PRP DObj RB RB RB as PRP VBZ VBD RP .
DT VBZ RB JJ DT NN as PRP MD DObj .
DT NN VBD RBR RB than NN VBP .
DT JJR DT NN VBZ VBN , DT JJR DT NN MD VB .
DT JJR PRP VBP , DT JJR PRP VBP PRP$ NN .
DT JJR PRP DObj , DT JJR NN PRP DObj .
DT NN VBZ RB RB JJ as PRP VBD JJ .
DT NNS IN NNP VBP RB RB JJ as PRP VBP IN NNP .
DT NN VBD RB VB RB RB as PRP VBD .
DT NN IN NN VBP JJR RP than PRP VBD TO VB .
EX VBD JJR NNS than PRP VBD VBN .
DT VBZ RB JJ DT NN as PRP MD VB IN .
PRP VBD TO VB JJ NN RB RB IN VB NN .
NNP VBZ RB JJ IN JJ NN as PRP VBZ JJ IN JJ NN .
PRP VBP it RB JJ as PRP VBP .
PRP VBD RP PRP$ NN as if PRP VBD VBN VBN .
PRP RB DObj DT NN as though PRP VBD JJ .
PRP VBZ as if PRP VBD VBN VBN IN NN .
PRP VBZ as if PRP VBZ JJ .
PRP VBZ as though PRP VBD VBN VBN IN NN .
PRP VBD PRP$ NNS as if PRP VBD VBG TO VB NN .
PRP VBZ PRP as if PRP VBP DT NN .
PRP VBD RB RB IN VBG DT NN .
PRP VBD RB IN RB VBG DT NN .
PRP VBP VBN it as PRP VBP .
PRP VBP DT JJ NN as if PRP VBD NN .
PRP VBD as if EX MD VB DT JJ NN .
PRP VBZ as if DT NN MD DObj RP RB RB .
NNP VBD RB VB as PRP VBD .
DT NNS VBZ VBN as if PRP VBD VBN IN NN .
DT JJ NN VBZ as if PRP VBZ DT JJ NN .
PRP RB VBP DT NNS as if PRP RB VBD .
PRP RB VBP DT NNS as though PRP RB VBD .
PRP VBD DT NN as if PRP VBD PRP$ JJ .
PRP MD VB as PRP$ NNS DObj PRP .
IN DT NNS VBP DT NNS , whose magnificence DT NN RB VBZ IN DT NN .
NNS , whose JJ NN VBZ JJ , MD DObj CC DObj IN JJ JJ NNS .
As PRP DT VBP , DT NN VBZ NN .
VBP PRP VBN DT NN NN , whose JJ NN VBZ NN JJ .
PRP VBZ DT NN , who VBZ DT NN .
PRP VBZ VBN IN NN , as PRP RB VBD .
PRP MD VB JJ NNS , IN which case PRP MD VB TO VB VBN RP .
PRP VBD that PRP VBD RB VBN PRP RB , WDT VBD RB JJ .
PRP VBD DT NN , which VBD PRP .
PRP MD VB RP DT NN IN NNP , when PRP MD VB JJ .
PRP$ NN RB VBD RP IN DT JJ JJ NNS , IN where PRP MD VB NN CC NNS .
PRP VBP DT NN , who VBZ DT JJ NN .
PRP VBP DT NN , who VBZ VBG DT NN .
IN PRP$ NN EX VBP CD NNS , DT JJS IN whom VBZ NNP NNP .
JJ VBP that_insert PRP VBD DT NNS POS NNP NNP , IN WDT JJ JJ NNS VBP VBN DT NN .
NNP VBZ DT JJ NN IN DT NN , DT NN IN which VBZ CD NNS IN NN .
PRP$ NN , who VBZ DObj IN DT NNP NNP NNP PDT PRP$ NN , VBZ VBG JJ NN .
PRP$ NN , who VBZ RB JJ , VBZ IN EX MD VB DT NNS DT NN .
PRP$ NN , who VBD DT JJ JJ , VBD DT JJ DObj .
NNP , whom PRP VBD IN NNP , VBZ SOLOR RB IN NNP .
NNP VBZ , as PRP VBP , DT JJ NN IN NNP .
NNP , which VBD VBN IN NNP , VBZ VBG RBR CC RBR JJ .
PRP VBZ RB JJ , which PRP MD RB VB .
PRP VBZ DT NN , which PRP VBP RB .
PRP VBD RB JJ IN DT NNS , which PRP$ NN RB VBD .
NNP NNP , whom NN VBZ RB JJ , VBZ CD IN DT JJS NNS IN PRP$ NN .
DT DObj , which PRP$ NN DObj PRP IN NNP , VBZ RB JJ IN VBG PRP$ NNP NNP .
DT NN , whose NNS VBZ DT NN , VBZ RB JJ .
DT NN , which PRP DObj JJ NN , VBZ RB JJ .
DT PLACE where NN CC NNS VBP .
DT DObj , whose NNS VBZ JJ , VBZ JJ IN DT JJ NNS .
DT DObj , whose NNS VBZ RB JJ , VBZ JJ IN DT NN .
DT NN VBZ DT NN , which DObj PRP JJ IN NNS TO VB .
DT CD NNS VBD JJ IN DT LogN , as VBD VBN RB .
DT CD NN VBD RB VBN , which IN LogN PRP VBD .
EX VBP CD NNS IN DT JJ NN , JJS IN which VBP JJ .
PRP VBD TO VB , where PRP VBD IN CD NNS .
PRP MD VB RP DT NN IN JJ NN , when PRP MD RB VB RB JJ .
NNP VBD CD NNS IN DT NN , IN which NN PRP VBD NN .
When RB VBN IN NN , WDT PRP RB VBD , PRP MD VB DT IN VBG CC VBG .
NNP , which PRP VBD JJ NN , VBZ DT JJ JJ NN .
JJ NNS VBP VBN TO VB how PRP MD DObj PRP$ NNS CC NNS IN NNP .
NNP NNP VBZ that_insert DT JJ NN NN VBZ VBG .
NNP VBZ RP whether PRP VBP IN PRP .
VB PRP RB VBN that DT NN IN PRP$ NN MD VB VBN .
PRP VBD that PRP VBD VBG TO PRP .
PRP DObj if PRP VBD DObj TO NNP .
PRP DObj PRP where PRP MD DObj NNP .
PRP DObj whose NNS was DT JJS .
PRP VBD RB DObj PRP when PRP MD VB RB .
PRP VBD RP whether PRP MD VB CC DObj DT NN .
PRP VBD that PRP MD VB RP TO DT NNP RB .
PRP VBD that_insert PRP MD VB DT NN DT NN .
PRP DObj PRP that PRP VBD VBG IN DT JJ NN .
PRP DObj PRP that PRP MD VB TO DT NN DT JJ NN .
PRP DObj PRP that PRP MD VB PRP IN DT JJ NN .
PRP VBP JJ that PRP VBP DObj DT NN .
PRP VBP JJ that PRP VBP VBN PRP RB JJ .
PRP VBP JJ that_insert PRP MD DObj DT NN .
PRP DObj PRP whether PRP VBD VBN PDT DT NN PRP CC IN PRP VBD VBN DT NN .
PRP MD RB VB whether CC RB NN MD VB IN NN .
PRP VBP RB VB whether CC RB PRP MD VB .
PRP VBP RB VB if EX MD VB DT NN DT RBR .
PRP VBP RB VB whom PRP MD VB RP .
PRP VBP RB VB that_insert PRP VBZ DT JJ NN .
PRP VBP RB VB that_insert NNS MD VB .
PRP VBP it DT NN that PRP VBP RB VBN TO DT NN .
PRP DObj PRP JJ that PRP MD VB it IN PDT DT JJ NN .
PRP VBP DObj RP that PDT DT NNS IN DT NN VBP VBN DObj RP .
PRP VBP DObj PRP DT NN that PRP VBP NNS .
PRP VBD that_insert it VBD IN PRP VBD VBN RB .
PRP VBP it JJ that PRP DObj RB IN JJ NN DT NN .
PRP VBP it RB JJ that PRP VBZ RP VBG RB DT NN .
PRP LogN PRP JJ that PRP MD VB DT NN IN RB CD NNS .
PRP VBP TO VB if PRP VBD PRP$ NN NN .
NNP NNP VBZ that_insert DT JJ NN IN DT NNP NNP NNP VBZ TO VB DT JJ NN IN NN VBG NNS IN DT NN .
NN VBD whether PRP MD DObj DT NN .
NN IN PRP VBZ where DT JJ NNS MD VB DObj .
PRP$ NN VBD that NNP VBZ DT JJ NN IN DT NN .
PRP$ NN DObj PRP that NN VBZ RB RBR IN NN .
UH DObj PRP when PRP MD VB DT NN .
UH DObj PRP what PRP DObj IN DT NN NN .
NNS VBP VBN that DT NN VBZ IN DT NN .
PRP VBZ that_insert DT JJ LogN NN VBZ RB RB JJ .
VB PRP which VBD PRP VBP IN .
DT DObj MD DObj PRP what DT JJS NNS VBP .
DT NN VBZ that_insert NN VBZ RB .
DT NN VBD that DT NN VBZ IN DT NN NN .
PRP MD VB DObj NN whether PRP MD DObj DT NN CC RB .
PRP DT VBP what PRP VBD TO VB JJ .
PRP DT VBP that PRP MD VB , IN NNS IN PRP$ NN VBP JJR .
PRP DT DObj PRP JJ that PRP DObj DT JJ LogN IN DT NN .
PRP VBP VBG RP whether PRP VBP NNS IN PRP$ NN .
PRP VBD what PRP VBD VBN TO VB JJ .
PRP VBP that_insert PRP VBP VBN DT NN .
PRP DObj PRP that PRP MD VB IN PRP .
PRP VBP it JJ that PRP DObj DT NN TO NN .
NNP DObj JJR NNS IN NN that_insert DT NN VBZ JJ .
PRP DObj RB IN NN that_insert PRP MD VB DT NN .
PRP VBD VBN IN NN DT NN MD VB PRP .
PRP VBP VBG PRP that lest PRP MD DObj DT DObj .
PRP DObj RP RB RB that PRP MD VB DT JJ NN .
JJS NNS VBP TO NN so that PRP MD VB NNS , NNS CC NNS .
PRP VBZ DObj DT DObj IN LogN that PRP MD VB DT NN NNS .
PRP VBD RB RB that PRP MD RB VB PRP$ NNS .
DT NN DObj DT NN TO VB RP IN DT NNS so that PRP MD VB PRP .
DT NNS VBN lest PRP MD VB DT VBG NN .
DT NN VBD PRP$ NN IN NN that DT NNS IN DT NN MD VB JJR RB .
PRP VBP VBN DT JJ NN so that PRP MD VB TO DT NNS RB .
PRP MD VB RBR so that PRP MD VB VBN IN DT .
IN DT NN , PRP VBD as if PRP MD RB VB IN DT JJ LogN .
PRP VBZ VBN what PRP VBD TO VB CD NNS RB .
PRP VBZ RB RB what PRP VBD .
PRP$ JJ LogN VBD whether NNP NNP VBD VBN RB .
PRP$ JJ NN VBD that DT NN VBP .
PRP$ LogN VBZ that PRP MD VB JJ .
PRP VBZ RB because PRP VBZ RB VB PRP .
PRP VBZ RB as though PRP VBD JJ .
PRP VBD as if PRP VBD VBG TO VB .
PRP$ LogN VBZ that PRP MD VB VBG NNS RB SOLOR .
PRP$ LogN VBZ who MD DObj RP NN IN DT NNP .
NNP NNP VBZ when PRP MD VB .
SOLOR PRP VBD as though PRP VBD VBN NNP IN NNS .
NNP VBZ RB what PRP VBD TO VB .
PRP VBZ VBN where PRP VBD NN IN DT NN .
DT VBZ what PRP VBP TO VB .
DT VBZ where PRP RB VBD PRP .
DT VBZ because PRP VBD TO VB PRP$ JJ NN IN PRP$ NN .
DT VBZ where PRP VBD VBN .
DT VBD when PRP VBD CD .
DT NN VBZ whether PRP VBD NN .
DT LogN VBZ that PRP VBZ RB RB VB .
DT NN VBZ where NNP NNP RB VBD .
DT NN VBZ whether PRP MD DObj PRP DT NN .
DT LogN VBZ how PRP MD DObj PRP .
DT LogN VBZ how PRP MD DObj DT NNS PRP VBP .
DT LogN VBZ whether DT NN VBZ JJ SOLOR .
DT LogN VBZ whether PRP MD VB IN PRP .
DT LogN VBZ who PRP MD VB .
DT NN VBZ that PRP VBP VBN PRP$ NN .
DT VBZ why PRP VBP JJ .
PRP VBP RB who PRP LogN PRP VBD .
As PRP VBD VBG , PRP VBD IN NN .
As PRP VBP DT NN , PRP MD RB DObj PRP .
PRP MD RB VB VBN PRP , for PRP VBD RB RB .
PRP VBD PRP because PRP VBD JJ .
PRP VBP it because PRP VBP it .
PRP VBP RB because PRP VBP TO VB DT NN NN IN DT NN .
SOLOR that PRP VBP RB , PRP MD RBR VB .
SOLOR that PRP VBZ VBG , PRP MD VB RB .
Since DT NN VBZ VBN , VB POS VB IN DT NN .
Since PRP VBP DT NN , PRP MD RB DObj PRP .
Since PRP VBP RB JJ , PRP MD RB DObj PRP IN PRP .
DT MD VB JJ because DT NNP NN VBZ RB VBN TO VB VBN IN NN IN NNP .
DT NN VBZ RB JJ because PRP VBZ JJ .
DT NN VBD because PRP VBD VBN RB .
DT NN VBD because PRP VBD VBN RB .
PRP MD VB DT NNS because DT NN RB VBZ .
PRP VBZ PDT DT JJ NN that PRP MD RB VB PRP .
NNP VBZ RB JJ that PRP MD RB VB DT NN IN PRP DT RB .
PRP VBD JJ JJ NNS that PRP MD RB VB DT NN .
PRP VBZ RB JJ that PRP MD VB TO NN .
PRP VBZ RB RB that DT NN MD VB PRP .
PRP VBD RB JJ that PRP MD RB VB TO VB DT NN .
PRP VBD RB JJ that PRP MD RB VB DT LogN .
PRP VBD PDT DT JJ NN that NN VBD TO VB NN .
PRP VBD PDT DT JJ NN that DT IN PRP VBD TO VB it RB .
NNP VBZ RB RB RB that PRP RB RB VBP PRP .
PRP$ NN VBZ RB RB VBN that PRP MD VB JJ NNS .
DT NN VBD RB JJ that DT IN PRP VBD TO VB it RB .
DT NN DObj RB JJ NNS that PRP VBP TO DObj NN IN PRP .
EX VBZ RB JJ DT increase IN NN that DT NN NN VBZ DObj .
DT CD VBD RB JJ IN NN that PRP RB DObj NNS IN DT JJ .
PRP VBZ DT NN that PRP VBD RB VB .
PRP VBZ DT NN that PRP MD RB VB .
PRP VBZ RB VB PRP whether PRP VBP CC RB .
PRP VBZ RB DObj DT NN whether PRP VBZ CC RB .
PRP VBD that PRP VBD IN WDT NN .
PRP VBZ DT NN TO PRP how PRP DT VBD .
PRP VBZ JJ whether PRP MD VB JJ TO VB .
PRP VBZ VBN TO PDT DT JJ NNS IN JJ NNS .
PRP VBZ VBN that NNP NNP VBZ VBN IN NNP .
PRP VBZ TO VB VBN whether PRP MD VB PRP JJ CC JJ .
PRP VBD PRP that NNP VBD RB DObj NN WRB PRP VBD .
PRP VBD DT LogN whether PRP MD VB PRP .
PRP VBD RB JJ that PRP DObj TO VB TO PRP .
That PRP MD VB VBZ JJ .
DT NN that_insert MD VB RP VBZ JJ .
That PRP VBD DT NN VBZ DT NN .
That PRP VBP RB JJ VBZ PRP .
That PRP VBD RB VB TO DT NN VBD DT NN .
What PRP VBZ VBP DT DObj .
What PRP VBP TO VB VBZ DT .
What PRP VBP VBZ NN .
Whatever PRP VBD VBD JJ .
When PRP MD VB RB VBZ IN DT NN .
When PRP MD VB VBZ DT NN .
When PRP MD VB VBZ RB VBN .
When DT NN VBZ TO DObj RP VBZ RB VBN VBN .
When PRP MD VB VBZ RB VBN DObj JJ .
Where DT NN MD VB SOLOR VBZ RB RB VBN .
Where PRP MD DObj PRP VBZ DT LogN .
Whether PRP VBZ VBG CC RB VBZ RB VB RB RB .
Whether PRP MD VB PRP VBD DT LogN .
NNP IN PRP VBN IN DT NN VBZ RB DT NN .
NNP VBZ that_insert DT NN MD VB VBN .
Whoever VBZ TO VB IN DT NN MD DObj DT NN .
NNP VBZ DT NN IN LogN NN .
NNP VBZ TO VB DT JJR NN IN VBG NNS IN JJ NN .
PRP VBD PRP DT NNS .
PRP VBD DT DObj TO PRP$ NN .
PRP VBZ JJ .
PRP VBZ NNP RB JJ .
PRP MD DObj PRP DT JJ NN .
PRP VBD NN .
PRP DObj DT DObj JJ .
NNP VBZ PRP JJ .
NNP VBZ DT NN .
PRP$ NN MD DObj NN .
NNP VBZ RB VBG IN JJ NNS TO VB DT NN VBN TO DObj NNS TO NNP .
NNP VBZ IN NNP NNP NNP .
NNP NNP VBD DT NN IN DT NN NN .
PRP VBD DT NN .
DT NN VBZ DT JJ NN VBN IN DT NN IN NN .
DT NN VBZ VBN DT NN IN PRP$ JJ JJ NN NN .
DT NN VBZ DT JJ LogN TO VB NNS TO DT NNS CC NNS .
DT NN MD VB JJ IN NN IN DT RB JJR NN .
DT NNS VBD VBN IN DT NNP NNP CC NNP NNP .
DT NN DObj DT NN POS NN , NN CC NN .
PRP MD VB DT JJ NN IN DT NN IN CC CC CC CD NNS .
DT LogN VBZ JJ , DT LogN VBZ JJ CC DT LogN VBZ JJ .
PRP RB VBD NNS .
As DT NN VBD IN DT NN DObj JJR .
Before PRP VBP PRP$ NN , VB PRP VB RB CD NNS TO DT JJ NN .
IN DT NN that_insert DT NN VBD , NNS IN NNS VBD NNS .
VB DT NN before PRP DObj DT NN .
DT NN PRP VBD TO VB , PRP MD VB IN PRP .
PRP VBD RB VBN RB when PRP VBD DT JJ NN IN PRP$ NN .
PRP VBD NO Sooner VBN PRP$ NN than DT NNS VBD VBG .
PRP VBD IN DT NN IN VBG when NN VBD IN DT NN .
PRP VBD RB VBG when DT NN VBD CC PRP$ NN VBD RP .
PRP MD VB PRP RB RB as PRP DObj NN .
PRP MD VB RB till DT NN VBZ .
PRP VBP VBN IN NNP since PRP DObj .
PRP VBP VBN DT NN IN JJ NNS IN PRP since PRP VBD RB IN RB .
PRP VBD IN TO DObj DT NN when DT NN VBD .
PRP VBD JJ IN NN when DT NN VBD .
PRP MD VB PRP when PRP DObj NN .
PRP VBD TO VB RB as PRP VBD NN .
NNP DObj NN while PRP$ NNS VBD VBG PRP$ NN .
PRP VBP , PRP VBD VBG TO DObj IN DT NN RB when PRP$ NN VBD VBZ IN NN .
NNP VBD RB JJ when PRP VBD NN IN PRP$ NN TO VB NNP .
PRP VBD RB VBN PRP$ NN when PRP$ NN DObj PRP TO VB VBG DT NN NN .
DT NN VBD NNP when PRP VBD PRP$ NN .
DT NN PRP VBD DT LogN , PRP VBN TO DT NN .
DT JJ NN that_insert PRP VBD PRP , PRP VBD VBG NN .
DT NNS VBD VBG PRP$ JJ NN when DT NN VBD RP .
PRP VBD NO Sooner VBN DT NN than PRP VBD VBN IN NN .
PRP VBD IN TO DObj when PRP VBD RP .
PRP VBD IN TO VB when PRP VBD TO VB .
PRP VBD VBG PRP$ NN when PRP VBD .
When PRP VBP , PRP$ NNS MD DObj NN IN PRP .
When PRP VBD IN DT NN , PRP VBD TO VB DT NN IN PRP .
When PRP VBD RP DT NN , PRP VBD TO NN .
When DT NN VBD , NNS VBD VBN VBN .
Whenever PRP VBP TO VB DT NN , PRP DObj RB JJ IN PRP VBP .
While PRP$ NN VBD VBG DT NN , PRP VBD VBG NN .
PRP MD RB VB NN till PRP VBP PRP$ NN .
PRP MD RB VB NN until PRP VBP PRP$ NN .
PRP VBP JJR DT NN that_insert PRP VBP PRP .
PRP MD VB TO VB PRP$ NNS CC PRP$ NN when PRP VBP DT LogN .
PRP MD VB JJ when PRP VBP JJ CC JJ .
PRP VBD PRP TO VB where DT NN VBZ JJ .
PRP VBZ JJ wherever PRP VBZ .
PRP VBZ where EX VBP DT NN NN .
PRP DObj PRP$ NN where PRP VBD RP NN .
PRP MD VB DT DObj where PRP MD VB it .
IN NN , RB , DT NNP NNP VBZ VBN TO DObj NN wherever EX VBZ JJ NN .
VB DT NN where PRP VBP DT LogN .
VB wherever PRP VBP .
PRP VBD where PRP VBD VBN IN NN CD NNS RB .
PRP MD VB where PRP VBP JJ .
PRP MD RB VB where EX VBZ DT JJ NN .
PRP VBP , VB CC VB where PRP$ NNS VBP VBN CC VBN .
PRP VBP TO VB where NN VBZ TO VB .
PRP MD PLACE where PRP MD DObj NN .
PRP VBD RB , where PRP VBD NN .
Where PRP VBP EX VBP RB IN NNS .
Where DT NNP NNP IN NNP VBZ , RB DT NNS VBP JJ .
Where DT NN VBZ , PRP MD DObj NN .
Where EX VBZ DT NN , EX VBZ DT NN .
Where EX VBZ DT NN , EX VBZ DT NN .
Where EX VBZ NN , EX VBZ LogN .
Where EX VBZ DT NN , NN VBZ JJ CC JJ .
NNP that_insert PRP VBP PRP MD VB VBG IN PRP .
VB PRP VB , PRP MD VB PRP .
VB PRP VB , PRP MD VB RB JJ NN RB RB as PRP VBP JJ TO VB .
IN DT NN , DT NN MD VB where PRP VBZ CC WRB PRP VBZ .
PRP MD VB RB that_insert PRP VBP .
PRP MD VB VBN DT DObj where PRP DObj PRP .
