VB PRP$ NN whether PRP VBP VBG .
VB PRP PRP$ NN that PRP MD VB TO PRP$ NN DT NN .
PRP VBD DT NN why PRP VBD .
PRP VBZ VBN DT NN why DT NN VBD RB IN NN .
PRP VBZ RB VBN DT NN whether PRP MD VB RB .
PRP VBD TO NNP POS NN that DT NN NNS VBP DT NN .
PRP VBD PRP DT NN that PRP MD RB VB JJ NN .
PRP VBP VBN IN NNP VBG IN DT NN that PRP MD RB VB JJ TO VB PRP DT NN .
PRP VBP VBN TO DT NN that PRP VBD JJ TO VB DT .
PRP MD VB PRP$ NN that PRP MD VB DT JJ NN .
PRP VBD DT NN that PRP VBD RB .
PRP VBP DT NN what VBP NNS PRP VBZ .
PRP VBP DT NN when PRP MD VB RB .
PRP VBP DT NN when PRP MD VB RB .
PRP VBP DT NN how PRP VBD RB , RB IN NN .
PRP$ NN how PRP MD VB IN NN IN PRP VBZ RB VBN VBN .
RB VBD DT NN that PDT DT NNS MD VB DT NNS .
DT NN that PRP VBD RB VBD NN VBN NN .
DT NN that DT NN VBZ VBN VBZ RB VB PRP VBD VBN .
DT NN that PRP MD VB DT NN RB IN VBG VBZ RB JJ .
DT NN that PRP VBD VBN DT NN RB VBN IN DT JJ NN .
DT NN that PRP MD VB RB JJ NN VBZ TO VB VBN .
DT NN that DT NN IN DT NN NN MD VB IN NN VBZ RB VBN .
DT NN whether PRP MD VB IN DT NN VBD VBN IN JJ NN .
DT NN who MD VB DT NN VBZ NN .
DT NN that DT JJ NN VB VBN VBD DT NN .
DT NN VBD TO PRP that RB DT NN VBD VBN DT NN .
EX VBZ DT NN that PRP VBZ VBN IN DT NN .
EX VBD DT NN that NNP MD VB VBN IN DT NN .
PRP VBP JJ IN DT NN that DT NN VBZ IN NNS .
PRP VBD VBN IN DT NN that PRP VBD JJ .
PRP MD VB DT NN whether DT NNS NN MD VB VBN IN NN .
PRP VBP RB VBG DT NN whether PRP VBZ JJ .
PRP VBP RB VBG IN DT NN whether PRP VBZ IN JJ .
PRP VBP RB VB DT NN why DT VBZ DT JJS NN .
PRP VBP RB RB VBN DT NN where PRP VBP VBG TO VB PRP$ JJ NN .
NNP VBD that PRP VBD VBN RB .
NNP NNP VBZ VBN DT NN why DT NN VBD RB IN NN .
PDT DT NNS that PRP$ NNS VBP PRP IN PRP$ NN MD VB VBN RP .
IN DT JJ NN PRP VBD RB JJ NN as PRP MD VB .
NNP VBZ NN which VBZ NN , RB VBN .
NNP , which VBZ IN DT NN , VBZ , RB , JJ IN JJ JJ NN .
PRP VBZ RB DT NN IN NN who MD VB RP IN PRP$ NNS .
PRP VBZ DT NN whose NNS VBZ DT NN .
PRP VBZ DT JJ NN whose NNS VBP RB IN JJ .
PRP VBZ RB DT JJ NN as PRP VBD .
PRP VBZ DT JJ NN that PRP VBP .
PRP VBZ DT JJ NN IN DT NNS that VBZ VBN TO VB .
PRP VBZ DT JJ NN IN PRP that VBZ JJ .
PRP VBZ TO VB NNS which VBP VBN IN JJ NNS .
PRP RB VBD RP DT JJS NN , which RB VBD CD NNS .
PRP$ NN TO PRP VBD RB DT JJ as PRP VBD RB VBN .
RB VBZ DT NN that PRP VBD VBN PRP IN .
PRP VBP DT NN TO which PRP VBZ .
PRP VBP RB VB DT NN why PRP VBZ JJ NN .
PRP VBP JJ IN JJ NNS who VBP PRP$ NNS IN DT NN IN NN .
PRP VBD PRP JJ NNS which PRP VBD DT NN IN .
PRP VBP DT NN that PRP MD VB .
PRP VBP DT NNS that PRP MD VB NN .
PRP VBP DT NN whose NN VBZ JJ .
PRP VBP DT NNS that VBP VBN IN NN NN .
PRP RB VBD IN DT NN whose NNS has VBN IN .
PRP VBP DT NNS when PRP VBD IN DT NN IN PRP$ NNS .
PRP RB VBP DT NN when PRP RB VBD TO DT NN .
PRP VBD DT NN whose NN VBZ VBN DT IN DT NN .
PRP VBD RP IN NN IN DT NN where PRP MD VB DT NN .
If PRP VBP RB IN DT NN , PRP MD RB VB RP DT NN IN WDT PRP VBD RB .
VBZ PRP DT NN that VBZ NNS .
VBZ PRP DT NN that VBZ NNS .
PRP VBZ IN DT NN that PRP RB VBD .
PRP VBD DT JJS NN that PRP RB VBD .
NNP VBD JJ IN DT NNS which DT NN VBD .
NNP NNP VBZ DT NN whom PRP VBD RP IN DT NN .
NNP NNP VBD DT NN who VBD JJ IN VBG IN NNPS .
NN VBZ VBG TO VB DT NN whose JJ NN VBZ IN DT NN NNS .
RB RB IN NNP VBD DT JJ NN which VBD IN DT NNP .
NNP VBZ NN that PRP RB VBP VBG .
NNS who VBP IN DT NN VBP JJ TO DT NN .
NNP VBZ DT RBS JJ JJ NN that PRP VBP RB VBN RP .
VBG TO DT NN where PRP VBD TO VB MD VB DT VBG NN .
VB RP RB DT NNS which PRP VBP RB VB NNP TO VB .
PRP VBZ CD IN DT NNS that VBP RB JJ .
PRP VBZ DT JJ NN that PRP VBD TO VB .
PRP VBD VBN IN DT JJ NN , where EX VBD DT VBG NN .
DT VBZ DT NN whom PRP VBP .
DT VBZ DT NN how PRP VBP NNP .
DT VBZ DT NN why PRP MD VB RB .
DT VBD DT NN why PRP VBD TO VB IN DT NN .
DT NN CC PRP$ NN that VBD VBN IN DT JJ NN VBD VBN TO DT NN NN .
DT NN whose NN VBZ VBN MD RB VB VBN .
DT NN VBZ IN DT NNS when NNS VBD NNS .
DT NN that PRP VBD VBG IN VBD JJ .
DT NN which VBZ NNS VBZ RB RB IN RB .
DT JJ NN that PRP VBP TO VB RB VBZ TO VB DT NN .
DT NN whom DT NN RB VBZ VBZ PRP$ NN .
DT NN IN whom PRP VBD VBN VBG IN CD NNS RB VBD PRP$ NNS CC VBD .
DT NN , which PRP VBP RB , VBD RB JJ .
DT NN that PRP VBD IN PRP NN VBZ RB JJ .
DT NN who VBZ VBG NNS IN PRP$ NN VBZ DT NN .
DT NN whom PRP VBD DT NN TO VBZ DT NN IN NNS .
DT NN whom PRP VBD RB RB VBZ PRP$ JJ NN .
DT NN whose NN PRP VBP RP VBZ JJ NN TO VBG PRP$ VBG NNS .
DT NN IN NNS that VBP TO VB DT NN DT NN VBZ CD CD .
DT NN , who VBD VBN RB IN RB CD NNS , VBD TO VB PRP$ NNS .
DT NNS who VBD IN NNP IN DT CD NNS VBD NNP NNP VBD DT IN PRP$ NN IN NNP .
DT NN that PRP VBD TO PRP VBZ RB JJ .
DT NN whom PRP VBP TO VB VBZ VBN .
DT NN VBP VBN IN DT DT NN NNS whom PRP VBP .
DT NN whom PRP VBP VBG IN VBZ VBN .
DT NN why PRP VBZ JJ VBZ IN PRP$ NN VBD JJ .
DT NN why PRP VBD VBN VBZ JJ TO PRP .
DT NN why PRP VBD RB VB DT NN VBD IN PRP$ NNP VBD RB RB JJ .
DT NN whose NNS VBZ RB VBZ NN .
DT NN which PRP RB VBD RP VBZ RB JJ .
DT NN which VBZ IN NNP VBZ NN .
DT NN which PRP VBD VBN IN VBD RB JJ .
DT NNS NN VBZ DT NN which PRP MD RB VB RP .
DT NN when PRP VBD RB RB VBD .
DT NNS VBD RP DT JJ NN where PRP VBD RP CC VBD .
DT CD NNS VBD JJ IN DT NN , as VBD VBN RB .
DT NNS RB VBP IN DT NN , which VBZ RB JJ TO NNS .
DT JJS NN that PRP VBP JJ IN VBD IN DT NN .
EX VBZ DT NN that PRP MD VB .
PRP VBD RP PDT DT NNS that VBD JJ IN DT JJ NN .
DT MD VB DT VBG NN IN DT NN , who RB VBZ CD JJR NNS IN DT NN .
DT VBZ CD IN DT JJ NNS why DT IN PRP$ NN MD RB VB VBN RB .
DT VBZ DT NN whom PRP VBD NN IN RB .
DT VBZ DT NN when DT NN VBZ JJ IN NNS .
DT VBZ DT NN which PRP VBD NN .
DT VBZ DT NN , IN which DT NNS VBP VBN .
DT VBZ DT NN which VBZ VBN IN DT NN IN NNS .
DT VBZ DT JJ NN that PRP VBP VBN VBG IN .
DT who VBP TO VB TO DT NN MD VB IN DT NN NN IN CD NN NN .
NNP VBD DT NN when DT NNS POS NNP IN NNP VBD VBN .
NNP IN PRP$ JJ VBN NN , which MD VB IN DT NN JJ NN .
NNP VBZ DT JJ NN IN which JJS NN VBP .
PRP VBP VBN IN DT NN which MD VB DT NN JJ CD NNS DT NN .
PRP MD RB VB NNS IN DT NN , CC DT VBZ RB NN that MD VB VBN IN .
PRP VBD IN DT NNS CC NNS that PRP VBD IN NN .
NN PRP VBD DT JJ NN who VBD VBN PRP$ NN .
PRP MD VB TO VB VBN that PRP$ NNS VBP VBN .
PRP MD VB TO VB VBG that PRP$ NNS VBP VBN .
PRP MD VB RB VBD that_insert DT NN VBZ IN PRP .
PRP MD VB RB VBG that_insert DT NN VBZ IN PRP .
PRP MD VB VBN RB RBR if PRP VBD RB VBN VBN IN DT NN .
PRP MD RB VB VBG DT unless PRP VBD JJ IN DT NNS .
If NNS VBP IN NN , PRP VBP NNS .
If PRP VBD PRP , PRP MD VB PRP TO DT NN .
If PRP VBD NN , PRP MD RB VB TO DT NN .
If PRP VBD NN , PRP MD RB VB TO DT NN .
If PRP VBD NN , WP VBD PRP VB .
If PRP VBZ VBG PRP MD VB RP .
If DT NN VBZ JJ JJ NN , PRP MD VB RP DT NN .
If PRP VBP PRP , PRP MD VB PRP .
If PRP VBP IN DT NN , PRP MD VB PRP RP .
If PRP VBP NN IN DT , PRP MD RB VB TO VB PRP .
If PRP VBP TO VB NN PRP MD VB JJR NN .
NNS VBZ JJ TO VB once PRP VBP DT NNS .
VBG PRP VB PRP$ NN IN DT NN , PRP MD VB VBN RP .
Provided PRP VBP RB TO VB NN RB , PRP RB VBP DT NN .
VBG that PRP VBP JJ NN , EX VBZ DT NN WRB PRP MD RB VB TO DT JJ NN .
VBG that_insert EX VBZ DT NN , PRP MD VB DT NN RB .
VBG PRP VB PRP$ NN IN DT NN , PRP MD VB VBN RP .
VBG that_insert PRP VBP RB TO VB NN RB , PRP RB VBP DT NN .
PRP MD VB IN VBG unless PRP VBZ VBN TO VB .
RB RB as PRP VBP JJ , FW MD VB JJ .
DT NN MD VB VBN IN NN unless EX VBZ DT NN .
DT JJ NNS VBP VBG TO VB RB JJ TO VB , VBD that PRP VBP IN PRP VBZ DT JJ NN .
DT JJ NN MD VB DT NNS , VBN that PRP VBZ VBN RP IN DT JJ NN .
Unless NNP VB PRP$ NN PRP VBP VBG TO VB DT NN .
Unless PRP VBP DT NN IN DT NN , PRP VBZ JJ .
Unless PRP VBP RB , PRP MD RB VB DT NN .
PRP MD VB RB if PRP MD RB VB DT NN .
PRP MD VB RB if PRP MD RB VB DT NN .
PRP MD VB NN unless PRP VBD NN .
WP MD VB if EX VBD DT NN .
PRP MD VB IN NNP unless PRP VBP RBR .
PRP MD VB PRP$ NN VBD that_insert PRP VBP PRP RB .
PRP MD VB IN NNP unless PRP VBP JJ .
VBG that_insert PRP VBZ NN CC NN , PRP VBZ RB VB PRP VBZ NN TO VB DT NN .
VBG that PRP VBZ NN CC NN , PRP VBZ RB VB PRP VBZ NN TO VB DT NN .
Although NN VBZ JJ , PRP VBZ NN .
Although PRP VBZ RB JJ , RB PRP VBZ RB JJ .
Although PRP VBD VBN , RB PRP VBD IN VBG .
Although PRP VBD VBN RP , PRP VBD IN VBG .
Although PRP VBD VBN RP , RB PRP VBD IN VBG .
Although PRP MD VB , PRP MD VB .
VBG as PRP VBZ , PRP VBP DT NN .
VBG as PRP VBD , PRP VBD WP VBD DT JJ NN TO VB .
NN though PRP VBZ , PRP VBP DT NN .
NN though PRP VBD , PRP VBD WP VBD DT JJ NN TO VB .
RB though PRP VBZ JJ , PRP VBZ PRP .
VBN that PRP VBP VBN DT NN , PRP MD RB VB VBN .
VBN PRP VBP VBN DT NN , PRP MD RB VB VBN .
VBG that PRP VBP VBN DT NN , PRP MD RB VB VBN .
VBG as PRP VBZ , PRP VBZ JJ NN .
NNP though PRP VBZ , PRP VBZ JJ NN .
However JJ PRP MD VB , PRP MD VB PRP .
RB RB PRP VBP , DT NN MD VB .
RB VBD that_insert DT NN MD VB , DT JJ MD RB VB JJR CC JJR .
PRP VBD DT JJ NN , although DT NNS VBD VBN .
DT NN how JJ PRP VBP VBN , PRP MD RB VB DT NN .
DT NN what VBD , PRP MD RB VB .
DT NN what PRP VBP CC WRB PRP VBP PRP , PRP RB VBZ PRP VBP JJ .
DT NN what PRP VBP , PRP MD RB VB PRP .
DT NN when PRP VBZ , DT NN VBZ VBN .
DT NN which NN PRP VBP , PRP MD VB PRP IN DT NN .
DT NN who PRP VBP , PRP MD VB DT NN .
VB as PRP MD , PRP MD VB .
PRP VBD DT NN though PRP VBD RB VBN RB JJ .
Though PDT DT NN VBD IN PRP , PRP MD RB VB TO PRP$ NN .
Though PRP VBZ RB JJ , RB PRP VBZ RB JJ .
Though PRP VBZ JJ , PRP RB VBZ .
Though PRP VBD DT NN , PRP VBD WP VBD DT JJ NN TO VB .
Though PRP VBD VBN , RB PRP VBD IN VBG .
Though PRP VBD VBN RP , PRP VBD IN VBG .
Though PRP VBZ JJ , PRP VBZ JJ NN .
Though PRP MD VB , PRP MD VB .
VB JJ as PRP MD , PRP RB VBZ JJ TO VB DT NN RB .
PRP MD VB DT NN RB if DT NN VBZ JJ .
PRP MD VB DT NN RB JJ that_insert DT NN VBZ JJ .
PRP MD VB DT NN RB though DT NN VBZ JJ .
PRP MD RB VB VBN RB if PRP VBP CD NNS .
Whatever VBD , PRP MD RB VB .
Whatever PRP VBP , PRP MD RB VB PRP .
Whether PRP NNS CC RB , PRP MD VB RP IN DT VBG NN .
Whether PRP VB PRP CC RB , PRP VBZ JJ .
JJ NN that_insert PRP VBP , PRP MD VB PRP IN DT NN .
Whoever PRP VBP , PRP MD VB DT NN .
PRP VBZ JJ CC PRP VBZ VBG TO VB NN .
PRP VBZ VBG NN CC PRP VBZ RB .
PRP RB JJ VBD PRP DT NN IN NN , CC RB PRP VBD PRP TO VB NNP .
PRP VBD VBG IN DT NNS NN CC RB PRP VBZ .
PRP$ NN VBZ DT NN CC PRP$ NN VBZ DT NN .
PRP VBD DT NN CC PRP VBZ PRP RB JJ .
PRP VBP PRP CC PRP VBZ PRP .
PRP VBP NNS CC PRP IN NN NNS , RB .
PRP VBP VBG NN CC PRP VBP VBG NN .
PRP VBP VBG NN CC PRP VBP VBG NN .
PRP RB JJ VBD PRP CC RB PRP VBD PRP .
PRP RB JJ VBD PRP CC RB PRP VBD PRP .
PRP VBD PRP$ JJS , CC PRP VBD RP IN PRP IN JJ .
NNP VBD PRP$ NN CC PRP VBD TO NN .
NNP RB JJ VBZ NN CC RB PRP VBZ NN .
VB VBG DT NN TO DT JJ , CC PRP MD VB NN .
JJ NN NN VBD that_insert NNP CC PRP VBD NNS .
PRP$ NN VBZ DT NN CC PRP$ NN VBZ DT NN .
PRP$ NN VBZ DT NN CC PRP$ NN VBZ DT NN .
DT MD PRP VB DT NN CC VB PRP VB DT NN .
DT MD PRP VB DT NN CC VB PRP VB DT NNS .
DT VBD that_insert DT JJ NN VBP NN CC VBD PRP$ NN NN IN PRP .
DT VBD that_insert DT JJ NN VBP NN CC VBD PRP$ NNS VBP TO VB IN PRP .
DT VBD that_insert DT JJ NN VBP NN CC VBD PRP$ NNS VBP TO VB IN PRP .
DT VBZ PRP VBD PRP$ NN , CC MD PRP VB RB .
DT VBZ PRP VBD PRP$ NN , CC MD PRP VB RB .
DT PRP VBZ PRP CC PRP VBZ PRP IN NN .
DT NN MD VB PRP CC PRP MD VB PRP IN NN .
RB JJ VBP PRP PRP$ NN , CC RB PRP VBP PRP$ NN .
RB JJ VBD DT NN NN PRP , CC PRP VBD RB VBN PRP RB .
RB RB VBD that_insert PRP VBP TO PRP CC RB PRP VBD PRP .
RB RB VBD that_insert PRP VBP TO PRP CC RB PRP VBD PRP .
RB RB PRP VBZ VBG NN , CC RB PRP$ NN VBZ .
RB JJ PRP VBN TO NN RB , CC RB PRP$ NN VBZ .
RB RB PRP VBP IN NN , CC RB PRP$ NN VBZ .
RB JJ VBZ PRP PRP$ NN , CC RB PRP VBZ PRP$ NN .
RB JJ VBZ PRP PRP$ NN , CC RB PRP VBZ PRP$ NN .
RB RB PRP VBZ DT JJ NN CC PRP VBP VBG PRP$ NN IN DT NN .
RB RB PRP VBZ DT JJ NN CC PRP VBP VBG PRP$ NN IN DT NN .
PRP RB VBD PRP$ NN , PRP MD CC VBP RB .
PRP RB JJ VBZ PRP$ JJ NNS , PRP RB VBZ IN PRP .
DT NN RB JJ VBZ PRP DT NN CC RB PRP VBZ PRP NN .
DT NN POS NN VBZ JJ , CC DT NN POS NN VBZ JJ .
DT NN POS NN VBZ NNP NNP CC DT NN POS NN VBZ JJ .
PRP RB JJ VBP CC RB PRP VBP NN .
DT RB JJ VBZ DT NN , CC PRP MD VB VBG DT NN IN PRP IN DT JJ JJ NNS .
VB PRP$ NN , CC PRP MD VB DT NN .
CD NNS VBD RB JJ IN NNP IN JJ NNS , CC PRP VBD JJ IN DT NNP .
RB PRP VBD , RB , that_insert PRP MD RB VB PRP .
NNS VBP DT JJ NN TO VB IN , CC PRP VBP JJ .
PRP VBZ JJ : RB PRP VBP RB VB PRP .
PRP VBZ JJ while PRP$ JJ NN VBZ JJ .
PRP VBD DT NN , CC PRP MD RB VB VBG PRP .
PRP VBD JJ , RB PRP VBD JJ .
PRP VBD PRP$ NN , CC PRP MD RB VB PRP .
VB RB CC RB PRP MD VB DT JJ NN .
VB RP CC PRP MD VB DT JJ NN .
NNP RB RB PRP MD VB DT JJ NN .
PRP VBP JJ TO VB PRP , CC MD PRP VB PRP DT NN TO DT NN .
PRP VBP RB VB RB , CC PRP VBP DT NN CD .
PRP VBP RB VB NNS CC PRP VBP NN NNS .
PRP VBP RB VB NN CC PRP VBP NN .
PRP VBP RB VB TO VB PRP CC PRP VBP TO .
PRP VBP that_insert NNP CC PRP$ JJ VBZ JJ .
PRP VBP NN while PRP VBZ NN .
PRP MD VB TO VB VBN TO DT NN JJ NN CC PRP VBD TO VB JJ NNS TO VB DT NN .
PRP VBZ DT JJ NN IN JJ NNS TO VB , CC PRP VBZ RB JJ JJ NN NN .
PRP VBZ RB JJ , CC JJ CC JJ .
PRP VBZ JJ , CC PRP VBZ JJ .
PRP RB VBZ but PRP VBZ .
NNP VBZ JJ CC PRP VBZ RB JJ TO VB NNS .
PRP$ NN VBZ DT JJ NN CC PRP$ NNS VBP RB RB VB PRP$ NNS .
PRP$ NN VBZ JJ CC PRP VBP JJ TO VB JJ IN DT NN .
JJ NNS VBG IN CD MD VB CD JJ NNS , CC RB RB CD VBP JJ IN NN .
IN CD JJ NNS VBP JJ IN NN , CC RB DT NN VBZ VBG VBN .
RB RB PRP VBZ CD TO CD NNS TO VB DT NN NN NNS , CC DT VBZ DT RB JJ .
JJ DT NN , RB PRP MD VB .
PRP VBZ DT JJ NN : RB PRP VBP RB VB PRP .
PRP VBZ RB JJ , CC PRP VBZ RB IN PRP$ CD NNS .
PRP MD VB JJ , CC PRP VBD IN NN .
NNP VBD DT NN IN NNP POS NN , CC PRP$ NNS VBP VBN IN PRP$ JJ NN IN DT NNP NNP .
DT NN VBZ RB IN DT NN , CC RB VBZ IN NN .
DT NN VBZ JJ : RB , PRP VBZ JJ PRP .
DT JJ JJ NN IN NNP VBZ RB CD NNS IN NN , CC PRP VBP VBN DT CD NN NN IN DT IN CD NN NNS IN DT NNP .
DT NN VBN IN NNS IN JJ NNP IN NNS , CC RB PRP MD RB VB DT .
EX VBP RB CD JJ NNS IN NNP , CC PRP RB VBP RB CD NN IN DT NN POS NN NN .
NNP NNS VBP RB IN JJ NNS , CC NNP VBD JJ TO VB DT NNS .
PRP VBP NN IN DT NN IN DT NNPS , CC IN DT NN PRP VBZ JJR .
PRP VB DT NN while PRP VB DT NN .
PRP MD VB RB , CC PRP MD VB .
MD PRP VB PRP TO NN CC VB PRP VB TO NN RB JJ .
NNP that_insert PRP VBP PRP TO VB PRP CC VB PRP VBP TO VB PRP PRP .
VBP PRP VB RB CC VBP PRP DT NN RB .
CC NNP VBZ VBG CC PRP$ NNS VBP .
CC NNP VBZ VBG CC PRP$ NNS VBP .
NNP MD VB JJ IN NN CC PRP MD RB VB VBN VBN .
PRP MD VB RB , RB PRP MD RB VB DT NN .
PRP VBP JJ CC PRP MD VB DT JJ NN .
MD PRP RB VB RB CC VB PRP that_insert VBP VBN RP .
PRP MD RBR VB RB , RB PRP MD VB DT NN .
PRP MD VB DT NN IN PRP$ NN CC PRP MD VB PRP .
PRP VB RP , CC RB PRP MD VB JJ .
PRP MD VB PRP NN CC FW MD RB VB PRP .
NNP RB VBZ JJ , IN PRP VBZ TO VB PRP$ NN IN NN .
NN VBD DT NN , IN DT NN VBD VBN IN NN .
JJ NN VBZ JJR NN CC JJR NNS : RB PRP VBZ PRP$ NN TO VB PRP .
PRP VBD DT NN , for PRP VBD RB JJ .
PRP VBD DT NN RB , for PRP VBD VBN NNS IN DT NN .
PRP VBD NN CC NN , RB , PRP VBD JJ TO VB DT NNS NN .
PRP VBP VBN DT NN TO VB , IN PRP VBP TO VB RB .
PRP VBP JJ , for PRP VBZ JJ .
PRP VBD TO PRP , for PRP VBD VBN PRP .
PRP VBP TO VB RB RB , for PRP VBP NNS IN NN TO VB .
PRP VBZ DT NN , IN PRP VBD PRP IN JJ .
PRP VBZ NN RB , RB DT NN MD VB JJR .
PRP VBZ NN IN NN IN DT NN NN , IN DT NN PRP VBP IN NN IN NN .
PRP VBZ NN RB , RB DT NN MD VB JJR .
PRP VBZ RB VBN RB , IN DT VBZ DT NN IN JJ NN VBG .
PRP VBZ RB DT RB JJ NN , IN PRP RB VBP PRP$ NN .
NNP VBD JJ , IN PRP VBD RB VB TO NN .
RBS JJ JJ JJ NNS RB VBP IN NNS IN PRP$ NN , so DT NN IN DT NN VBZ JJ NNS IN JJ NN .
PRP MD VB RB , for PRP$ NN VBZ VBG IN PRP .
DT NNPS VBP RB VBN JJ NN IN NN NN , IN PRP MD VB IN DT IN DT NN IN VBG JJ NN .
DT NN VBZ VBN IN NN RB , IN PRP VBP VBG NNS .
DT NN VBD JJ so PRP VBD IN PRP$ NN .
DT NN VBD RP RB DT NN , so PRP VBD RB VB DT JJ NN .
PRP VBD PRP TO VB , IN PRP VBD .
PRP VBP VBN NN , IN EX VBZ DT NN NN .
PRP VBD PRP TO VB , IN PRP VBP .
PRP VBP IN PRP$ NN NN , IN PRP MD VB JJ NNS IN NN TO VB DT NN IN PRP .
PRP VBP VBN TO VB JJ IN NNS , for PRP RB VBZ TO DT JJ NNS .
PRP VBZ RBR than PRP VBZ JJ IN PRP .
PRP VBZ DT RBR NN than PRP VBD NN .
PRP VBZ RBR RB than PRP$ NN VBZ .
PRP VBD RBR JJ than PRP VBD JJ NN .
PRP VBD RB IN RB as PRP VBD VBN RB .
PRP VBP PRP DT JJR , DT JJR PRP VBP PRP .
PRP VBZ RB RB JJ as PRP VBP .
NNP VBD RBR than NNS VBP .
NNP VBZ RBR IN DT NN that_insert PRP VBZ .
PRP VBZ RBR than PRP$ NN VBZ .
DT VBZ RB JJ DT NN as PRP MD VB .
DT NN VBD RBR RB than NN VBP .
DT NN VBZ RB JJ as PRP VBD RB JJ .
DT JJR DT NN VBZ VBN , DT JJR DT NN MD VB .
DT JJR PRP VBD , DT JJR NN PRP VBP .
DT NN VBZ RB RB JJ as PRP VBD JJ .
DT NNS IN NNP VBP RB RB JJ as PRP VBP IN NNP .
EX VBD JJR NNS than PRP VBD VBN .
PRP VBP RBR than PRP VBP JJ IN PRP .
PRP VBP VBN RB JJR NN DT NN than PRP VBD DT NN .
PRP VBD TO VB JJ NN RB RB IN VB NN .
NNP VBZ RB JJ IN JJ NN as PRP VBZ JJ IN JJ NN .
NNP VBP TO DT NNS as PRP MD VB VBN IN .
PRP VBZ as if PRP VBD DT NN .
PRP VBD RP PRP$ NN as if PRP VBD VBN VBN .
PRP RB VBD DT NN as though PRP VBD JJ .
PRP VBZ as if PRP VBD VBN VBN IN NN .
PRP VBZ as if PRP VBZ JJ .
PRP VBZ as though PRP VBD VBN VBN IN NN .
PRP VBD PRP$ NNS as if PRP VBD VBG TO VB NN .
PRP VBZ PRP as if PRP VBP DT NN .
PRP VBD RB RB IN VBG DT NN .
PRP VBD RB IN RB VBG DT NN .
PRP VBP as PRP MD VB JJ IN NN .
PRP VBP VBN PRP as PRP VBP .
PRP VBP DT JJ NN as if PRP VBD NN .
PRP VBD as if EX MD VB DT JJ NN .
PRP VBZ as if DT NN MD VB RP RB RB .
NNP VBD RB VB as PRP VBD .
DT NNS VBZ VBN as if PRP VBD VBN IN NN .
PRP RB VBP DT NNS as if PRP RB VBD .
PRP RB VBP DT NNS as though PRP RB VBD .
PRP VBD DT NN as if PRP VBD PRP$ JJ .
PRP MD VB as PRP$ NNS VBP PRP .
IN DT NNS VBP DT NNS , whose magnificence DT NN RB VBZ IN DT NN .
NNS , whose JJ NN VBZ JJ , MD VB CC VB IN JJ JJ NNS .
As VBZ VBN TO DT NNP , NNP NNP VBZ DT JJ JJ NN .
As PRP DT VBP , DT NN VBZ NN .
PRP VBD TO VB PRP$ NN IN PRP , as VBD RB DT NN .
PRP VBZ TO VB IN NNP , which PRP VBZ RB VB .
PRP VBZ VBN IN NN , as PRP RB VBD .
PRP MD VB JJ NNS , IN which case PRP MD VB TO VB VBN RP .
PRP VBD DT NN , which VBD PRP .
PRP MD VB RP DT NN IN NNP , when PRP MD VB JJ .
PRP$ NN RB VBD RP IN DT JJ JJ NNS , IN where PRP MD VB NN CC NNS .
PRP$ NN , who VBZ PRP RB JJ , VBZ JJ IN PRP .
PRP VBP DT NN , who VBZ VBG DT NN .
PRP VBD TO NN IN CD , IN when PRP VBD VBG IN DT NN .
JJ VBP that_insert PRP VBD DT NNS POS NNP NNP , IN WDT JJ JJ NNS VBP VBN DT NN .
NNP VBZ DT JJ NN IN DT NN , DT NN IN which VBZ CD NNS IN NN .
NNP NNP , IN whom PRP VBP VBN DT NN , VBZ DT JJ NN .
PRP$ NN , who VBZ VBN IN DT NNP NNP NNP PDT PRP$ NN , VBZ VBG JJ NN .
PRP$ NN , who VBZ RB JJ , VBZ IN EX MD VB DT NNS DT NN .
PRP$ NN , who VBD DT JJ JJ , VBD DT JJ NN .
NNP , whom PRP VBD IN NNP , VBZ RB RB IN NNP .
NNP VBZ , as PRP VBP , DT JJ NN IN NNP .
NNP , which VBD VBN IN NNP , VBZ VBG RBR CC RBR JJ .
PRP VBZ RB JJ , which PRP MD RB VB .
PRP VBZ DT NN , which PRP VBP RB .
PRP VBD RB JJ IN DT NNS , which PRP$ NN RB VBD .
NNP NNP , whom NN VBZ RB JJ , VBZ CD IN DT JJS NNS IN PRP$ NN .
DT NN , whose NNS VBZ DT NN , VBZ RB JJ .
DT NN VBZ RB JJ , which VBD PRP RB JJ .
DT JJ NN VBZ DT NN , who VBZ IN DT NN .
DT NN where NN CC NNS VBP .
DT NN VBZ DT NN , which VBZ PRP JJ IN NNS TO VB .
DT CD NNS VBD JJ IN DT NN , as VBD VBN RB .
DT CD NN VBD RB VBN , which IN NN PRP VBD .
EX VBP CD NNS IN DT JJ NN , JJS IN which VBP JJ .
PRP VBD TO VB , where PRP VBD IN CD NNS .
NNP , which VBZ DT JJ JJ , VBZ JJ NNS .
PRP MD VB RP DT NN IN JJ NN , when PRP MD RB VB RB JJ .
NNP NNP VBD CD NNS IN DT NN , IN which NN PRP VBD NN .
When RB VBN IN NN , WDT PRP RB VBD , PRP MD VB DT IN VBG CC VBG .
NNP , which PRP VBD JJ NN , VBZ DT JJ JJ NN .
JJ NNS VBP VBN TO VB how PRP MD VB PRP$ NNS CC NNS IN NNP .
NNP NNP VBZ that_insert DT JJ NN NN VBZ VBG .
NNP VBZ RP whether PRP VBP IN PRP .
VB PRP RB VBN that DT NN IN PRP$ NN MD VB VBN .
PRP VBD that PRP VBD VBG TO PRP .
PRP VBD if PRP VBD VBN TO NNP .
PRP VBD PRP where PRP MD VB NNP .
PRP VBD whose NNS was DT JJS .
PRP VBD RP whether PRP MD VB CC VB DT NN .
PRP VBZ VBG when MD PRP VB DT difficult NN .
PRP VBD that PRP MD VB RP TO DT NNP RB .
PRP VBD PRP that PRP VBD VBG IN DT JJ NN .
PRP VBD PRP that PRP MD VB TO DT NN DT JJ NN .
PRP VBD that PRP MD VB TO DT NN DT JJ NN .
PRP VBD PRP that PRP MD VB PRP IN DT JJ NN .
PRP VBP JJ that PRP MD VB PRP .
PRP VBP JJ that PRP VBP VBN DT NN .
PRP VBP JJ that PRP VBP VBN PRP RB JJ .
PRP VBP JJ that_insert PRP MD VB DT NN .
PRP VBD PRP whether PRP VBD VBN PDT DT NN PRP CC IN PRP VBD VBN DT NN .
PRP VBD if PRP VBD RB VB TO NN NN .
PRP VBP RB VB whether CC RB PRP MD VB .
PRP VBP RB VB if EX MD VB DT NN DT RBR .
PRP VBP RB VB that_insert PRP VBZ DT JJ NN .
PRP VBP PRP DT NN that PRP VBP RB VBN TO DT NN .
PRP VBP VBN RP that PDT DT NNS IN DT NN VBP VBN VBN RP .
PRP VBP VBN PRP DT NN that PRP VBP NNS .
PRP VBD that_insert PRP VBD IN PRP VBD VBN RB .
PRP VBP PRP JJ that PRP VBP RB IN JJ NN DT NN .
PRP VBP PRP RB JJ that PRP VBZ RP VBG RB DT NN .
PRP VBD PRP JJ that PRP MD VB DT NN IN RB CD NNS .
PRP VBP TO VB if PRP VBD PRP$ NN NN .
NN VBD whether PRP MD VB DT NN .
NN IN PRP VBZ where DT JJ NNS MD VB VBN .
PRP$ NN VBD that NNP VBZ DT JJ NN IN DT NN .
PRP$ NN VBD PRP that NN VBZ RB RBR IN NN .
UH VB PRP when PRP MD VB DT NN .
UH VB PRP what PRP VBD IN DT NN NN .
PRP VBZ that_insert DT JJ NN NN VBZ RB RB JJ .
VB PRP which VBD PRP VBP IN .
DT NN MD VB PRP what DT JJS NNS VBP .
DT NN VBZ that_insert NN VBZ RB .
PRP MD VB VBN NN whether PRP MD VB DT NN CC RB .
PRP DT VBP PRP JJ that PRP VBP DT JJ NN IN DT NN .
PRP VBP VBG RP whether PRP VBP NNS IN PRP$ NN .
PRP VBD whether TO VB RB .
PRP VBP that_insert PRP VBP VBN DT NN .
PRP VBP PRP that PRP MD VB IN PRP .
PRP VBP PRP JJ that PRP VBD DT NN TO NN .
NNP VBZ JJR NNS IN NN that_insert DT NN VBZ JJ .
NN VBP DT NN , so that DT NN VBD VBN IN NN .
PRP VBD RB IN NN that_insert PRP MD VB DT NN .
PRP VBD VBN IN NN DT NN MD VB PRP .
PRP VBZ JJ IN NN that PRP$ NN MD VB JJ .
PRP VBP VBG DT NN lest PRP MD VB DT JJ NN .
PRP VBP VBG PRP that lest PRP MD VB DT NN .
PRP VBZ VBN DT NN IN NN that PRP MD VB DT NN NNS .
DT NN VBD DT NN TO VB RP IN DT NNS so that PRP MD VB PRP .
DT NNS VBN lest PRP MD VB DT VBG NN .
DT NN VBD PRP$ NN IN NN that DT NNS IN DT NN MD VB JJR RB .
PRP VBP VBN DT JJ NN so that PRP MD VB TO DT NNS RB .
PRP MD VB RBR so that PRP MD VB VBN IN DT .
PRP VBP PRP JJR so DT NN MD VB PRP .
IN DT NN , PRP VBD as if PRP MD RB VB IN DT JJ NN .
NNP VBZ RB RB what PRP VBD TO VB .
NNP CC JJ NN VBZ what PRP VBP IN .
PRP VBZ VBN what PRP VBD TO VB CD NNS RB .
PRP VBZ RB RB what PRP VBD .
PRP$ JJ NN VBD whether NNP NNP VBD VBN RB .
PRP$ JJ NN VBD that DT NN VBP .
PRP$ NN VBZ that PRP MD VB JJ .
PRP VBZ RB because PRP VBZ RB VB PRP .
PRP VBZ RB as DT VBZ WP PRP VBP , IN PRP VBD VBG RB IN RB .
PRP VBD as if PRP VBD VBG TO VB .
PRP$ NN VBZ that PRP MD VB PRP DT NN IN RB .
PRP$ NN VBZ who MD VB RP NN IN DT NNP .
PRP$ NN VBZ that PRP MD VB JJ NN .
PRP$ NN VBZ that PRP MD VB PRP .
NNP NNP VBZ when PRP MD VB .
RB PRP VBD as though PRP VBD VBN NNP IN NNS .
NNP VBZ RB what PRP VBD TO VB .
PRP VBZ VBN where PRP VBD NN IN DT NN .
DT VBZ what PRP VBP TO VB .
DT VBZ what PRP VBP RB IN .
DT VBZ where PRP RB VBD PRP .
DT VBZ where PRP VBP JJ .
DT VBZ why PRP VBP TO DT NN .
DT VBZ because PRP VBD TO VB PRP$ JJ NN IN PRP$ NN .
DT VBZ where PRP VBD VBN .
DT VBD when PRP VBD CD .
DT NN VBZ whether PRP VBD NN .
DT NN VBZ that PRP VBZ RB RB VB .
DT NN VBZ whether PRP MD VB PRP DT NN .
DT NN VBZ how PRP MD VB PRP .
DT NN VBZ when PRP MD VB DT NN NN .
DT NN VBZ who MD VB DT NN .
DT NN VBZ who PRP MD VB TO VB PRP .
DT NN VBZ whether DT NN VBZ VBG IN PRP .
DT NN VBZ whether DT NN VBZ JJ VBG .
DT NN VBZ whether PRP MD VB IN PRP .
DT NN VBZ who PRP MD VB .
DT NN VBZ whether PRP MD VB JJ TO VB PRP .
DT NN VBZ that PRP VBP VBN PRP$ NN .
DT NN VBZ that PRP VBP JJ IN NNS .
DT VBZ what PRP VBP .
DT VBZ why PRP VBP JJ .
PRP VBP RB who PRP VBD PRP VBD .
As PDT DT NNS VBD JJ , PRP VBD RP .
As PRP VBD VBG , PRP VBD IN NN .
PRP MD RB VB VBN PRP , for PRP VBD RB RB .
PRP VBD RB VB because PRP VBD JJ .
PRP VBP PRP because PRP VBP PRP .
VBG that PRP VBZ VBG , PRP MD VB RB .
Since DT NN VBZ VBN , VB POS VB IN DT NN .
Since PRP VBP DT NN , PRP MD RB VB PRP .
Since PRP VBP DT NN , PRP MD RB VB PRP .
Since PRP VBP RB JJ , PRP MD RB VB PRP IN PRP .
DT MD VB JJ because DT NNP NN VBZ RB VBN TO VB VBN IN NN IN NNP .
DT NN VBZ RB JJ because PRP VBZ JJ .
DT NN VBD because PRP VBD VBN RB .
DT NN VBD because PRP VBD VBN RB .
PRP VBD IN NN because PRP VBD JJR .
PRP MD VB DT NNS because DT NN RB VBZ .
PRP MD RB VB JJ RB because DT NNS VBP JJ IN PRP .
DT NN VBZ RB JJ that PRP MD RB VB PRP .
NNP VBZ RB JJ that PRP MD RB VB DT NN IN PRP DT RB .
PRP VBD JJ JJ NNS that PRP MD RB VB DT NN .
PRP VBZ RB JJ NN that PRP MD RB VB TO DT NN IN PRP .
PRP VBD RB JJ that PRP MD RB VB TO VB DT NN .
PRP VBD RB JJ that PRP MD RB VB DT NN .
PRP VBD so that PRP MD RB VB .
PRP VBZ JJ JJ NN that PRP MD VB TO VB TO DT NN .
PRP VBD PDT DT JJ NN that NN VBD TO VB NN .
PRP VBD PDT DT JJ NN that DT IN PRP VBD TO VB PRP RB .
NNP VBZ RB RB RB that PRP RB RB VBP PRP .
PRP$ NN VBZ RB RB VBN that PRP MD VB JJ NNS .
DT NN VBD RB JJ that DT IN PRP VBD TO VB PRP RB .
DT NN VBZ RB JJ NNS that PRP VBP TO VB NN IN PRP .
DT CD VBD RB JJ IN NN that PRP RB VBD NNS IN DT JJ .
PRP VBP JJ NN NNS that PRP RB VB PRP IN JJ NN .
How DT VBD VBZ RB JJ TO NN .
PRP VBZ DT NN that PRP VBD RB VB .
PRP VBZ DT NN that PRP MD RB VB .
PRP VBZ RB VB PRP whether PRP VBP CC RB .
PRP VBZ RB VB whether PRP MD VB CC RB .
PRP VBD that PRP VBD IN WDT NN .
PRP VBZ JJ that PRP MD VB RB IN PRP$ NN .
PRP VBZ JJ NN that DT NN VBZ RB DT NN .
PRP VBZ JJ that PRP MD VB RB IN DT NNP .
PRP VBZ DT NN that NNP MD VB VBN DT NN .
PRP VBZ VBN that NNP NNP VBZ VBN IN NNP .
PRP VBD PRP that NNP VBD RB VB NN WRB PRP VBD .
PRP VBD RB JJ that PRP VBD TO VB TO PRP .
That PRP MD VB VBZ JJ .
That PRP MD VB NNS VBZ DT NN .
That PRP MD RB VB TO DT NN DT NN VBZ JJ .
DT NN that_insert MD VB RP VBZ JJ .
That PRP VBD DT NN VBZ DT NN .
That PRP VBP RB JJ VBZ PRP .
That PRP VBD RB VB TO DT NN VBD DT NN .
That PRP MD VB DT NN VBZ JJ .
What PRP VBZ VBP DT NNS .
What PRP VBP VBZ NN .
What PRP VBP VBZ JJR NN .
Whatever PRP VBD VBZ JJ .
Whatever PRP VBD VBD JJ .
When PRP MD VB RB VBZ IN DT NN .
When PRP MD VB VBZ DT NN .
When PRP MD VB VBZ RB VBN .
When DT NN VBZ TO VB RP VBZ RB VBN VBN .
When PRP MD VB VBZ RB VBN VBN JJ .
When PRP MD VB NN MD VB VBN RB .
Where DT NN MD VB VBN VBZ RB RB VBN .
Where PRP MD VB PRP VBZ DT NN .
Whether PRP VBZ VBG CC RB VBZ RB VB RB RB .
Whether DT NN MD VB VBN RP VBZ RB VBN VBN RB .
Whether PRP MD VB PRP VBD DT NN .
Which NN MD VB VBZ RB JJ .
NNP VBZ that_insert DT NN MD VB VBN .
Whoever VBZ TO VB IN DT NN MD VB DT NN .
NNP NNP VBZ DT NN IN NN NN .
PRP VBD DT NN TO PRP$ NN .
PRP VBZ JJ .
PRP MD VB PRP VB .
PRP MD VB PRP DT JJ NN .
PRP VBD NN .
PRP MD VB PRP$ NNS TO VB DT NNS .
NNP VBZ RB VBG IN JJ NNS TO VB DT NN VBN TO VB NNS TO NNP .
NNP NNP VBZ IN NNP NNP NNP .
NN VBD .
NNP NNP VBD DT NN IN DT NN NN .
DT NN VBZ DT JJ NN VBN IN DT NN IN NN .
DT NN VBZ VBN DT NN IN PRP$ JJ JJ NN NN .
DT NN VBZ DT JJ NN TO VB NNS TO DT NNS CC NNS .
DT NN MD VB JJ IN NN IN DT RB JJR NN .
DT NNS VBD VBN IN DT NNP NNP CC NNP NNP .
DT NN VBZ DT NN POS NN , NN CC NN .
PRP MD VB DT JJ NN IN DT NN IN CC CC CC CD NNS .
PRP VBP JJ .
DT NN VBZ JJ , DT NN VBZ JJ CC DT NN VBZ JJ .
PRP RB VBD NNS .
As DT NN VBD IN DT NN VBD JJR .
Before PRP VBP PRP$ NN , VB PRP VB RB CD NNS TO DT JJ NN .
IN DT NN that_insert DT NN VBD , NNS IN NNS VBD NNS .
IN DT NN PRP VBD RB , PRP VBD VBN DT NN .
VB DT NN before PRP VBP DT NN .
DT NN PRP VBD TO VB , PRP MD VB IN PRP .
PRP VBD RB VBN RB when PRP VBD DT JJ NN IN PRP$ NN .
PRP VBD DT RBR VBN PRP$ NN than DT NNS VBD VBG .
PRP VBD RB VBD PRP$ NN when DT NN VBD IN PRP .
PRP VBD IN DT NN IN VBG when NN VBD IN DT NN .
PRP VBD RB VBG when DT NN VBD CC PRP$ NN VBD RP .
PRP MD VB RB till DT NN VBZ .
PRP VBD RB VB TO NN until PRP$ NN VBD RB .
PRP VBP VBN IN NNP since PRP VBD .
PRP VBP VBN DT NN IN JJ NNS IN PRP since PRP VBD RB IN RB .
PRP VBD IN TO VB DT NN when DT NN VBD .
PRP VBD JJ IN NN when DT NN VBD .
PRP VBD RB VBG DT NN when PRP VBD IN PRP$ NN .
PRP VBD TO NN after PRP VBD PRP$ NN .
PRP VBZ RB JJR TO VB NNS when PRP VBP JJ NNS .
PRP VBD TO VB RB as PRP VBD NN .
NNP VBD NN while PRP$ NNS VBD VBG PRP$ NN .
NNP VBD PRP RB JJ when PRP VBD PRP$ NNS IN NNP NNP .
PRP VBP , PRP VBD VBG TO VB IN DT NN RB when PRP$ NN VBD VBZ IN NN .
PRP VBD RB VBN PRP$ NN when PRP$ NN VBD PRP TO VB VBG DT NN NN .
DT NN VBD NNP when PRP VBD PRP$ NN .
DT NNS VBP RBR when NNP VBZ .
DT NN PRP VBD DT NN , PRP VBN TO DT NN .
DT JJ NN that_insert PRP VBD PRP , PRP VBD VBG NN .
DT NNS VBD VBG PRP$ JJ NN when DT NN VBD RP .
DT JJ NN VBD IN DT JJ NNS when PRP RB VBD PRP .
PRP VBD IN TO VB when PRP VBD RP .
PRP VBD IN TO VB when PRP VBD TO VB .
When PRP VBP , PRP$ NNS MD VB NN IN PRP .
When PRP VBD IN DT NN , PRP VBD TO VB DT NN IN PRP .
When PRP VBD RP DT NN , PRP VBD TO NN .
When DT NN VBD , NNS VBD VBN VBN .
While NNP VBD VBG PRP$ NN , NNP NNP VBD TO VB PRP .
While PRP$ NN VBD VBG DT NN , PRP VBD VBG NN .
PRP MD RB VB NN till PRP VBP PRP$ NN .
PRP MD RB VB NN until PRP VBP PRP$ NN .
PRP VBP JJR DT NN that_insert PRP VBP PRP .
PRP MD VB TO VB PRP$ NNS CC PRP$ NN when PRP VBP DT NN .
RB PRP VBD , PRP VBD RB VBN .
VB IN DT NNS IN NNS where PRP VBZ JJ .
VB RP where PRP VBD IN .
PRP VBD PRP TO VB where DT NN VBZ JJ .
PRP VBZ JJ wherever PRP VBZ .
PRP VBD PRP where PRP MD VB CC VB .
PRP VBD PRP$ NN where PRP VBD RP NN .
PRP MD VB DT NN where PRP MD VB PRP .
VB PRP where PRP MD VB PRP .
VB DT NN where PRP VBP DT NN .
VB wherever PRP VBP .
PRP VBD where PRP VBD VBN IN NN CD NNS RB .
PRP MD RB VB where EX VBZ DT JJ NN .
PRP VBP TO VB where NN VBZ TO VB .
PRP MD VB where PRP MD VB NN .
PRP VBD RB , where PRP VBD NN .
Where DT NNP NNP IN NNP VBZ , RB DT NNS VBP JJ .
Where DT NN VBZ , PRP MD VB NN .
Where EX VBZ DT NN , EX VBZ DT NN .
Where EX VBZ DT NN , EX VBZ DT NN .
Where EX VBZ NN , EX VBZ NN .
Where EX VBZ DT NN , NN VBZ JJ CC JJ .
Where EX VBZ JJ EX VBZ JJ TO VB NN .
NNP that_insert PRP VBP PRP MD VB VBG IN PRP .
VB PRP VB , PRP MD VB RB JJ NN RB RB as PRP VBP JJ TO VB .
IN DT NN , DT NN MD VB where PRP VBZ CC WRB PRP VBZ .
PRP MD VB RB that_insert PRP VBP .
