VB PRP$ NN IN PRP VBP VBG .
VB PRP PRP$ NN IN PRP MD VB TO PRP$ NN DT NN .
PRP VBD DT NN WRB PRP VBD .
PRP VBZ VBN DT NN WRB DT NN VBD RB IN NN .
PRP VBD DT NN IN DT NN VB VBN .
PRP VBD TO NNP POS NN IN DT NN NNS VBP DT NN .
PRP VBP VBN IN NNP VBG IN DT NN IN PRP MD RB VB JJ TO VB PRP DT NN .
PRP VBP VBN TO DT NN IN PRP VBD JJ TO VB DT .
PRP MD VB PRP$ NN IN PRP MD VB DT JJ NN .
PRP VBD DT NN IN PRP VBD RB .
PRP VBP VBN DT NN IN NNP VBD VBN DT NN .
PRP VBP DT NN WRB PRP MD VB RB .
PRP VBP DT NN WRB PRP MD VB RB .
PRP VBD DT NN IN PRP$ NN VBD VBN .
PRP$ NN WRB PRP MD VB IN NN IN PRP VBZ RB VBN VBN .
PRP$ NN VBD PRP DT NN WRB PRP MD VB DT NN .
RB VBD DT NN IN PDT DT NNS MD VB DT NNS .
DT NN IN PRP VBD RB VBD NN VBN NN .
DT NN IN DT NN VBZ VBN VBZ RB VB PRP VBD VBN .
DT NN VBD DT NN IN DT NNS MD VB DT NN IN RB .
DT NN IN PRP MD VB DT NN RB IN VBG VBZ RB JJ .
DT NN IN PRP MD VB DT JJ NNS TO VB DT JJ NNS VBD VBN NN .
DT NN IN PRP MD VB RB JJ NN VBZ TO VB VBN .
DT NN IN DT NN IN DT NN NN MD VB IN NN VBZ RB VBN .
DT NN IN PRP MD VB IN DT NN VBD VBN IN JJ NN .
DT NN WP MD VB DT NN VBZ NN .
EX VBD DT NN IN NNP MD VB VBN IN DT NN .
PRP VBP JJ IN DT NN IN DT NN VBZ IN NNS .
PRP VBD DT NN IN PRP VBP DT NN .
PRP VBD VBN IN DT NN IN DT NN VB VBN .
PRP VBD VBN IN DT NN IN PRP VBD JJ .
PRP MD VB DT NN IN DT NNS NN MD VB VBN IN NN .
PRP DT VB RP WRB PRP VBD DT NN IN PRP$ NN VBD DT JJ NN .
PRP VBP RB VBG DT NN IN PRP VBZ JJ .
PRP VBP RB VBG IN DT NN IN PRP VBZ IN JJ .
PRP VBP RB VB DT NN WRB DT VBZ DT JJS NN .
PRP VBP RB RB VBN DT NN WRB PRP VBP VBG TO VB PRP$ JJ NN .
NNP VBD IN PRP VBD VBN RB .
DT JJ NN DT VBZ NN CC JJ JJ NNS .
PDT DT NNS IN PRP$ NNS VBP PRP IN PRP$ NN MD VB VBN RP .
IN DT JJ NN PRP VBD RB JJ NN IN PRP MD VB .
NNP VBZ DT NN WDT VBZ VBN IN JJS NNS .
PRP VBZ RB DT NN IN NN WP MD VB RP IN PRP$ NNS .
PRP VBZ DT NN NN IN PRP VBP RB VBD TO .
PRP VBZ DT NN WP$ NNS VBZ DT NN .
PRP VBZ DT JJ NN WP$ NNS VBP RB IN JJ .
PRP VBZ DT JJ NN IN PRP VBP .
PRP VBZ DT JJ NN IN DT NNS WDT VBZ VBN TO VB .
PRP VBZ DT JJ NN IN PRP WDT VBZ JJ .
PRP VBZ TO VB NNS WDT VBP VBN IN JJ NNS .
PRP VBD DT NN IN WP PRP VBD CD NNS .
PRP RB VBD RP DT JJS NN , WDT RB VBD CD NNS .
PRP RB VBD RP DT JJ NNS WDT VBD TO VB VBN RB IN VBG .
PRP VBD NN WDT VBD PRP JJ .
PRP VBD DT JJ NN WDT MD VB RP DT NNS .
PRP VBD VBG DT NNS CC NNS WDT VBD DT NN .
PRP WP VBZ JJ NNS RBS .
PRP$ NN TO PRP VBD RB DT JJ IN PRP VBD RB VBN .
RB VBZ DT NN IN PRP VBD VBN PRP IN .
PRP MD VB DT NN WP$ NNS VBZ RP IN DT NN .
PRP VBP RB VBN IN NN WDT MD VB IN NN TO PRP .
PRP VBP DT NN TO WDT PRP VBZ .
PRP VBP RB VB DT NN WRB PRP VBZ JJ NN .
PRP VBP JJ IN JJ NNS WP VBP PRP$ NNS IN DT NN IN NN .
PRP VBD PRP JJ NNS WDT PRP VBD DT NN IN .
PRP VBP RB VBN PDT DT NN IN PRP VBD RP .
PRP VBP DT NN IN PRP MD VB .
PRP VBP DT NNS IN PRP MD VB NN .
PRP VBP DT NNS WDT VBP VBN IN NN NN .
PRP RB VBD JJ NNS IN PRP VBZ .
PRP RB VBD IN DT NN WP$ NNS VBZ VBN IN .
PRP VBP DT NNS WRB PRP VBD IN DT NN IN PRP$ NNS .
PRP RB VBP DT NN WRB PRP RB VBD TO DT NN .
PRP VBD DT NN WP$ NN VBZ VBN DT IN DT NN .
PRP VBD DT NN WRB DT NN IN NNS VBD VBN .
PRP VBD RP IN NN IN DT NN WRB PRP MD VB DT NN .
PRP MD RB VB DT CD NNS IN PRP VBD IN DT JJ JJ NN .
IN PRP VBP RB IN DT NN , PRP MD RB VB RP DT NN IN WDT PRP VBD RB .
VBZ PRP DT NN WDT VBZ NNS .
VBZ PRP DT NN WDT VBZ NNS .
PRP VBZ IN DT NN IN PRP RB VBD .
PRP VBD DT JJS NN IN PRP RB VBD .
NNP NNP VBZ RB DT NN WP PRP VBP TO VB .
NNP NNP VBZ DT NN WP PRP VBD RP IN DT NN .
NN VBZ VBG TO VB DT NN WP$ JJ NN VBZ IN DT NN NNS .
RB RB IN NNP VBD DT JJ NN WDT VBD IN DT NNP .
NNP VBZ NN IN PRP RB VBP VBG .
VBG TO DT NN WRB PRP VBD TO VB MD VB DT VBG NN .
VB RP RB DT NNS WDT PRP VBP RB VB NNP TO VB .
PRP VBD VBN IN DT JJ NN , WRB EX VBD DT VBG NN .
DT VBZ DT NN WP PRP VBP .
DT VBZ DT JJ NN WDT VBD IN NN DT NN IN RB .
DT VBZ DT NN WRB PRP VBP NNP .
DT VBZ DT NN WRB PRP MD VB RB .
DT NN CC PRP$ NN WDT VBD VBN IN DT JJ NN VBD VBN TO DT NN NN .
DT NNS WP VBP VBG NN VBP IN NNP CD .
DT NN WP$ NN VBZ VBN MD RB VB VBN .
DT NN VBZ IN DT NNS WRB NNS VBD NNS .
DT NN IN PRP VBD VBG IN VBD JJ .
DT NN WDT VBZ NNS VBZ RB RB IN RB .
DT NN WDT PRP VBD TO VB JJ NN VBD RB JJ IN DT .
DT JJ NN IN PRP VBP TO VB RB VBZ TO VB DT NN .
DT NN WP DT NN RB VBZ VBZ PRP$ NN .
DT NN IN WP PRP VBD VBN VBG IN CD NNS RB VBD PRP$ NNS CC VBD .
DT NN , WDT PRP VBP RB , VBD RB JJ .
DT NN IN PRP VBD IN PRP NN VBZ RB JJ .
DT NN WP VBZ VBG NNS IN PRP$ NN VBZ DT NN .
DT NN WP VBD VBD DT NN IN NNP .
DT NN WP PRP VBD DT NN TO VBZ DT NN IN NNS .
DT NN WP PRP VBD RB RB VBZ PRP$ JJ NN .
DT NN WP$ NN PRP VBP RP VBZ JJ NN TO VBG PRP$ VBG NNS .
DT NN IN NNS WDT VBP TO VB DT NN DT NN VBZ CD CD .
DT NNS WP VBD IN NNP IN DT CD NNS VBD NNP NNP VBD DT IN PRP$ NN IN NNP .
DT NN IN PRP VBD TO PRP VBZ RB JJ .
DT NN WP PRP VBP TO VB VBZ VBN .
DT NN , WP$ NNS VBZ RB JJ , VBZ JJ IN DT NN .
DT NN VBP VBN IN DT DT NN NNS WP PRP VBP .
DT NN WP PRP VBP VBG IN VBZ VBN .
DT NN WRB PRP VBZ JJ VBZ IN PRP$ NN VBD JJ .
DT NN WRB PRP VBD VBN VBZ JJ TO PRP .
DT NN WRB PRP VBD RB VB DT NN VBD IN PRP$ NNP VBD RB RB JJ .
DT NN WP$ NNS VBZ RB VBZ NN .
DT NN WDT PRP RB VBD RP VBZ RB JJ .
DT NN WDT VBZ IN NNP VBZ NN .
DT NN WDT PRP VBD VBN IN VBD RB JJ .
DT NN WRB PRP VBD RB RB VBD .
DT NNS VBD RP DT JJ NN WRB PRP VBD RP CC VBD .
EX VBZ DT NN WP VBZ TO VB PRP .
EX VBZ DT NN IN PRP MD VB .
EX VBD JJ NNS WRB PRP VBD DT NN IN PRP .
PRP VBD RP PDT DT NNS WDT VBD JJ IN DT JJ NN .
DT VBZ CD IN DT JJ NNS WRB DT IN PRP$ NN MD RB VB VBN RB .
DT VBZ DT NN WP PRP VBD NN IN RB .
DT VBZ DT NN WDT PRP VBD NN .
DT VBZ DT NN , IN WDT DT NNS VBP VBN .
DT VBZ DT NN WDT VBZ VBN IN DT NN IN NNS .
DT VBZ DT JJ NN IN PRP VBP VBN VBG IN .
DT WP VBP TO VB TO DT NN MD VB IN DT NN NN IN CD NN NN .
DT WP VBD VBN IN DT NNS RB VBD VBD .
NNP VBD DT NN WRB DT NNS POS NNP IN NNP VBD VBN .
NN PRP MD VB RB DT NN WDT PRP VBD IN .
NNP IN PRP$ JJ VBN NN , WDT MD VB IN DT NN JJ NN .
NNP VBZ DT JJ NN IN WDT JJS NN VBP .
PRP MD VB TO VB DT JJ NN WP PRP VBP RB VBN IN .
PRP VBP VBN IN DT NN WDT MD VB DT NN JJ CD NNS DT NN .
PRP MD RB VB NNS IN DT NN , CC DT VBZ RB NN WDT MD VB VBN IN .
PRP VBD IN DT NNS CC NNS IN PRP VBD IN NN .
WDT IN DT NNS IN PRP VBD NN VBD VBN IN NNP .
MD PRP VB VB DT JJ NNS IN PRP VBP .
NN PRP VBD DT JJ NN WP VBD VBN PRP$ NN .
NN PRP VBD DT NN WDT VBD IN NNP .
PRP VBP PRP DT NN WRB PRP VBD DT NN .
PRP MD VB DT NN VBG IN PRP MD VB PRP IN PRP$ JJ NN .
PRP MD VB TO VB VBN IN PRP$ NNS VBP VBN .
PRP MD VB TO VB VBG IN PRP$ NNS VBP VBN .
PRP MD VB VBG IN PRP$ NNS VBP VBN .
PRP MD VB RB VBD DT NN VBZ IN PRP .
PRP MD VB RB VBG DT NN VBZ IN PRP .
PRP MD VB VBN RB RBR IN PRP VBD RB VBN VBN IN DT NN .
PRP MD RB VB VBG DT IN PRP VBD JJ IN DT NNS .
IN NNS VBP IN NN , PRP VBP NNS .
IN PRP VBD PRP , PRP MD VB PRP TO DT NN .
IN PRP VBZ RB JJ , PRP MD VB JJ TO VB PRP$ NN POS NN NN RBR .
IN PRP VBD NN , PRP MD RB VB TO DT NN .
IN PRP VBD NN , PRP MD RB VB TO DT NN .
IN PRP VBZ VBG PRP MD VB RP .
IN DT NN VBZ JJ JJ NN , PRP MD VB RP DT NN .
IN PRP VBP PRP , PRP MD VB PRP .
IN PRP VBP IN DT NN , PRP MD VB PRP RP .
IN PRP VB PRP$ NN IN DT JJ NN , DT NN NN MD RB VB PRP .
IN PRP VBP NN IN DT , PRP MD RB VB TO VB PRP .
IN PRP VBP TO VB NN PRP MD VB JJR NN .
IN PRP VBP TO VB NN PRP MD VB JJR NN .
NNS VBZ JJ TO VB IN PRP VBP DT NNS .
VBG PRP VB PRP$ NN IN DT NN , PRP MD VB VBN RP .
IN PRP VBP RB TO VB NN RB , PRP RB VBP DT NN .
VBG IN PRP VBP JJ NN , EX VBZ DT NN WRB PRP MD RB VB TO DT JJ NN .
VBG EX VBZ DT NN , PRP MD VB DT NN RB .
VBG PRP VB PRP$ NN IN DT NN , PRP MD VB VBN RP .
VBG PRP VBP RB TO VB NN RB , PRP RB VBP DT NN .
PRP MD VB IN VBG IN PRP VBZ VBN TO VB .
RB RB IN PRP VBP JJ , FW MD VB JJ .
DT NN MD VB VBN IN NN IN EX VBZ DT NN .
DT JJ NNS VBP VBG TO VB RB JJ TO VB , VBD IN PRP VBP IN PRP VBZ DT JJ NN .
DT JJ NN MD VB DT NNS , VBN IN PRP VBZ VBN RP IN DT JJ NN .
IN PRP VBZ , DT NN MD VB VBN .
IN PRP VBP DT NN IN DT NN , PRP VBZ JJ .
IN PRP VBP RB , PRP MD RB VB DT NN .
PRP MD VB RB IN PRP MD RB VB DT NN .
PRP MD VB RB IN PRP MD RB VB DT NN .
PRP MD VB NN IN PRP VBD NN .
WP MD PRP VB IN PRP VBP DT NN IN NN .
WP MD PRP VB IN PRP VBP DT NN IN NN .
WP MD VB IN EX VBD DT NN .
PRP MD VB IN NNP IN PRP VBP RBR .
PRP MD VB PRP$ NN VBD PRP VBP PRP RB .
PRP MD VB RB JJ IN PRP VBZ PRP VB IN DT NN .
VBG PRP VBZ NN CC NN , PRP VBZ RB VB PRP VBZ NN TO VB DT NN .
VBG IN PRP VBZ NN CC NN , PRP VBZ RB VB PRP VBZ NN TO VB DT NN .
IN NN VBZ JJ , PRP VBZ NN .
IN PRP VBZ RB JJ , RB PRP VBZ RB JJ .
IN PRP VBD VBN , RB PRP VBD IN VBG .
IN PRP VBD VBN RP , RB PRP VBD IN VBG .
IN PRP MD VB , PRP MD VB .
MD PRP VB PRP IN PRP MD VB CC RB NN .
VBG IN PRP VBZ , PRP VBP DT NN .
VBG IN PRP VBD , PRP VBD WP VBD DT JJ NN TO VB .
NN IN PRP VBZ , PRP VBP DT NN .
NN IN PRP VBD , PRP VBD WP VBD DT JJ NN TO VB .
RB IN PRP VBZ JJ , PRP VBZ PRP .
VB IN PRP VBD , PRP MD RB VB DT NN RB RB .
VBN IN PRP VBP VBN DT NN , PRP MD RB VB VBN .
VBN PRP VBP VBN DT NN , PRP MD RB VB VBN .
VBG IN PRP VBP VBN DT NN , PRP MD RB VB VBN .
VBG PRP VBP VBN DT NN , PRP MD RB VB VBN .
NNP IN PRP VBZ , PRP VBZ JJ NN .
WRB JJ PRP MD VB , PRP MD VB PRP .
WRB JJ PRP VBP VBN , PRP MD RB VB DT NN .
RB RB PRP VBP , DT NN MD VB .
RB VBD DT NN MD VB , DT JJ MD RB VB JJR CC JJR .
PRP VBD DT JJ NN , IN DT NNS VBD VBN .
PRP VBD DT JJ NN , IN DT NNS VBD VBN .
DT NN WP PRP VBP CC WRB PRP VBP PRP , PRP RB VBZ PRP VBP JJ .
DT NN WP PRP VBP , PRP MD RB VB PRP .
DT NN WRB PRP VBZ , DT NN VBZ VBN .
VB IN PRP MD , PRP MD VB .
PRP VBD DT NN IN PRP VBD RB VBN RB JJ .
IN PDT DT NN VBD IN PRP , PRP MD RB VB TO PRP$ NN .
IN PRP VBZ JJ , CC PRP VBZ JJ .
IN PRP VBZ JJ , PRP RB VBZ .
IN PRP VBD DT NN , PRP VBD WP VBD DT JJ NN TO VB .
IN PRP VBD VBN RP , PRP VBD IN VBG .
IN PRP VBD VBN RP , RB PRP VBD IN VBG .
IN PRP MD VB , PRP MD VB .
PRP MD VB DT NN RB IN DT NN VBZ JJ .
PRP MD VB DT NN RB JJ DT NN VBZ JJ .
PRP MD VB DT NN RB IN DT NN VBZ JJ .
PRP MD RB VB VBN RB IN PRP VBP CD NNS .
WDT PRP VBP , PRP MD RB VB PRP .
WRB PRP VBZ , DT NN VBZ VBN .
IN PRP NNS CC RB , PRP MD VB RP IN DT VBG NN .
IN PRP VB PRP CC RB , PRP VBZ JJ .
JJ NN PRP VBP , PRP MD VB PRP IN DT NN .
IN PRP VBP DT NN , PRP VBP RB VB DT NN .
WP PRP VBP , PRP MD VB DT NN .
PRP MD VB TO VB DT NN IN PRP VBP JJ CC JJ .
PRP VBZ JJ CC PRP VBZ VBG TO VB NN .
PRP VBZ VBG NN CC PRP VBZ RB .
PRP RB JJ VBD PRP DT NN IN NN , CC RB PRP VBD PRP TO VB NNP .
PRP RB JJ VBZ JJ CC RB PRP VBZ JJ .
PRP VBD VBG IN DT NNS NN CC RB PRP VBZ .
PRP$ NN VBZ DT NN CC PRP$ NN VBZ DT NN .
PRP VBD DT NN CC PRP VBZ PRP RB JJ .
PRP VBP PRP CC PRP VBZ PRP .
PRP VBP NNS CC PRP IN NN NNS , RB .
PRP VBP VBG NN CC PRP VBP VBG NN .
PRP VBP VBG NN , PRP$ NN VBZ VBG NN CC PRP$ NN VBZ VBG NN .
PRP VBP VBG NN CC PRP VBP VBG NN .
PRP RB JJ VBD PRP CC RB PRP VBD PRP .
PRP VBD PRP$ JJS , CC PRP VBD RP IN PRP IN JJ .
NNP VBD PRP$ NN CC PRP VBD TO NN .
NNP RB JJ VBZ NN CC RB PRP VBZ NN .
VB VBG DT NN TO DT JJ , CC PRP MD VB NN .
JJ NN NN VBD NNP CC PRP VBD NNS .
PRP$ NN VBZ DT NN CC PRP$ NN VBZ DT NN .
PRP$ NN VBZ DT NN CC PRP$ NN VBZ DT NN .
DT MD PRP VB DT NN CC VB PRP VB DT NN .
DT MD PRP VB DT NN CC VB PRP VB DT NNS .
DT VBD DT JJ NN VBP NN CC VBD PRP$ NN NN IN PRP .
DT VBD DT JJ NN VBP NN CC VBD PRP$ NNS VBP TO VB IN PRP .
DT VBD DT JJ NN VBP NN CC VBD PRP$ NNS VBP TO VB IN PRP .
DT VBZ PRP VBD PRP$ NN , CC MD PRP VB RB .
DT VBZ PRP VBD PRP$ NN , CC MD PRP VB RB .
DT PRP VBZ PRP CC PRP VBZ PRP IN NN .
DT NN MD VB PRP CC PRP MD VB PRP IN NN .
RB JJ VBP PRP PRP$ NN , CC RB PRP VBP PRP$ NN .
RB JJ VBD DT NN NN PRP , CC PRP VBD RB VBN PRP RB .
RB RB VBD PRP VBP TO PRP CC RB PRP VBD PRP .
RB RB VBD PRP VBP TO PRP CC RB PRP VBD PRP .
RB RB PRP VBZ VBG NN , CC RB PRP$ NN VBZ .
RB JJ PRP VBN TO NN RB , CC RB PRP$ NN VBZ .
RB RB PRP VBP IN NN , CC RB PRP$ NN VBZ .
RB JJ VBZ PRP PRP$ NN , CC RB PRP VBZ PRP$ NN .
RB JJ VBZ PRP PRP$ NN , CC RB PRP VBZ PRP$ NN .
RB RB PRP VBZ DT JJ NN CC PRP VBP VBG PRP$ NN IN DT NN .
RB RB PRP VBZ DT JJ NN CC PRP VBP VBG PRP$ NN IN DT NN .
PRP RB JJ VBZ JJ CC RB PRP VBZ JJ .
PRP RB JJ VBZ PRP$ JJ NNS , PRP RB VBZ IN PRP .
DT NNS IN NNS VBP VBG PRP NN IN VBG CC VBG JJ NN , CC DT VBZ RB JJ VBG DT NN IN NNS .
DT NN RB JJ VBZ PRP DT NN CC RB PRP VBZ PRP NN .
DT NN POS NN VBZ JJ , CC DT NN POS NN VBZ JJ .
DT NN POS NN VBZ NNP NNP CC DT NN POS NN VBZ JJ .
DT RB JJ VBZ DT NN , CC PRP MD VB VBG DT NN IN PRP IN DT JJ JJ NNS .
VB PRP$ NN , CC PRP MD VB DT NN .
PRP VBD VBG DT NNS , CC PRP RB VBD RB IN NN .
CD NNS VBD RB JJ IN NNP IN JJ NNS , CC PRP VBD JJ IN DT NNP .
RB PRP VBD , RB , PRP MD RB VB PRP .
NNS VBP DT JJ NN TO VB IN , CC PRP VBP JJ .
NNP VBZ DT RB JJ CC PRP VBZ RB JJ .
PRP VBZ JJ : RB PRP VBP RB VB PRP .
PRP VBZ JJ IN PRP$ JJ NN VBZ JJ .
PRP VBD DT NN , CC PRP MD RB VB VBG PRP .
PRP VBD JJ , RB PRP VBD JJ .
PRP VBD PRP$ NN , CC PRP MD RB VB PRP .
VB RB CC RB PRP MD VB DT JJ NN .
VB RP CC PRP MD VB DT JJ NN .
NNP RB RB PRP MD VB DT JJ NN .
PRP VBP RB IN NN RB CC PRP VBP DT NNS TO VB .
PRP VBP RB JJ IN JJ CC PRP VBP DT JJ NN .
PRP VBP JJ TO VB PRP , CC MD PRP VB PRP DT NN TO DT NN .
PRP VBP RB VB RB , CC PRP VBP DT NN CD .
PRP VBP RB VB NNS CC PRP VBP NN NNS .
PRP VBP RB VB TO VB PRP CC PRP VBP TO .
PRP VBP VBN , CC PRP MD VB RB .
PRP VBP NNP CC PRP$ JJ VBZ JJ .
PRP MD VB TO VB VBN TO DT NN JJ NN CC PRP VBD TO VB JJ NNS TO VB DT NN .
PRP VBZ RB JJ , CC JJ CC JJ .
PRP VBZ JJ , CC PRP VBZ JJ .
PRP RB VBZ CC PRP VBZ .
NNP DT NN VBZ RB JJ , CC PRP VBP TO VB .
PRP$ NN VBZ DT JJ NN CC PRP$ NNS VBP RB RB VB PRP$ NNS .
PRP$ NN VBZ JJ CC PRP VBP JJ TO VB JJ IN DT NN .
IN CD JJ NNS VBP JJ IN NN , CC RB DT NN VBZ VBG VBN .
JJ DT NN , RB PRP MD VB .
PRP VBZ DT JJ NN : RB PRP VBP RB VB PRP .
PRP VBZ JJ CC JJ , CC RB NNS VBP PRP .
PRP VBZ RB JJ , CC PRP VBZ RB IN PRP$ CD NNS .
PRP MD VB JJ , CC PRP VBD IN NN .
NNP VBD DT NN IN NNP POS NN , CC PRP$ NNS VBP VBN IN PRP$ JJ NN IN DT NNP NNP .
DT NN VBZ JJ : RB , PRP VBZ JJ PRP .
DT NNP NNP CC JJ JJ NNS RB RB VBD RP NNS IN NN , CC NNP VBZ RB VBD .
DT JJ JJ NN IN NNP VBZ RB CD NNS IN NN , CC PRP VBP VBN DT CD NN NN IN DT IN CD NN NNS IN DT NNP .
DT NN VBN IN NNS IN JJ NNP IN NNS , CC RB PRP MD RB VB DT .
DT NN VBN IN NNS IN NNP IN NNS , CC PRP MD RB VB DT NN .
EX VBP RB CD JJ NNS IN NNP , CC PRP RB VBP RB CD NN IN DT NN POS NN NN .
NNP NNS VBP RB IN JJ NNS , CC NNP VBD JJ TO VB DT NNS .
PRP VBP DT NN IN DT VBG NNS CC DT VBZ VBN IN PRP$ NN TO VB IN NN NNS .
PRP VB DT NN IN PRP VB DT NN .
PRP MD VB RB , CC PRP MD VB .
MD PRP VB PRP TO NN CC VB PRP VB TO NN RB JJ .
NNP PRP VBP PRP TO VB PRP CC VB PRP VBP TO VB PRP PRP .
VBP PRP VB RB CC VBP PRP DT NN RB .
CC NNP VBZ VBG CC PRP$ NNS VBP .
CC NNP VBZ VBG CC PRP$ NNS VBP .
PRP VBD JJ DT NN , RB PRP MD VB VBN NN IN DT NNS VB .
NNP MD VB JJ IN NN CC PRP MD RB VB VBN VBN .
DT NN MD VB JJ CC PRP MD VB JJ .
PRP MD VB RB , RB PRP MD RB VB DT NN .
PRP VBP JJ CC PRP MD VB DT JJ NN .
PRP MD RBR VB RB , RB PRP MD VB DT NN .
PRP MD VB DT NN IN PRP$ NN CC PRP MD VB PRP .
PRP MD VB RB , RB PRP MD VB DT NN .
PRP VBD IN NN IN DT NN , RB PRP MD VB VBN PRP DT NN .
NNP RB VBZ JJ , IN PRP VBZ TO VB PRP$ NN IN NN .
NN VBD DT NN , IN DT NN VBD VBN IN NN .
PRP VBD DT NN , IN PRP VBD RB JJ .
PRP VBD DT NN RB , IN PRP VBD VBN NNS IN DT NN .
PRP VBP VBN DT NN TO VB , IN PRP VBP TO VB RB .
PRP VBP JJ , IN PRP VBZ JJ .
PRP VBD TO PRP , IN PRP VBD VBN PRP .
PRP VBZ DT NN , IN PRP VBD PRP IN JJ .
PRP VBZ NN , IN DT NNS VBP VBG .
PRP VBZ NN IN NN IN DT NN NN , IN DT NN PRP VBP IN NN IN NN .
PRP VBZ NN RB , RB DT NN MD VB JJR .
PRP VBZ RB DT RB JJ NN , IN PRP RB VBP PRP$ NN .
NNP VBD JJ , IN PRP VBD RB VB TO NN .
RBS JJ JJ JJ NNS RB VBP IN NNS IN PRP$ NN , IN DT NN IN DT NN VBZ JJ NNS IN JJ NN .
PRP MD VB RB , IN PRP$ NN VBZ VBG IN PRP .
DT NNPS VBP RB VBN JJ NN IN NN NN , IN PRP MD VB IN DT IN DT NN IN VBG JJ NN .
DT NN VBZ VBN IN NN RB , IN PRP VBP VBG NNS .
DT NN VBD JJ IN PRP VBD IN PRP$ NN .
DT NN VBD RP RB DT NN , IN PRP VBD RB VB DT JJ NN .
PRP VBD PRP TO VB , IN PRP VBD .
PRP VBP IN PRP$ NN NN , IN PRP MD VB JJ NNS IN NN TO VB DT NN IN PRP .
PRP MD RBR VB DT NN IN PRP , IN PRP VBZ VBG TO VB .
DT NN VBZ DT RBR , DT JJR NN PRP VBZ .
PRP VBZ DT RBR NN IN PRP VBD NN .
PRP VBZ RBR RB IN PRP$ NN VBZ .
PRP VBD RB IN RB IN PRP VBD VBN RB .
PRP VBP PRP DT JJR , DT JJR PRP VBP PRP .
PRP VBD IN JJ NNS IN PRP VBP VBN TO VB VBN .
PRP VBZ RB RB JJ IN PRP VBP .
NNP VBZ RBR IN DT NN PRP VBZ .
PRP VBZ RBR IN PRP$ NN VBZ .
PRP VBP RB RB RB IN PRP VBZ VBD RP .
DT VBZ RB JJ DT NN IN PRP MD VB .
DT NN VBD RBR RB IN NN VBP .
DT NN VBZ RB JJ IN PRP VBD RB JJ .
DT JJR DT NN VBZ , DT JJR DT NN VBZ .
DT JJR DT NN VBZ VBN , DT JJR DT NN MD VB .
DT JJR PRP VBP , DT JJR PRP VBP PRP$ NN .
DT JJR PRP VBD , DT JJR NN PRP VBP .
DT NNS IN NNP VBP RB RB JJ IN PRP VBP IN NNP .
DT NN VBD RB VB RB RB IN PRP VBD .
DT NN IN NN VBP JJR RP IN PRP VBD TO VB .
EX VBD JJR NNS IN PRP VBD VBN .
PRP VBP RBR IN PRP VBP JJ IN PRP .
PRP VBP VBN RB JJR NN DT NN IN PRP VBD DT NN .
PRP VBD TO VB JJ NN RB RB IN VB NN .
NNP VBZ RB JJ IN JJ NN IN PRP VBZ JJ IN JJ NN .
NNP VBP TO DT NNS IN PRP MD VB VBN IN .
IN NN VBZ TO NN , RB NN VBZ TO NN .
PRP VBZ RB IN PRP VBD DT NN .
PRP VBD RP PRP$ NN RB IN PRP VBD VBN VBN .
PRP RB VBD DT NN RB IN PRP VBD JJ .
PRP VBZ RB IN PRP VBZ JJ .
PRP VBD PRP$ NNS RB IN PRP VBD VBG TO VB NN .
PRP VBZ PRP RB IN PRP VBP DT NN .
PRP VBD RB IN RB VBG DT NN .
PRP VBP IN PRP MD VB JJ IN NN .
PRP VBP VBN PRP IN PRP VBP .
PRP VBP DT JJ NN RB IN PRP VBD NN .
PRP VBD RB IN EX MD VB DT JJ NN .
PRP VBZ RB IN DT NN MD VB RP RB RB .
NNP VBD RB VB IN PRP VBD .
DT NNS VBZ VBN RB IN PRP VBD VBN IN NN .
DT JJ NN VBZ RB IN PRP VBZ DT JJ NN .
PRP RB VBP DT NNS RB IN PRP RB VBD .
PRP RB VBP DT NNS RB IN PRP RB VBD .
PRP VBD DT NN RB IN PRP VBD PRP$ JJ .
PRP MD VB IN PRP$ NNS VBP PRP .
IN DT NNS VBP DT NNS , WP$ NN DT NN RB VBZ IN DT NN .
IN VBZ VBN TO DT NNP , NNP NNP VBZ DT JJ JJ NN .
IN PRP DT VBP , DT NN VBZ NN .
VBP PRP VBN DT NN NN , WP$ JJ NN VBZ NN JJ .
PRP VBD TO VB PRP$ NN IN PRP , IN VBD RB DT NN .
PRP VBZ DT NN , WP VBZ DT NN .
PRP VBZ TO VB IN NNP , WDT PRP VBZ RB VB .
PRP MD VB JJ NNS , IN WDT NN PRP MD VB TO VB VBN RP .
PRP VBD IN PRP VBD RB VBN PRP RB , WDT VBD RB JJ .
PRP$ NN , WP VBZ PRP RB JJ , VBZ JJ IN PRP .
PRP VBD TO NN IN CD , IN WRB PRP VBD VBG IN DT NN .
IN PRP$ NN EX VBP CD NNS , DT JJS IN WP VBZ NNP NNP .
JJ VBP PRP VBD DT NNS POS NNP NNP , IN WDT JJ JJ NNS VBP VBN DT NN .
NNP VBZ DT JJ NN IN DT NN , DT NN IN WDT VBZ CD NNS IN NN .
PRP$ NN , WP VBZ VBN IN DT NNP NNP NNP PDT PRP$ NN , VBZ VBG JJ NN .
PRP$ NN , WP VBZ RB JJ , VBZ IN EX MD VB DT NNS DT NN .
PRP$ NN , WP VBD DT JJ JJ , VBD DT JJ NN .
NNP , WP PRP VBD IN NNP , VBZ RB RB IN NNP .
NNP VBZ , IN PRP VBP , DT JJ NN IN NNP .
NNP , WDT VBD VBN IN NNP , VBZ VBG RBR CC RBR JJ .
PRP VBZ RB JJ , WDT PRP MD RB VB .
PRP VBZ DT NN , WDT PRP VBP RB .
DT NN , WDT PRP$ NN VBD PRP IN NNP , VBZ RB JJ IN VBG PRP$ NNP NNP .
DT NN VBZ RB JJ , WDT VBD PRP RB JJ .
DT NN , WDT PRP VBD JJ NN , VBZ RB JJ .
DT JJ NN VBZ DT NN , WP VBZ IN DT NN .
DT NN WRB NN CC NNS VBP .
DT NN , WP$ NNS VBZ JJ , VBZ JJ IN DT JJ NNS .
DT NN , WP$ NNS VBZ RB JJ , VBZ JJ IN DT NN .
DT NN VBZ DT NN , WDT VBZ PRP JJ IN NNS TO VB .
DT NNPS , WDT VBZ RB JJ RB TO VB RP , VBD JJ IN IN DT CD NNS .
DT CD NNS VBD JJ IN DT NN , IN VBD VBN RB .
DT CD NN VBD RB VBN , WDT IN NN PRP VBD .
DT NN NNS , WDT PRP VBD CD NNS RB , VBP RB VBN DT NN .
PRP VBD TO VB , WRB PRP VBD IN CD NNS .
DT NN VBD VBN IN DT NNP PRP , WP VBD DT JJ NN IN NNP NNP .
NNP , WDT VBZ DT JJ JJ , VBZ JJ NNS .
NNP NNP VBD CD NNS IN DT NN , IN WDT NN PRP VBD NN .
NNP , WDT PRP VBD JJ NN , VBZ DT JJ JJ NN .
JJ NNS VBP VBN TO VB WRB PRP MD VB PRP$ NNS CC NNS IN NNP .
NNP VBZ RP IN PRP VBP IN PRP .
VB PRP RB VBN IN DT NN IN PRP$ NN MD VB VBN .
PRP VBD IN PRP VBD VBG TO PRP .
PRP VBD IN PRP VBD VBN TO NNP .
PRP VBD PRP WRB PRP MD VB NNP .
PRP VBD WP$ NNS VBD DT JJS .
PRP VBZ VBG WRB MD PRP VB DT JJ NN .
PRP VBD PRP IN PRP VBD VBG IN DT JJ NN .
PRP VBD IN PRP MD VB TO DT NN DT JJ NN .
PRP VBD PRP IN PRP MD VB PRP IN DT JJ NN .
PRP VBP JJ IN PRP MD VB PRP .
PRP VBP JJ IN PRP VBP VBN DT NN .
PRP VBP JJ PRP MD VB DT NN .
PRP VBD IN PRP VBD RB VB TO NN NN .
PRP VBP RB VB IN EX MD VB DT NN DT RBR .
PRP VBP RB VB WP PRP MD VB RP .
PRP VBP RB VB NNS MD VB .
PRP VBP VBN RP IN PDT DT NNS IN DT NN VBP VBN VBN RP .
PRP VBD PRP VBD IN PRP VBD VBN RB .
PRP VBP PRP JJ IN PRP VBP RB IN JJ NN DT NN .
PRP VBD PRP JJ IN PRP MD VB DT NN IN RB CD NNS .
PRP VBP TO VB IN PRP VBD PRP$ NN NN .
NNP NNP VBZ DT JJ NN IN DT NNP NNP NNP VBZ TO VB DT JJ NN IN NN VBG NNS IN DT NN .
NN IN PRP VBZ WRB DT JJ NNS MD VB VBN .
PRP$ NN VBD PRP IN NN VBZ RB RBR IN NN .
UH VB PRP WRB PRP MD VB DT NN .
UH VB PRP WP PRP VBD IN DT NN NN .
NNS VBP VBN IN DT NN VBZ IN DT NN .
PRP VBZ DT JJ NN NN VBZ RB RB JJ .
VB PRP WDT VBD PRP VBP IN .
DT NN VBZ NN VBZ RB .
DT NN VBD IN DT NN VBZ IN DT NN NN .
PRP MD VB VBN NN IN PRP MD VB DT NN CC RB .
PRP DT VBP WP PRP VBD TO VB JJ .
PRP DT VBP PRP JJ IN PRP VBP DT JJ NN IN DT NN .
PRP VBP VBG RP IN PRP VBP NNS IN PRP$ NN .
PRP VBD IN TO VB RB .
PRP VBD WP PRP VBD VBN TO VB JJ .
PRP VBP PRP VBP VBN DT NN .
PRP VBP PRP IN PRP MD VB IN PRP .
NNP VBZ JJR NNS IN NN DT NN VBZ JJ .
NN VBP DT NN , RB IN DT NN VBD VBN IN NN .
PRP VBD RB IN NN PRP MD VB DT NN .
PRP VBD VBN IN NN DT NN MD VB PRP .
PRP VBD DT NN RB IN NN IN PRP MD VB PRP .
PRP VBP VBG DT NN IN PRP MD VB DT JJ NN .
PRP VBP VBG PRP IN IN PRP MD VB DT NN .
PRP VBP DT NN IN PRP MD VB PRP .
PRP VBZ VBN DT NN IN NN IN PRP MD VB DT NN NNS .
PRP VBD RB RB IN PRP MD RB VB PRP$ NNS .
DT NN VBD DT NN TO VB RP IN DT NNS RB IN PRP MD VB PRP .
DT NNS VBN IN PRP MD VB DT VBG NN .
PRP VBP VBN DT JJ NN RB IN PRP MD VB TO DT NNS RB .
IN DT NN , PRP VBD RB IN PRP MD RB VB IN DT JJ NN .
NNP VBZ RB RB WP PRP VBD TO VB .
NNP CC JJ NN VBZ WP PRP VBP IN .
PRP VBZ RB RB WP PRP VBD .
PRP$ JJ NN VBD IN NNP NNP VBD VBN RB .
PRP$ JJ NN VBD IN DT NN VBP .
PRP$ NN VBZ IN PRP MD VB JJ .
PRP VBZ RB IN PRP VBZ RB VB PRP .
PRP VBZ RB RB IN PRP VBD JJ .
PRP VBZ RB IN DT VBZ WP PRP VBP , IN PRP VBD VBG RB IN RB .
PRP VBD RB IN PRP VBD VBG TO VB .
PRP$ NN VBZ IN PRP MD VB PRP DT NN IN RB .
PRP$ NN VBZ IN PRP MD VB VBG NNS RB RB .
PRP$ NN VBZ WP MD VB RP NN IN DT NNP .
PRP$ NN VBZ IN PRP MD VB PRP .
NNP NNP VBZ WRB PRP MD VB .
NNP VBZ RB WP PRP VBD TO VB .
DT VBZ WP PRP VBP TO VB .
DT VBZ WP PRP VBP RB IN .
DT VBZ WRB PRP RB VBD PRP .
DT VBZ WRB PRP VBP JJ .
DT VBZ WRB PRP VBD RB VB .
DT VBZ WRB PRP VBP TO DT NN .
DT VBZ IN PRP VBD TO VB PRP$ JJ NN IN PRP$ NN .
DT VBZ WRB PRP VBD VBN .
DT VBD WRB PRP VBD CD .
DT NN VBZ IN PRP VBD NN .
DT NN VBZ IN PRP MD VB PRP DT NN .
DT NN VBZ WRB PRP MD VB PRP .
DT NN VBZ WRB PRP MD VB DT NNS PRP VBP .
DT NN VBZ WRB PRP MD VB DT NN NN .
DT NN VBZ WP MD VB DT NN .
DT NN VBZ IN DT NN VBZ VBG IN PRP .
DT NN VBZ IN DT NN VBZ JJ VBG .
DT NN VBZ IN PRP MD VB IN PRP .
DT NN VBZ WP PRP MD VB .
DT NN VBZ IN PRP MD VB JJ TO VB PRP .
DT NN VBZ IN PRP VBP JJ IN NNS .
DT VBZ WP PRP VBP .
DT VBZ WRB PRP VBP JJ .
PRP VBP RB WP PRP VBD PRP VBD .
IN PDT DT NNS VBD JJ , PRP VBD RP .
IN PRP VBD VBG , PRP VBD IN NN .
IN PRP VBP DT NN , PRP MD RB VB PRP .
PRP VBP PRP IN PRP VBP PRP .
PRP VBP RB IN PRP VBP TO VB DT NN NN IN DT NN .
RB IN PRP VBP RB , PRP MD RBR VB .
RB IN PRP VBP RB RB , PRP MD VB .
VBG IN PRP VBZ VBG , PRP MD VB RB .
IN DT NN VBZ VBN , VB POS VB IN DT NN .
IN PRP VBP DT NN , PRP MD RB VB PRP .
IN PRP VBP RB JJ , PRP MD RB VB PRP IN PRP .
DT NN VBZ RB JJ IN PRP VBZ JJ .
DT NN VBD IN PRP VBD VBN RB .
DT NN VBD IN PRP VBD VBN RB .
PRP VBD IN NN IN PRP VBD JJR .
PRP MD VB DT NNS IN DT NN RB VBZ .
PRP MD RB VB JJ RB IN DT NNS VBP JJ IN PRP .
PRP VBZ PDT DT JJ NN IN PRP MD RB VB PRP .
DT NN VBZ RB JJ IN PRP MD RB VB PRP .
NNP VBZ RB JJ IN PRP MD RB VB DT NN IN PRP DT RB .
PRP VBD JJ JJ NNS IN PRP MD RB VB DT NN .
PRP VBZ RB JJ NN IN PRP MD RB VB TO DT NN IN PRP .
PRP VBZ RB JJ IN PRP MD VB TO NN .
PRP VBZ RB RB IN DT NN MD VB PRP .
PRP VBD RB JJ IN PRP MD RB VB DT NN .
PRP VBD PDT DT JJ NN IN NN VBD TO VB NN .
PRP VBD PDT DT JJ NN IN DT IN PRP VBD TO VB PRP RB .
PRP$ NN VBZ RB RB VBN IN PRP MD VB JJ NNS .
DT NN VBD RB JJ IN DT IN PRP VBD TO VB PRP RB .
DT NN VBZ RB JJ NNS IN PRP VBP TO VB NN IN PRP .
EX VBZ RB JJ DT NN IN NN IN DT NN NN VBZ VBN .
DT CD VBD RB JJ IN NN IN PRP RB VBD NNS IN DT JJ .
PRP VBZ DT NN IN PRP VBD RB VB .
PRP VBZ DT NN IN PRP MD RB VB .
PRP VBZ RB VB PRP IN PRP VBP CC RB .
PRP VBZ RB VB DT NN IN PRP VBZ CC RB .
PRP VBZ RB VB IN PRP MD VB CC RB .
PRP VBD IN PRP VBD IN WDT NN .
PRP VBZ DT NN TO PRP WRB PRP DT VBD .
PRP VBZ JJ IN PRP MD VB RB IN PRP$ NN .
PRP VBZ JJ NN IN DT NN VBZ RB DT NN .
PRP VBZ JJ IN PRP MD VB JJ TO VB .
PRP VBZ JJ IN PRP MD VB RB IN DT NNP .
PRP VBZ VBN TO PDT DT JJ NNS IN JJ NNS .
PRP VBZ TO VB VBN IN PRP MD VB PRP JJ CC JJ .
PRP VBD DT NN IN PRP MD VB PRP .
PRP VBD RB JJ IN PRP VBD TO VB TO PRP .
IN PRP MD VB VBZ JJ .
IN PRP MD VB NNS VBZ DT NN .
IN PRP MD RB VB TO DT NN DT NN VBZ JJ .
DT NN MD VB RP VBZ JJ .
IN PRP VBD DT NN VBZ DT NN .
IN PRP VBP RB JJ VBZ PRP .
IN PRP VBD RB VB TO DT NN VBD DT NN .
IN PRP MD VB DT NN VBZ JJ .
WP PRP VBZ VBP DT NNS .
WP PRP VBP TO VB VBZ DT .
WP PRP VBP VBZ NN .
WP PRP VBP VBZ JJR NN .
WDT PRP VBD VBD JJ .
WRB PRP MD VB RB VBZ IN DT NN .
WRB DT NN VBZ TO VB RP VBZ RB VBN VBN .
WRB PRP MD VB NN MD VB VBN RB .
WRB DT NN MD VB VBN VBZ RB RB VBN .
IN DT NN MD VB VBN RP VBZ RB VBN VBN RB .
NNP IN PRP VBN IN DT NN VBZ RB DT NN .
WDT NN MD VB VBZ RB JJ .
WP VBD DT NN VBZ DT NN .
NNP VBZ DT NN MD VB VBN .
WP VBZ TO VB IN DT NN MD VB DT NN .
NNP NNP VBZ DT NN IN NN NN .
NNP VBZ TO VB DT JJR NN IN VBG NNS IN JJ NN .
PRP VBD PRP DT NNS .
PRP VBZ JJ .
PRP VBZ NNP RB JJ .
PRP MD VB PRP DT JJ NN .
PRP VBD NN .
PRP VBD DT NN JJ .
PRP MD VB PRP$ NNS TO VB DT NNS .
NNP MD VB DT JJ NN NN IN JJ NNS CC JJR NNS .
NNP VBZ PRP JJ .
NNP VBZ DT NN .
PRP$ NN MD VB NN .
NNP NNP VBZ IN NNP NNP NNP .
NNP NNP VBD DT NN IN DT NN NN .
NNS IN NN VBP VBN JJ NNS IN VBG NN IN DT NN .
PRP VBD DT NN .
DT NN VBZ DT JJ NN VBN IN DT NN IN NN .
DT NN VBZ DT JJ NN TO VB NNS TO DT NNS CC NNS .
DT NN MD VB JJ IN NN IN DT RB JJR NN .
DT NNS VBD VBN IN DT NNP NNP CC NNP NNP .
DT NN VBZ DT NN POS NN , NN CC NN .
PRP MD VB DT JJ NN IN DT NN IN CC CC CC CD NNS .
PRP VBP JJ .
PRP RB VBD NNS .
IN PRP VBD VBN DT NN , PRP VBD NN .
IN DT NN VBD IN DT NN VBD JJR .
IN PRP VBP PRP$ NN , VB PRP VB RB CD NNS TO DT JJ NN .
IN DT NN DT NN VBD , NNS IN NNS VBD NNS .
IN DT NN PRP VBD RB , PRP VBD VBN DT NN .
VB DT NN IN PRP VBP DT NN .
DT NN PRP VBD TO VB , PRP MD VB IN PRP .
PRP VBD DT RBR VBN PRP$ NN IN DT NNS VBD VBG .
PRP VBD RB VBD PRP$ NN WRB DT NN VBD IN PRP .
PRP VBD IN DT NN IN VBG WRB NN VBD IN DT NN .
PRP VBD RB VBG WRB DT NN VBD CC PRP$ NN VBD RP .
PRP MD VB PRP RB RB IN PRP VBP NN .
PRP VBD RB VB TO NN IN PRP$ NN VBD RB .
PRP VBD IN TO VB DT NN WRB DT NN VBD .
PRP VBD JJ IN NN WRB DT NN VBD .
PRP VBD VBG IN DT WRB PRP VBD PRP$ NN VBD .
PRP VBD TO NN IN PRP VBD PRP$ NN .
PRP VBZ RB JJR TO VB NNS WRB PRP VBP JJ NNS .
PRP VBD TO VB RB IN PRP VBD NN .
NNP VBD NN IN PRP$ NNS VBD VBG PRP$ NN .
PRP VBP , PRP VBD VBG TO VB IN DT NN RB WRB PRP$ NN VBD VBZ IN NN .
PRP VBD RB VBN PRP$ NN WRB PRP$ NN VBD PRP TO VB VBG DT NN NN .
DT NN VBD NNP WRB PRP VBD PRP$ NN .
DT NNS VBP RBR WRB NNP VBZ .
DT NN PRP VBD DT NN , PRP VBN TO DT NN .
DT JJ NN PRP VBD PRP , PRP VBD VBG NN .
PRP VBD DT RBR VBN DT NN IN PRP VBD VBN IN NN .
DT JJ NN VBD IN DT JJ NNS WRB PRP RB VBD PRP .
PRP VBD IN TO VB WRB PRP VBD RP .
PRP VBD IN TO VB WRB PRP VBD TO VB .
WRB PRP VBP , PRP$ NNS MD VB NN IN PRP .
WRB PRP VBD IN DT NN , PRP VBD TO VB DT NN IN PRP .
WRB PRP VBD RP DT NN , PRP VBD TO NN .
WRB PRP VBP TO VB DT NN , PRP VBP RB JJ IN PRP VBP .
IN NNP VBD VBG PRP$ NN , NNP NNP VBD TO VB PRP .
PRP MD RB VB NNS IN DT NN NN IN PRP VBP PRP$ NN NN .
PRP MD RB VB NN IN PRP VBP PRP$ NN .
PRP MD RB VB NN IN PRP VBP PRP$ NN .
PRP VBP JJR DT NN PRP VBP PRP .
PRP MD VB JJ WRB PRP VBP JJ CC JJ .
VB IN DT NNS IN NNS WRB PRP VBZ JJ .
VB RP WRB PRP VBD IN .
PRP VBD PRP TO VB WRB DT NN VBZ JJ .
PRP VBZ JJ WRB PRP VBZ .
PRP VBZ WRB EX VBP DT NN NN .
PRP VBD PRP$ NN WRB PRP VBD RP NN .
PRP MD VB DT NN WRB PRP MD VB PRP .
IN NN , RB , DT NNP NNP VBZ VBN TO VB NN WRB EX VBZ JJ NN .
VB DT NN WRB PRP VBP DT NN .
VB WRB PRP VBP .
PRP VBD WRB PRP VBD VBN IN NN CD NNS RB .
PRP MD RB VB WRB EX VBZ DT JJ NN .
PRP VBP , VB CC VB WRB PRP$ NNS VBP VBN CC VBN .
PRP VBP TO VB WRB NN VBZ TO VB .
PRP MD VB WRB PRP MD VB NN .
PRP VBD RB , WRB PRP VBD NN .
WRB PRP VBP EX VBP RB IN NNS .
WRB DT NNP NNP IN NNP VBZ , RB DT NNS VBP JJ .
WRB DT NN VBZ , PRP MD VB NN .
WRB EX VBZ NN , EX VBZ NN .
WRB EX VBZ DT NN , NN VBZ JJ CC JJ .
NNP PRP VBP PRP MD VB VBG IN PRP .
VB PRP VB , PRP MD VB RB JJ NN RB RB IN PRP VBP JJ TO VB .
IN DT NN , DT NN MD VB WRB PRP VBZ CC WRB PRP VBZ .
PRP MD VB RB PRP VBP .
PRP MD VB VBN DT NN WRB PRP VBD PRP .
