VB PRP$ LogN whether PRP VBP VBG .
VB PRP PRP$ LogN that PRP MD VB TO PRP$ NN DT NN .
PRP VBD DT LogN why PRP DObj .
PRP VBZ VBN DT LogN why DT NN VBD RB IN LogN .
PRP DObj DT LogN that DT NN VB VBN .
PRP VBD TO NNP POS LogN that DT NN NNS VBP DT NN .
PRP VBP VBN IN NNP VBG IN DT LogN that PRP MD RB VB JJ TO VB PRP DT NN .
PRP VBP VBN TO DT LogN that PRP VBD JJ TO VB DT .
PRP MD VB PRP$ LogN that PRP MD VB DT JJ NN .
PRP VBD DT LogN that PRP VBD RB .
PRP VBP DObj DT LogN that NNP VBD VBN DT NN .
PRP VBP DT LogN when PRP MD VB RB .
PRP VBP DT LogN when PRP MD VB RB .
PRP VBD DT LogN that PRP$ NN VBD VBN .
PRP$ LogN how PRP MD DObj IN NN IN PRP VBZ RB VBN VBN .
PRP$ NN VBD PRP DT LogN how PRP MD VB DT NN .
RB VBD DT LogN that PDT DT NNS MD VB DT NNS .
DT LogN that PRP VBD RB VBD NN VBN NN .
DT LogN that DT NN VBZ VBN VBZ RB VB it VBD DObj .
DT NN VBD DT LogN that DT NNS MD VB DT NN IN RB .
DT LogN that PRP MD VB DT NN RB IN VBG VBZ RB JJ .
DT LogN that PRP MD DObj DT JJ NNS TO VB DT JJ NNS VBD VBN NN .
DT LogN that PRP MD VB RB JJ NN VBZ TO VB VBN .
DT LogN that DT NN IN DT NN NN MD VB IN NN VBZ RB VBN .
DT LogN whether PRP MD VB IN DT NN VBD VBN IN JJ NN .
DT LogN who MD VB DT NN VBZ NN .
EX VBD DT LogN that NNP MD VB VBN IN DT NN .
PRP VBP JJ IN DT LogN that DT NN VBZ IN NNS .
PRP VBD DT LogN that PRP VBP DT DObj .
PRP VBD VBN IN DT LogN that DT NN VB VBN .
PRP VBD VBN IN DT LogN that PRP VBD JJ .
PRP MD VB DT LogN whether DT NNS NN MD VB VBN IN NN .
PRP DT VB RP when PRP VBD DT LogN IN PRP$ NN VBD DT JJ NN .
PRP VBP RB VBG DT LogN whether PRP VBZ JJ .
PRP VBP RB VBG IN DT LogN whether PRP VBZ IN JJ .
PRP VBP RB VB DT LogN why DT VBZ DT JJS NN .
PRP VBP RB RB VBN DT LogN where PRP VBP VBG TO VB PRP$ JJ NN .
LogN VBD that PRP VBD VBN RB .
DT JJ NN DT DObj NN CC JJ JJ NNS .
PDT DT NNS that PRP$ NNS VBP PRP IN PRP$ NN MD VB VBN RP .
IN DT JJ NN PRP DObj RB JJ NN as PRP MD DObj .
NNP VBZ DT NN which VBZ VBN IN JJS NNS .
PRP VBZ RB DT NN IN NN who MD VB RP IN PRP$ LogN .
PRP VBZ DT NN NN that PRP VBP RB VBD TO .
PRP VBZ DT NN whose NNS VBZ DT NN .
PRP VBZ DT JJ NN whose NNS VBP RB IN JJ .
PRP VBZ DT JJ NN that PRP VBP .
PRP VBZ DT JJ NN IN DT NNS that VBZ VBN TO VB .
PRP VBZ DT JJ NN IN PRP that VBZ JJ .
PRP VBZ TO DObj DObj which VBP DObj IN JJ NNS .
PRP VBD DT NN IN whom PRP VBD CD NNS .
PRP RB VBD RP DT JJS NN , which RB VBD CD NNS .
PRP RB VBD RP DT JJ NNS that VBD TO VB VBN RB IN VBG .
PRP VBD NN that DObj PRP JJ .
PRP VBD DT JJ NN that MD VB RP DT NNS .
PRP VBD VBG DT NNS CC NNS that VBD DT NN .
PRP who VBZ JJ NNS RBS .
PRP$ NN TO PRP VBD RB DT JJ as PRP VBD RB VBN .
RB VBZ DT NN that PRP VBD DObj PRP IN .
PRP MD VB DT NN whose NNS VBZ RP IN DT NN .
PRP VBP RB VBN IN NN which MD VB IN NN TO PRP .
PRP VBP DT NN TO which PRP VBZ .
PRP VBP RB VB DT NN why PRP VBZ JJ NN .
PRP VBP JJ IN JJ NNS who VBP PRP$ NNS IN DT NN IN NN .
PRP VBD PRP JJ NNS which PRP DObj DT NN IN .
PRP VBP RB VBN PDT DT NN as PRP VBD RP .
PRP VBP DT NN that PRP MD DObj .
PRP VBP DT NNS that PRP MD VB NN .
PRP VBP DT NNS that VBP VBN IN NN NN .
PRP RB VBD JJ NNS as PRP DObj .
PRP RB VBD IN DT NN whose NNS has VBN IN .
PRP VBP DT TIME when PRP VBD IN DT NN IN PRP$ NNS .
PRP RB VBP DT TIME when PRP RB VBD TO DT NN .
PRP VBD DT NN whose NN VBZ VBN DT IN DT NN .
PRP VBD DT NN where DT NN IN NNS VBD VBN .
PRP VBD RP IN NN IN DT NN where PRP MD DObj DT NN .
PRP MD RB VB DT CD NNS that PRP VBD IN DT JJ JJ NN .
If PRP VBP RB IN DT NN , PRP MD RB DObj RP DT NN IN WDT PRP DObj RB .
VBZ PRP DT NN that DObj NNS .
VBZ PRP DT NN that DObj NNS .
PRP VBZ IN DT NN that PRP RB VBD .
PRP VBD DT JJS NN that PRP RB VBD .
NNP NNP VBZ RB DT NN whom PRP VBP TO VB .
NNP NNP VBZ DT NN whom PRP VBD RP IN DT NN .
NN VBZ VBG TO DObj DT NN whose JJ NN VBZ IN DT NN NNS .
RB RB IN NNP VBD DT JJ NN which VBD IN DT NNP .
NNP VBZ NN that PRP RB VBP VBG .
VBG TO DT PLACE where PRP VBD TO VB MD VB DT VBG NN .
VB RP RB DT LogN which PRP VBP RB LogN NNP TO DObj .
PRP VBD DObj IN DT JJ NN , where EX VBD DT VBG NN .
DT VBZ DT NN whom PRP DObj .
DT VBZ DT JJ NN that DObj IN NN DT NN IN RB .
DT VBZ DT NN how PRP VBP NNP .
DT VBZ DT NN why PRP MD VB SOLOR .
DT NN CC PRP$ NN that VBD VBN IN DT JJ NN VBD DObj TO DT NN NN .
DT NNS who VBP VBG NN VBP IN NNP CD .
DT NN whose NN VBZ VBN MD RB VB VBN .
DT NN VBZ IN DT TIME when NNS VBD NNS .
DT NN that PRP VBD VBG IN VBD JJ .
DT NN which DObj NNS VBZ RB RB IN RB .
DT NN which PRP VBD TO VB JJ NN VBD RB JJ IN DT .
DT JJ NN that PRP VBP TO VB SOLOR VBZ TO VB DT NN .
DT NN whom DT NN RB VBZ VBZ PRP$ NN .
DT NN IN whom PRP VBD VBN VBG IN CD NNS RB VBD PRP$ NNS CC DObj .
DT NN , which PRP VBP RB , VBD RB JJ .
DT NN that PRP VBD IN PRP NN VBZ RB JJ .
DT NN who VBZ VBG DObj IN PRP$ NN VBZ DT NN .
DT NN who VBD VBD DT NN IN NNP .
DT NN whom PRP DObj DT NN TO VBZ DT NN IN NNS .
DT NN whom PRP VBD RB SOLOR VBZ PRP$ JJ NN .
DT NN whose NN PRP VBP RP DObj JJ NN TO VBG PRP$ VBG NNS .
DT NN IN NNS that VBP TO VB DT NN DT NN VBZ CD CD .
DT NNS who VBD IN NNP IN DT CD NNS VBD NNP NNP VBD DT IN PRP$ NN IN NNP .
DT NN that PRP VBD TO PRP VBZ RB JJ .
DT NN whom PRP LogN TO VB VBZ VBN .
DT DObj , whose NNS VBZ RB JJ , VBZ JJ IN DT NN .
DT NN VBP VBN IN DT DT NN NNS whom PRP VBP .
DT NN whom PRP VBP VBG IN VBZ VBN .
DT NN why PRP VBZ JJ VBZ IN PRP$ NN VBD JJ .
DT NN why PRP VBD VBN VBZ JJ TO PRP .
DT NN why PRP VBD RB DObj DT NN VBD IN PRP$ NNP VBD RB RB JJ .
DT NN whose NNS VBZ RB VBZ NN .
DT NN which PRP RB VBD RP VBZ RB JJ .
DT NN which VBZ IN NNP VBZ NN .
DT NN which PRP VBD DObj IN VBD RB JJ .
DT TIME when PRP DObj RB RB VBD .
DT NNS VBD RP DT JJ NN where PRP VBD RP CC VBD .
EX VBZ DT NN who VBZ TO VB PRP .
EX VBZ DT NN that PRP MD VB .
EX VBD JJ TIME when PRP VBD DT LogN IN PRP .
PRP VBD RP PDT DT NNS that VBD JJ IN DT JJ NN .
DT VBZ CD IN DT JJ NNS why DT IN PRP$ NN MD RB VB VBN RB .
DT VBZ DT NN whom PRP DObj NN IN RB .
DT VBZ DT NN which PRP DObj NN .
DT VBZ DT NN , IN which DT NNS VBP VBN .
DT VBZ DT NN which VBZ VBN IN DT NN IN NNS .
DT VBZ DT JJ DObj that PRP VBP VBN VBG IN .
DT who VBP TO VB TO DT NN MD VB IN DT NN NN IN CD NN NN .
DT who VBD VBN IN DT NNS RB DObj VBD .
NNP VBD DT TIME when DT NNS POS NNP IN NNP VBD VBN .
NN PRP MD DObj RB DT NN which PRP DObj IN .
NNP IN PRP$ JJ VBN NN , which MD VB IN DT NN JJ NN .
NNP VBZ DT JJ NN IN which JJS NN VBP .
PRP MD VB TO VB DT JJ NN whom PRP VBP RB VBN IN .
PRP VBP VBN IN DT NN which MD DObj DT NN JJ CD NNS DT NN .
PRP MD RB VB NNS IN DT NN , CC DT VBZ RB NN that MD VB VBN IN .
PRP VBD IN DT NNS CC NNS that PRP VBD IN NN .
WDT IN DT DObj that PRP DObj NN VBD DObj IN NNP .
MD PRP VB VB DT JJ NNS that PRP DObj .
NN PRP VBD DT JJ NN who VBD VBN PRP$ NN .
NN PRP VBD DT NN which VBD IN NNP .
PRP DObj PRP DT NN why PRP VBD DT NN .
PRP MD DObj DT NN SOLOC that PRP MD VB it IN PRP$ JJ NN .
PRP MD VB TO VB SOLOC that PRP$ NNS VBP DObj .
PRP MD VB TO VB SOLOC that PRP$ NNS VBP DObj .
PRP MD VB SOLOC that PRP$ NNS VBP DObj .
PRP MD VB RB SOLOC that_insert DT NN VBZ IN PRP .
PRP MD VB RB SOLOC that_insert DT NN VBZ IN PRP .
PRP MD VB VBN RB RBR if PRP VBD RB VBN VBN IN DT NN .
PRP MD RB VB LogN DT unless PRP VBD JJ IN DT NNS .
If NNS VBP IN NN , PRP VBP NNS .
If PRP VBD PRP , PRP MD VB PRP TO DT NN .
if PRP VBZ RB JJ , PRP MD VB JJ TO VB PRP$ NN POS NN NN RBR .
If PRP VBD NN , PRP MD RB VB TO DT NN .
If PRP VBD NN , PRP MD RB VB TO DT NN .
If PRP VBZ VBG PRP MD VB RP .
If DT NN VBZ JJ JJ NN , PRP MD VB RP DT NN .
If PRP DObj PRP , PRP MD VB PRP .
If PRP VBP IN DT NN , PRP MD VB PRP RP .
If PRP VB PRP$ NN IN DT JJ NN , DT NN NN MD RB DObj PRP .
If PRP VBP NN IN DT , PRP MD RB VB TO VB it .
If PRP VBP TO VB NN PRP MD VB JJR NN .
If PRP VBP TO VB NN PRP MD VB JJR NN .
NNS VBZ JJ TO VB once PRP VBP DT NNS .
SOLOC PRP VB PRP$ NN IN DT NN , PRP MD VB VBN RP .
Provided PRP LogN RB TO DObj NN RB , PRP RB VBP DT NN .
SOLOC that PRP VBP JJ NN , EX VBZ DT NN WRB PRP MD RB VB TO DT JJ NN .
SOLOC that_insert EX VBZ DT NN , PRP MD VB DT NN RB .
SOLOC PRP VB PRP$ NN IN DT NN , PRP MD VB VBN RP .
SOLOC that_insert PRP LogN RB TO DObj NN RB , PRP RB VBP DT NN .
PRP MD VB IN VBG unless PRP VBZ DObj TO VB .
RB RB as PRP VBP JJ , FW MD VB JJ .
DT NN MD VB VBN IN NN unless EX VBZ DT NN .
DT JJ NNS VBP VBG TO VB RB JJ TO VB , SOLOC that PRP VBP IN PRP VBZ DT JJ LogN .
DT JJ NN MD VB DT NNS , SOLOC that PRP DObj DObj RP IN DT JJ NN .
Unless PRP VBZ , DT NN MD VB DObj .
Unless PRP VBP DT NN IN DT NN , PRP VBZ JJ .
Unless PRP VBP RB , PRP MD RB VB DT NN .
PRP MD VB RB if PRP MD RB DObj DT NN .
PRP MD VB RB if PRP MD RB DObj DT NN .
PRP MD VB NN unless PRP VBD NN .
WP MD PRP VB if PRP DObj DT NN IN NN .
WP MD PRP VB if PRP DObj DT NN IN NN .
WP MD VB if EX VBD DT NN .
PRP MD VB IN NNP unless PRP VBP RBR .
PRP MD DObj PRP$ NN SOLOC that_insert PRP DObj PRP RB .
PRP MD VB RB JJ if PRP VBZ PRP VB IN DT NN .
VBG that_insert PRP VBZ NN CC NN , PRP VBZ RB VB PRP VBZ NN TO VB DT NN .
VBG that PRP VBZ NN CC NN , PRP VBZ RB VB PRP VBZ NN TO VB DT NN .
Although NN VBZ JJ , PRP VBZ NN .
Although PRP VBZ RB JJ , RB PRP VBZ RB JJ .
Although PRP VBD VBN , RB PRP VBD IN VBG .
Although PRP VBD VBN RP , RB PRP VBD IN VBG .
Although PRP MD VB , PRP MD VB .
MD PRP DObj PRP whether PRP MD VB CC RB NN .
VBG as PRP VBZ , PRP VBP DT NN .
VBG as PRP VBD , PRP VBD WP VBD DT JJ NN TO VB .
NN though PRP VBZ , PRP VBP DT NN .
NN though PRP VBD , PRP VBD WP VBD DT JJ NN TO VB .
RB if PRP VBZ JJ , PRP VBZ PRP .
VB as PRP DObj , PRP MD RB VB DT DObj RB RB .
SOLOCCS that PRP VBP DObj DT NN , PRP MD RB VB VBN .
SOLOCCS PRP VBP DObj DT NN , PRP MD RB VB VBN .
SOLOCCS that PRP VBP DObj DT NN , PRP MD RB VB VBN .
SOLOCCS that_insert PRP VBP DObj DT NN , PRP MD RB VB VBN .
NNP though PRP VBZ , PRP DObj JJ NN .
However JJ PRP MD VB , PRP MD DObj PRP .
However JJ PRP VBP VBN , PRP MD RB DObj DT NN .
RB RB PRP VBP , DT NN MD VB .
RB VBD that_insert DT NN MD VB , DT JJ MD RB VB JJR CC JJR .
PRP VBD DT JJ NN , although DT NNS VBD VBN .
PRP VBD DT JJ NN , though DT NNS VBD VBN .
NO Matter what PRP VBP CC WRB PRP VBP it , PRP RB VBZ PRP VBP JJ .
NO Matter what PRP VBP , PRP MD RB VB PRP .
NO Matter when PRP VBZ , DT NN VBZ VBN .
VB as PRP MD , PRP MD VB .
PRP DObj DT NN though PRP VBD RB VBN RB JJ .
Though PDT DT NN VBD IN PRP , PRP MD RB VB TO PRP$ LogN .
Though PRP VBZ JJ , CC PRP VBZ JJ .
Though PRP VBZ JJ , PRP RB VBZ .
Though PRP VBD DT NN , PRP VBD WP VBD DT JJ NN TO VB .
Though PRP VBD VBN RP , PRP VBD IN VBG .
Though PRP VBD VBN RP , RB PRP VBD IN VBG .
Though PRP MD VB , PRP MD VB .
PRP MD DObj DT NN RB if DT NN VBZ JJ .
PRP MD DObj DT NN RB JJ that_insert DT NN VBZ JJ .
PRP MD DObj DT NN RB though DT NN VBZ JJ .
PRP MD RB VB VBN RB if PRP VBP CD NNS .
Whatever PRP VBP , PRP MD RB VB PRP .
Whenever PRP VBZ , DT NN VBZ VBN .
Whether PRP NNS CC RB , PRP MD VB RP IN DT VBG NN .
Whether PRP VB it CC RB , PRP VBZ JJ .
JJ DObj that_insert PRP DObj , PRP MD DObj PRP IN DT NN .
While PRP VBP DT NN , PRP VBP RB VB DT NN .
Whoever PRP VBP , PRP MD VB DT NN .
PRP MD VB TO VB DT NN whether PRP VBP JJ CC JJ .
PRP VBZ JJ CC PRP VBZ VBG TO VB NN .
PRP VBZ VBG NN CC PRP DObj RB .
PRP RB JJ VBD PRP DT NN IN LogN , CC RB PRP VBD PRP TO VB NNP .
PRP RB JJ VBZ JJ CC RB PRP VBZ JJ .
PRP VBD VBG IN DT NNS NN CC SOLOR PRP VBZ .
PRP$ NN VBZ DT NN CC PRP$ NN VBZ DT NN .
PRP DObj DT NN CC PRP VBZ it RB JJ .
PRP VBP PRP CC PRP VBZ PRP .
PRP VBP NNS CC PRP IN NN NNS , RB .
PRP VBP VBG NN CC PRP VBP SOLOR NN .
PRP VBP VBG NN , PRP$ NN VBZ SOLOR NN CC PRP$ NN VBZ VBG NN .
PRP VBP VBG NN CC PRP VBP VBG NN .
PRP RB JJ DObj PRP CC RB PRP VBD PRP .
PRP VBD PRP$ JJS , CC PRP VBD RP IN PRP IN JJ .
NNP VBD PRP$ NN CC PRP VBD TO NN .
NNP RB JJ VBZ NN CC RB PRP VBZ NN .
VB VBG DT NN TO DT JJ , CC PRP MD VB NN .
JJ NN NN VBD that_insert NNP CC PRP VBD NNS .
PRP$ NN VBZ DT NN CC PRP$ NN VBZ DT NN .
PRP$ NN VBZ DT NN CC PRP$ NN VBZ DT NN .
DT MD PRP VB DT LogN CC VB PRP VB DT NN .
DT MD PRP VB DT NN CC VB PRP DObj DT NNS .
DT VBD that_insert DT JJ NN VBP NN CC VBD PRP$ NN NN IN PRP .
DT VBD that_insert DT JJ NN VBP NN CC VBD PRP$ NNS VBP TO VB IN PRP .
DT VBD that_insert DT JJ NN VBP NN CC VBD PRP$ NNS VBP TO VB IN PRP .
DT VBZ PRP VBD PRP$ NN , CC MD PRP VB RB .
DT VBZ PRP VBD PRP$ NN , CC MD PRP VB RB .
DT PRP VBZ PRP CC PRP DObj PRP IN NN .
DT NN MD VB PRP CC PRP MD DObj PRP IN LogN .
RB JJ VBP PRP PRP$ NN , CC RB PRP VBP PRP$ NN .
RB JJ VBD DT NN NN PRP , CC PRP VBD RB DObj PRP RB .
RB RB VBD that_insert PRP DObj TO PRP CC RB PRP VBD PRP .
RB RB VBD that_insert PRP DObj TO PRP CC RB PRP VBD PRP .
RB RB PRP VBZ VBG NN , CC RB PRP$ NN VBZ .
RB JJ PRP VBN TO NN RB , CC RB PRP$ NN VBZ .
RB RB PRP VBP IN NN , CC RB PRP$ NN VBZ .
RB JJ VBZ PRP PRP$ NN , CC RB PRP VBZ PRP$ NN .
RB JJ VBZ PRP PRP$ NN , CC RB PRP VBZ PRP$ NN .
RB SOLOR PRP VBZ DT JJ NN CC PRP VBP VBG PRP$ NN IN DT NN .
RB SOLOR PRP VBZ DT JJ NN CC PRP VBP VBG PRP$ NN IN DT NN .
PRP RB JJ VBZ JJ CC RB PRP VBZ JJ .
PRP RB JJ DObj PRP$ JJ DObj , PRP RB VBZ IN PRP .
DT NNS IN NNS VBP VBG PRP NN IN VBG CC VBG JJ NN , CC DT VBZ RB JJ VBG DT NN IN NNS .
DT NN RB JJ VBZ PRP DT NN CC RB PRP VBZ PRP NN .
DT NN POS NN VBZ JJ , CC DT NN POS NN VBZ JJ .
DT NN POS NN VBZ NNP NNP CC DT NN POS NN VBZ JJ .
DT RB JJ VBZ DT NN , CC PRP MD VB SOLOR DT NN IN PRP IN DT JJ JJ NNS .
VB PRP$ DObj , CC PRP MD DObj DT NN .
PRP VBD VBG DT NNS , CC PRP RB VBD RB IN NN .
CD NNS VBD RB JJ IN NNP IN JJ NNS , CC PRP VBD JJ IN DT NNP .
RB PRP VBD , RB , that_insert PRP MD RB DObj PRP .
NNS VBP DT JJ NN TO VB IN , CC PRP VBP JJ .
NNP VBZ DT RB JJ CC PRP VBZ RB JJ .
PRP VBZ JJ : RB PRP VBP RB VB PRP .
PRP VBZ JJ while PRP$ JJ NN VBZ JJ .
PRP DObj DT NN , CC PRP MD RB VB VBG it .
PRP VBD JJ , RB PRP VBD JJ .
PRP VBD PRP$ NN , CC PRP MD RB VB PRP .
VB RB CC RB PRP MD VB DT JJ NN .
VB RP CC PRP MD VB DT JJ NN .
NNP RB RB PRP MD VB DT JJ NN .
PRP VBP RB IN NN SOLOR CC PRP VBP DT NNS TO VB .
PRP VBP RB JJ IN JJ CC PRP VBP DT JJ NN .
PRP VBP JJ TO VB PRP , CC MD PRP DObj PRP DT NN TO DT NN .
PRP VBP RB VB RB , CC PRP VBP DT NN CD .
PRP VBP RB VB NNS CC PRP VBP NN NNS .
PRP VBP RB VB TO VB it CC PRP VBP TO .
PRP VBP VBN , CC PRP MD VB RB .
PRP VBP that_insert NNP CC PRP$ JJ VBZ JJ .
PRP MD VB TO VB VBN TO DT NN JJ NN CC PRP VBD TO VB JJ NNS TO VB DT LogN .
PRP VBZ RB JJ , CC JJ CC JJ .
PRP VBZ JJ , CC PRP VBZ JJ .
PRP RB VBZ but PRP VBZ .
NNP DT NN VBZ RB JJ , CC PRP VBP TO VB .
PRP$ NN VBZ DT JJ NN CC PRP$ NNS VBP RB RB VB PRP$ NNS .
PRP$ NN VBZ JJ CC PRP VBP JJ TO VB JJ IN DT NN .
IN CD JJ NNS VBP JJ IN NN , CC RB DT NN VBZ VBG VBN .
JJ DT NN , RB PRP MD VB .
PRP VBZ DT JJ NN : RB PRP VBP RB VB PRP .
PRP VBZ JJ CC JJ , CC RB NNS VBP PRP .
PRP VBZ RB JJ , CC PRP VBZ RB IN PRP$ CD NNS .
PRP MD VB JJ , CC PRP VBD IN NN .
NNP VBD DT NN IN NNP POS NN , CC PRP$ NNS VBP VBN IN PRP$ JJ NN IN DT NNP NNP .
DT DObj VBZ JJ : RB , PRP VBZ JJ PRP .
DT NNP NNP CC JJ JJ NNS RB RB VBD RP NNS IN NN , CC NNP VBZ RB VBD .
DT JJ JJ NN IN NNP VBZ RB CD NNS IN NN , CC PRP VBP VBN DT CD NN NN IN DT IN CD NN NNS IN DT NNP .
DT NN VBN IN NNS IN JJ NNP IN NNS , CC RB PRP MD RB DObj DT .
DT NN VBN IN NNS IN NNP IN NNS , CC PRP MD RB DObj DT NN .
EX VBP RB CD JJ NNS IN NNP , CC PRP RB VBP RB CD NN IN DT NN POS NN NN .
NNP NNS VBP RB IN JJ NNS , CC NNP VBD JJ TO DObj DT NNS .
PRP VBP DT NN IN DT VBG NNS CC DT VBZ VBN IN PRP$ LogN TO VB IN NN NNS .
PRP VB DT NN while PRP VB DT NN .
PRP MD VB RB , CC PRP MD VB .
MD PRP DObj PRP TO NN CC VB PRP VB TO NN RB JJ .
NNP that_insert PRP VBP PRP TO VB PRP CC VB PRP VBP TO VB it PRP .
VBP PRP VB RB CC VBP PRP DT NN RB .
CC NNP VBZ VBG CC PRP$ NNS VBP .
CC NNP VBZ VBG CC PRP$ NNS VBP .
PRP VBD JJ DT NN , RB PRP MD VB DObj NN IN DT NNS VB .
NNP MD VB JJ IN NN CC PRP MD RB VB VBN VBN .
DT NN MD VB JJ CC PRP MD VB JJ .
PRP MD VB RB , RB PRP MD RB DObj DT NN .
PRP VBP JJ CC PRP MD VB DT JJ NN .
PRP MD RBR VB SOLOR , RB PRP MD VB DT NN .
PRP MD DObj DT NN IN PRP$ NN CC PRP MD DObj PRP .
PRP MD VB RB , RB PRP MD VB DT NN .
PRP VBD IN NN IN DT NN , RB PRP MD VB SOLOR PRP DT DObj .
NNP RB VBZ JJ , IN PRP VBZ TO DObj PRP$ NN IN NN .
NN DObj DT DObj , IN DT NN VBD VBN IN NN .
PRP VBD DT NN , for PRP VBD RB JJ .
PRP VBD DT NN SOLOR , for PRP VBD VBN NNS IN DT NN .
PRP VBP DObj DT NN TO VB , IN PRP VBP TO VB SOLOR .
PRP VBP JJ , for PRP VBZ JJ .
PRP VBD TO PRP , for PRP VBD VBN PRP .
PRP VBZ DT NN , IN PRP VBD it IN JJ .
PRP VBZ NN , for DT NNS VBP VBG .
PRP VBZ NN IN NN IN DT NN NN , IN DT NN PRP VBP IN NN IN NN .
PRP VBZ NN SOLOR , RB DT NN MD VB JJR .
PRP VBZ RB DT RB JJ NN , IN PRP RB VBP PRP$ NN .
NNP VBD JJ , IN PRP VBD RB VB TO NN .
RBS JJ JJ JJ NNS SOLOR VBP IN NNS IN PRP$ NN , so DT NN IN DT NN VBZ JJ NNS IN JJ NN .
PRP MD VB SOLOR , for PRP$ NN VBZ VBG IN PRP .
DT NNPS VBP RB VBN JJ NN IN NN NN , IN PRP MD VB IN DT IN DT NN IN VBG JJ NN .
DT NN VBZ VBN IN NN RB , IN PRP VBP SOLOR NNS .
DT NN VBD JJ so PRP VBD IN PRP$ NN .
DT NN DObj RP RB DT NN , so PRP VBD RB VB DT JJ NN .
PRP DObj PRP TO VB , IN PRP VBD .
PRP VBP IN PRP$ NN NN , IN PRP MD VB JJ NNS IN LogN TO VB DT NN IN PRP .
PRP MD RBR DObj DT NN IN PRP , for PRP VBZ VBG TO VB .
DT NN that_insert DObj DT RBR , DT JJR NN PRP VBZ .
PRP VBZ DT RBR NN than PRP VBD NN .
PRP VBZ RBR RB than PRP$ NN VBZ .
PRP VBD RB IN RB as PRP VBD VBN RB .
PRP VBP PRP DT JJR , DT JJR PRP VBP PRP .
PRP DObj IN JJ NNS as PRP VBP VBN TO VB DObj .
PRP VBZ RB RB JJ as PRP VBP .
NNP VBZ RBR IN DT NN that_insert PRP VBZ .
PRP VBZ RBR than PRP$ NN VBZ .
PRP DObj RB RB RB as PRP VBZ VBD RP .
DT VBZ RB JJ DT NN as PRP MD DObj .
DT NN VBD RBR RB than NN VBP .
DT NN VBZ RB JJ as PRP VBD RB JJ .
DT JJR DT NN VBZ , DT JJR DT NN VBZ .
DT JJR DT NN VBZ VBN , DT JJR DT NN MD VB .
DT JJR PRP VBP , DT JJR PRP VBP PRP$ NN .
DT JJR PRP DObj , DT JJR NN PRP DObj .
DT NNS IN NNP VBP RB RB JJ as PRP VBP IN NNP .
DT NN VBD RB VB RB RB as PRP VBD .
DT NN IN NN VBP JJR RP than PRP VBD TO VB .
EX VBD JJR NNS than PRP VBD VBN .
PRP VBP RBR than PRP VBP JJ IN PRP .
PRP VBP VBN RB JJR NN DT NN than PRP VBD DT NN .
PRP VBD TO VB JJ NN RB RB IN VB NN .
NNP VBZ RB JJ IN JJ NN as PRP VBZ JJ IN JJ NN .
NNP VBP TO DT NNS as PRP MD VB VBN IN .
As NN VBZ TO NN , RB NN VBZ TO NN .
PRP VBZ as if PRP VBD DT NN .
PRP VBD RP PRP$ NN as if PRP VBD VBN VBN .
PRP RB DObj DT NN as though PRP VBD JJ .
PRP VBZ as if PRP VBZ JJ .
PRP VBD PRP$ NNS as if PRP VBD VBG TO VB NN .
PRP VBZ PRP as if PRP VBP DT NN .
PRP VBD RB IN RB VBG DT NN .
PRP VBP as PRP MD VB JJ IN NN .
PRP VBP VBN it as PRP VBP .
PRP VBP DT JJ NN as if PRP VBD NN .
PRP VBD as if EX MD VB DT JJ NN .
PRP VBZ as if DT NN MD DObj RP RB RB .
NNP VBD RB VB as PRP VBD .
DT NNS VBZ VBN as if PRP VBD VBN IN NN .
DT JJ NN VBZ as if PRP VBZ DT JJ NN .
PRP RB VBP DT NNS as if PRP RB VBD .
PRP RB VBP DT NNS as though PRP RB VBD .
PRP VBD DT NN as if PRP VBD PRP$ JJ .
PRP MD VB as PRP$ NNS DObj PRP .
IN DT NNS VBP DT NNS , whose magnificence DT NN RB VBZ IN DT NN .
As VBZ VBN TO DT NNP , NNP VBZ DT JJ JJ NN .
As PRP DT VBP , DT NN VBZ NN .
VBP PRP VBN DT NN NN , whose JJ NN VBZ NN JJ .
PRP VBD TO DObj PRP$ NN IN PRP , as VBD RB DT NN .
PRP VBZ DT NN , who VBZ DT NN .
PRP VBZ TO VB IN NNP , which PRP VBZ RB VB .
PRP MD VB JJ NNS , IN which case PRP MD VB TO VB VBN RP .
PRP VBD that PRP VBD RB VBN PRP RB , WDT VBD RB JJ .
PRP$ NN , who VBZ PRP RB JJ , VBZ JJ IN PRP .
PRP VBD TO NN IN CD , IN when PRP VBD VBG IN DT NN .
IN PRP$ NN EX VBP CD NNS , DT JJS IN whom VBZ NNP NNP .
JJ VBP that_insert PRP VBD DT NNS POS NNP NNP , IN WDT JJ JJ NNS VBP VBN DT NN .
NNP VBZ DT JJ NN IN DT NN , DT NN IN which VBZ CD NNS IN NN .
PRP$ NN , who VBZ DObj IN DT NNP NNP NNP PDT PRP$ NN , VBZ VBG JJ NN .
PRP$ NN , who VBZ RB JJ , VBZ IN EX MD VB DT NNS DT NN .
PRP$ NN , who VBD DT JJ JJ , VBD DT JJ DObj .
NNP , whom PRP VBD IN NNP , VBZ SOLOR RB IN NNP .
NNP VBZ , as PRP VBP , DT JJ NN IN NNP .
NNP , which VBD VBN IN NNP , VBZ VBG RBR CC RBR JJ .
PRP VBZ RB JJ , which PRP MD RB VB .
PRP VBZ DT NN , which PRP VBP RB .
DT DObj , which PRP$ NN DObj PRP IN NNP , VBZ RB JJ IN VBG PRP$ NNP NNP .
DT NN VBZ RB JJ , which DObj PRP RB JJ .
DT NN , which PRP DObj JJ NN , VBZ RB JJ .
DT JJ NN VBZ DT NN , who VBZ IN DT NN .
DT PLACE where NN CC NNS VBP .
DT DObj , whose NNS VBZ JJ , VBZ JJ IN DT JJ NNS .
DT DObj , whose NNS VBZ RB JJ , VBZ JJ IN DT NN .
DT NN VBZ DT NN , which DObj PRP JJ IN NNS TO VB .
DT NNPS , which VBZ SOLOR JJ RB TO VB RP , VBD JJ IN IN DT CD NNS .
DT CD NNS VBD JJ IN DT LogN , as VBD VBN RB .
DT CD NN VBD RB VBN , which IN LogN PRP VBD .
DT NN NNS , which PRP VBD CD NNS RB , VBP RB VBN DT NN .
PRP VBD TO VB , where PRP VBD IN CD NNS .
DT NN VBD VBN IN DT NNP PRP , who VBD DT JJ NN IN NNP NNP .
NNP , which VBZ DT JJ JJ , VBZ JJ NNS .
NNP VBD CD NNS IN DT NN , IN which NN PRP VBD NN .
NNP , which PRP VBD JJ NN , VBZ DT JJ JJ NN .
JJ NNS VBP VBN TO VB how PRP MD DObj PRP$ NNS CC NNS IN NNP .
NNP VBZ RP whether PRP VBP IN PRP .
VB PRP RB VBN that DT NN IN PRP$ NN MD VB VBN .
PRP VBD that PRP VBD VBG TO PRP .
PRP DObj if PRP VBD DObj TO NNP .
PRP DObj PRP where PRP MD DObj NNP .
PRP DObj whose NNS was DT JJS .
PRP VBZ VBG when MD PRP VB DT difficult NN .
PRP DObj PRP that PRP VBD VBG IN DT JJ NN .
PRP DObj that PRP MD VB TO DT NN DT JJ NN .
PRP DObj PRP that PRP MD VB PRP IN DT JJ NN .
PRP VBP JJ that PRP MD VB PRP .
PRP VBP JJ that PRP VBP DObj DT NN .
PRP VBP JJ that_insert PRP MD DObj DT NN .
PRP DObj if PRP VBD RB VB TO NN NN .
PRP VBP RB VB if EX MD VB DT NN DT RBR .
PRP VBP RB VB whom PRP MD VB RP .
PRP VBP RB VB that_insert NNS MD VB .
PRP VBP DObj RP that PDT DT NNS IN DT NN VBP VBN DObj RP .
PRP VBD that_insert it VBD IN PRP VBD VBN RB .
PRP VBP it JJ that PRP DObj RB IN JJ NN DT NN .
PRP LogN PRP JJ that PRP MD VB DT NN IN RB CD NNS .
PRP VBP TO VB if PRP VBD PRP$ NN NN .
NNP NNP VBZ that_insert DT JJ NN IN DT NNP NNP NNP VBZ TO VB DT JJ NN IN NN VBG NNS IN DT NN .
NN IN PRP VBZ where DT JJ NNS MD VB DObj .
PRP$ NN DObj PRP that NN VBZ RB RBR IN NN .
UH DObj PRP when PRP MD VB DT NN .
UH DObj PRP what PRP DObj IN DT NN NN .
NNS VBP VBN that DT NN VBZ IN DT NN .
PRP VBZ that_insert DT JJ LogN NN VBZ RB RB JJ .
VB PRP which VBD PRP VBP IN .
DT NN VBZ that_insert NN VBZ RB .
DT NN VBD that DT NN VBZ IN DT NN NN .
PRP MD VB DObj NN whether PRP MD DObj DT NN CC RB .
PRP DT VBP what PRP VBD TO VB JJ .
PRP DT DObj PRP JJ that PRP DObj DT JJ LogN IN DT NN .
PRP VBP VBG RP whether PRP VBP NNS IN PRP$ NN .
PRP VBD whether TO VB RB .
PRP VBD what PRP VBD VBN TO VB JJ .
PRP VBP that_insert PRP VBP VBN DT NN .
PRP DObj PRP that PRP MD VB IN PRP .
NNP DObj JJR NNS IN NN that_insert DT NN VBZ JJ .
NN DObj DT DObj , so that DT NN VBD VBN IN NN .
PRP DObj RB IN NN that_insert PRP MD VB DT NN .
PRP VBD VBN IN NN DT NN MD VB PRP .
PRP DObj DT NN RB IN NN that PRP MD VB it .
PRP VBP VBG DT NN lest PRP MD DObj DT JJ DObj .
PRP VBP VBG PRP that lest PRP MD DObj DT DObj .
PRP VBP DT DObj lest PRP MD VB it .
PRP VBZ DObj DT DObj IN LogN that PRP MD VB DT NN NNS .
PRP VBD RB RB that PRP MD RB VB PRP$ NNS .
DT NN DObj DT NN TO VB RP IN DT NNS so that PRP MD VB PRP .
DT NNS VBN lest PRP MD VB DT VBG NN .
PRP VBP VBN DT JJ NN so that PRP MD VB TO DT NNS RB .
IN DT NN , PRP VBD as if PRP MD RB VB IN DT JJ LogN .
NNP VBZ RB RB what PRP VBD TO VB .
NNP CC JJ NN VBZ what PRP VBP IN .
PRP VBZ RB RB what PRP VBD .
PRP$ JJ LogN VBD whether NNP NNP VBD VBN RB .
PRP$ JJ NN VBD that DT NN VBP .
PRP$ LogN VBZ that PRP MD VB JJ .
PRP VBZ RB because PRP VBZ RB VB PRP .
PRP VBZ RB as though PRP VBD JJ .
PRP VBZ RB as DT VBZ WP PRP VBP , IN PRP VBD VBG RB IN RB .
PRP VBD as if PRP VBD VBG TO VB .
PRP$ LogN VBZ that PRP MD VB it DT NN IN RB .
PRP$ LogN VBZ that PRP MD VB VBG NNS RB SOLOR .
PRP$ LogN VBZ who MD DObj RP NN IN DT NNP .
PRP$ LogN VBZ that PRP MD DObj PRP .
NNP NNP VBZ when PRP MD VB .
NNP VBZ RB what PRP VBD TO VB .
DT VBZ what PRP VBP TO VB .
DT VBZ what PRP VBP RB IN .
DT VBZ where PRP RB VBD PRP .
DT VBZ where PRP VBP JJ .
DT VBZ why PRP VBD RB VB .
DT VBZ why PRP VBP TO DT LogN .
DT VBZ because PRP VBD TO VB PRP$ JJ NN IN PRP$ NN .
DT VBZ where PRP VBD VBN .
DT VBD when PRP VBD CD .
DT NN VBZ whether PRP VBD NN .
DT NN VBZ whether PRP MD DObj PRP DT NN .
DT LogN VBZ how PRP MD DObj PRP .
DT LogN VBZ how PRP MD DObj DT NNS PRP VBP .
DT LogN VBZ when PRP MD DObj DT DObj NN .
DT LogN VBZ who MD VB DT NN .
DT LogN VBZ whether DT NN VBZ VBG IN PRP .
DT LogN VBZ whether DT NN VBZ JJ SOLOR .
DT LogN VBZ whether PRP MD VB IN PRP .
DT LogN VBZ who PRP MD VB .
DT LogN VBZ whether PRP MD VB JJ TO VB PRP .
DT NN VBZ that PRP VBP JJ IN NNS .
DT VBZ what PRP VBP .
DT VBZ why PRP VBP JJ .
PRP VBP RB who PRP LogN PRP VBD .
As PDT DT NNS VBD JJ , PRP VBD RP .
As PRP VBD VBG , PRP VBD IN NN .
As PRP VBP DT NN , PRP MD RB DObj PRP .
PRP VBP it because PRP VBP it .
PRP VBP RB because PRP VBP TO VB DT NN NN IN DT NN .
SOLOR that PRP VBP RB , PRP MD RBR VB .
SOLOR that PRP VBP RB RB , PRP MD VB .
SOLOR that PRP VBZ VBG , PRP MD VB RB .
Since DT NN VBZ VBN , VB POS VB IN DT NN .
Since PRP VBP DT NN , PRP MD RB DObj PRP .
Since PRP VBP RB JJ , PRP MD RB DObj PRP IN PRP .
DT NN VBZ RB JJ because PRP VBZ JJ .
DT NN VBD because PRP VBD VBN RB .
DT NN VBD because PRP VBD VBN RB .
PRP VBD IN NN because PRP VBD JJR .
PRP MD VB DT NNS because DT NN RB VBZ .
PRP MD RB DObj JJ RB because DT NNS VBP JJ IN PRP .
PRP VBZ PDT DT JJ NN that PRP MD RB VB PRP .
DT NN VBZ RB JJ that PRP MD RB VB it .
NNP VBZ RB JJ that PRP MD RB VB DT NN IN PRP DT RB .
PRP VBD JJ JJ NNS that PRP MD RB VB DT NN .
PRP VBZ RB JJ NN that PRP MD RB VB TO DT NN IN PRP .
PRP VBZ RB JJ that PRP MD VB TO NN .
PRP VBZ RB RB that DT NN MD VB PRP .
PRP VBD RB JJ that PRP MD RB VB DT LogN .
PRP VBD PDT DT JJ NN that NN VBD TO VB NN .
PRP VBD PDT DT JJ NN that DT IN PRP VBD TO VB it RB .
PRP$ NN VBZ RB RB VBN that PRP MD VB JJ NNS .
DT NN VBD RB JJ that DT IN PRP VBD TO VB it RB .
DT NN DObj RB JJ NNS that PRP VBP TO DObj NN IN PRP .
EX VBZ RB JJ DT increase IN NN that DT NN NN VBZ DObj .
DT CD VBD RB JJ IN NN that PRP RB DObj NNS IN DT JJ .
PRP VBZ DT NN that PRP VBD RB VB .
PRP VBZ DT NN that PRP MD RB VB .
PRP VBZ RB VB PRP whether PRP VBP CC RB .
PRP VBZ RB DObj DT NN whether PRP VBZ CC RB .
PRP VBZ RB VB whether PRP MD VB CC RB .
PRP VBD that PRP VBD IN WDT NN .
PRP VBZ DT NN TO PRP how PRP DT VBD .
PRP VBZ JJ that PRP MD VB RB IN PRP$ NN .
PRP VBZ JJ LogN that DT NN VBZ RB DT NN .
PRP VBZ JJ whether PRP MD VB JJ TO VB .
PRP VBZ JJ that PRP MD VB RB IN DT NNP .
PRP VBZ VBN TO PDT DT JJ NNS IN JJ NNS .
PRP VBZ TO VB VBN whether PRP MD VB PRP JJ CC JJ .
PRP VBD DT LogN whether PRP MD VB PRP .
PRP VBD RB JJ that PRP DObj TO VB TO PRP .
That PRP MD VB VBZ JJ .
That PRP MD VB NNS VBZ DT LogN .
That PRP MD RB VB TO DT NN DT NN VBZ JJ .
DT NN that_insert MD VB RP VBZ JJ .
That PRP VBD DT NN VBZ DT NN .
That PRP VBP RB JJ VBZ PRP .
That PRP VBD RB VB TO DT NN VBD DT NN .
That PRP MD VB DT NN VBZ JJ .
What PRP VBZ VBP DT DObj .
What PRP VBP TO VB VBZ DT .
What PRP VBP VBZ NN .
What PRP VBP VBZ JJR NN .
Whatever PRP VBD VBD JJ .
When PRP MD VB RB VBZ IN DT NN .
When DT NN VBZ TO DObj RP VBZ RB VBN VBN .
When PRP MD VB NN MD VB DObj RB .
Where DT NN MD VB SOLOR VBZ RB RB VBN .
Whether DT NN MD VB VBN RP VBZ RB VBN VBN RB .
NNP IN PRP VBN IN DT NN VBZ RB DT NN .
Which NN MD VB VBZ RB JJ .
WP VBD that_insert DT NN VBZ DT LogN .
NNP VBZ that_insert DT NN MD VB VBN .
Whoever VBZ TO VB IN DT NN MD DObj DT NN .
NNP VBZ DT NN IN LogN NN .
NNP VBZ TO VB DT JJR NN IN VBG NNS IN JJ NN .
PRP VBD PRP DT NNS .
PRP VBZ JJ .
PRP VBZ NNP RB JJ .
PRP MD DObj PRP DT JJ NN .
PRP VBD NN .
PRP DObj DT DObj JJ .
PRP MD DObj PRP$ NNS TO VB DT NNS .
NNP MD VB DT JJ NN NN IN JJ NNS CC JJR NNS .
NNP VBZ PRP JJ .
NNP VBZ DT NN .
PRP$ NN MD DObj NN .
NNP VBZ IN NNP NNP NNP .
NNP NNP VBD DT NN IN DT NN NN .
NNS IN NN VBP VBN JJ NNS IN VBG NN IN DT NN .
PRP VBD DT NN .
DT NN VBZ DT JJ NN VBN IN DT NN IN NN .
DT NN VBZ DT JJ LogN TO VB NNS TO DT NNS CC NNS .
DT NN MD VB JJ IN NN IN DT RB JJR NN .
DT NNS VBD VBN IN DT NNP NNP CC NNP NNP .
DT NN DObj DT NN POS NN , NN CC NN .
PRP MD VB DT JJ NN IN DT NN IN CC CC CC CD NNS .
PRP VBP JJ .
PRP RB VBD NNS .
After PRP VBD VBN DT NN , PRP VBD NN .
As DT NN VBD IN DT NN DObj JJR .
Before PRP VBP PRP$ NN , VB PRP VB RB CD NNS TO DT JJ NN .
IN DT NN that_insert DT NN VBD , NNS IN NNS VBD NNS .
IN DT NN PRP VBD RB , PRP VBD VBN DT DObj .
VB DT NN before PRP DObj DT NN .
DT NN PRP VBD TO VB , PRP MD VB IN PRP .
PRP VBD NO Sooner VBN PRP$ NN than DT NNS VBD VBG .
PRP VBD RB VBD PRP$ NN when DT NN VBD IN PRP .
PRP VBD IN DT NN IN VBG when NN VBD IN DT NN .
PRP VBD RB VBG when DT NN VBD CC PRP$ NN VBD RP .
PRP MD VB PRP RB RB as PRP DObj NN .
PRP VBD RB VB TO NN until PRP$ NN VBD RB .
PRP VBD IN TO DObj DT NN when DT NN VBD .
PRP VBD JJ IN NN when DT NN VBD .
PRP VBD VBG IN DT when PRP VBD PRP$ NN VBD .
PRP VBD TO NN after PRP VBD PRP$ NN .
PRP VBZ RB JJR TO DObj NNS when PRP VBP JJ NNS .
PRP VBD TO VB RB as PRP VBD NN .
NNP DObj NN while PRP$ NNS VBD VBG PRP$ NN .
PRP VBP , PRP VBD VBG TO DObj IN DT NN RB when PRP$ NN VBD VBZ IN NN .
PRP VBD RB VBN PRP$ NN when PRP$ NN DObj PRP TO VB VBG DT NN NN .
DT NN VBD NNP when PRP VBD PRP$ NN .
DT NNS DObj RBR when NNP VBZ .
DT NN PRP VBD DT LogN , PRP VBN TO DT NN .
DT JJ NN that_insert PRP VBD PRP , PRP VBD VBG NN .
PRP VBD NO Sooner VBN DT NN than PRP VBD VBN IN NN .
DT JJ NN VBD IN DT JJ TIME when PRP RB VBD it .
PRP VBD IN TO DObj when PRP VBD RP .
PRP VBD IN TO VB when PRP VBD TO VB .
When PRP VBP , PRP$ NNS MD DObj NN IN PRP .
When PRP VBD IN DT NN , PRP VBD TO VB DT NN IN PRP .
When PRP VBD RP DT NN , PRP VBD TO NN .
Whenever PRP VBP TO VB DT NN , PRP DObj RB JJ IN PRP VBP .
While NNP VBD VBG PRP$ NN , NNP VBD TO VB PRP .
PRP MD RB DObj DObj IN DT NN NN before PRP DObj PRP$ NN NN .
PRP MD RB VB NN till PRP VBP PRP$ NN .
PRP MD RB VB NN until PRP VBP PRP$ NN .
PRP VBP JJR DT NN that_insert PRP VBP PRP .
PRP MD VB JJ when PRP VBP JJ CC JJ .
VB IN DT NNS IN NNS where PRP VBZ JJ .
VB RP where PRP VBD IN .
PRP VBD PRP TO VB where DT NN VBZ JJ .
PRP VBZ JJ wherever PRP VBZ .
PRP VBZ where EX VBP DT NN NN .
PRP DObj PRP$ NN where PRP VBD RP NN .
PRP MD VB DT DObj where PRP MD VB it .
IN NN , RB , DT NNP NNP VBZ VBN TO DObj NN wherever EX VBZ JJ NN .
VB DT NN where PRP VBP DT LogN .
VB wherever PRP VBP .
PRP VBD where PRP VBD VBN IN NN CD NNS RB .
PRP MD RB VB where EX VBZ DT JJ NN .
PRP VBP , VB CC VB where PRP$ NNS VBP VBN CC VBN .
PRP VBP TO VB where NN VBZ TO VB .
PRP MD PLACE where PRP MD DObj NN .
PRP VBD RB , where PRP VBD NN .
Where PRP VBP EX VBP RB IN NNS .
Where DT NNP NNP IN NNP VBZ , RB DT NNS VBP JJ .
Where DT NN VBZ , PRP MD DObj NN .
Where EX VBZ NN , EX VBZ LogN .
Where EX VBZ DT NN , NN VBZ JJ CC JJ .
NNP that_insert PRP VBP PRP MD VB VBG IN PRP .
VB PRP VB , PRP MD VB RB JJ NN RB RB as PRP VBP JJ TO VB .
IN DT NN , DT NN MD VB where PRP VBZ CC WRB PRP VBZ .
PRP MD VB RB that_insert PRP VBP .
PRP MD VB VBN DT DObj where PRP DObj PRP .
