PRP VBD DT NN why PRP VBD .
PRP VBZ VBN DT NN why DT NN VBD RB IN NN .
PRP VBZ RB VBN DT NN whether PRP MD VB RB .
PRP VBD DT NN that DT NN VB VBN .
PRP VBD VB PRP$ NN that PRP MD VB JJ TO VB TO NN .
PRP VBD TO NNP POS NN that DT NN NNS VBP DT NN .
PRP VBD PRP DT NN that PRP MD RB VB JJ NN .
PRP VBP VBN TO DT NN that PRP VBD JJ TO VB DT .
PRP MD VB PRP$ NN that PRP MD VB DT JJ NN .
PRP VBD DT NN that PRP VBD RB .
PRP VBP VBN DT NN that NNP VBD VBN DT NN .
PRP VBP DT NN what VBP NNS PRP VBZ .
PRP VBP DT NN when PRP MD VB RB .
PRP VBP DT NN when PRP MD VB RB .
PRP VBP DT NN how PRP VBD RB , RB IN NN .
PRP VBD DT NN that PRP$ NN VBD VBN .
PRP VBZ JJ TO VB PRP$ NN how PRP VBD PRP .
PRP$ NN how PRP MD VB IN NN IN PRP VBZ RB VBN VBN .
RB VBD DT NN that PDT DT NNS MD VB DT NNS .
DT NN that PRP VBD RB VBD NN VBN NN .
DT NN that DT NN VBZ VBN VBZ RB VB PRP VBD VBN .
DT NN VBD DT NN that DT NNS MD VB DT NN IN RB .
DT NN that PRP MD VB DT NN RB IN VBG VBZ RB JJ .
DT NN that PRP VBD VBN DT NN RB VBN IN DT JJ NN .
DT NN that PRP MD VB DT JJ NNS TO VB DT JJ NNS VBD VBN NN .
DT NN who MD VB DT NN VBZ NN .
DT NN who MD VB PRP$ NN VBZ RB RB JJ .
DT NN VBD TO PRP that RB DT NN VBD VBN DT NN .
EX VBZ DT NN that PRP VBZ VBN IN DT NN .
EX VBD DT NN that NNP MD VB VBN IN DT NN .
PRP VBP JJ IN DT NN that DT NN VBZ IN NNS .
PRP VBD DT NN that PRP VBP DT NN .
PRP VBD VBN IN DT NN that DT NN VB VBN .
PRP VBD VBN IN DT NN that PRP VBD JJ .
PRP MD VB DT NN whether DT NNS NN MD VB VBN IN NN .
PRP DT VB RP when PRP VBD DT NN IN PRP$ NN VBD DT JJ NN .
PRP VBP RB VBG DT NN whether PRP VBZ JJ .
PRP VBP RB VBG IN DT NN whether PRP VBZ IN JJ .
PRP VBP RB VB DT NN why DT VBZ DT JJS NN .
PRP VBP RB RB VBN DT NN where PRP VBP VBG TO VB PRP$ JJ NN .
NNP VBD that PRP VBD VBN RB .
NNP VBZ VBN DT NN why DT NN VBD RB IN NN .
DT JJ NN DT VBZ NN CC JJ JJ NNS .
PDT DT NNS that PRP$ NNS VBP PRP IN PRP$ NN MD VB VBN RP .
IN DT JJ NN PRP VBD RB JJ NN as PRP MD VB .
NNP VBZ DT NN which VBZ VBN IN JJS NNS .
NNP VBZ NN which VBZ NN , RB VBN .
NNP , which VBZ IN DT NN , VBZ , RB , JJ IN JJ JJ NN .
PRP VBZ RB DT NN IN NN who MD VB RP IN PRP$ NNS .
PRP VBZ DT NN NN that PRP VBP RB VBD TO .
PRP VBZ DT NN whose NNS VBZ DT NN .
PRP VBZ DT JJ NN whose NNS VBP RB IN JJ .
PRP VBZ RB DT JJ NN as PRP VBD .
PRP VBZ DT JJ NN IN PRP that VBZ JJ .
PRP VBZ TO VB NNS which VBP VBN IN JJ NNS .
PRP VBD DT NN IN whom PRP VBD CD NNS .
PRP RB VBD RP DT JJ NNS that VBD TO VB VBN RB IN VBG .
PRP VBD NN that VBD PRP JJ .
PRP VBD DT JJ NN that MD VB RP DT NNS .
PRP VBD VBG DT NNS CC NNS that VBD DT NN .
PRP who VBZ JJ NNS RBS .
PRP$ NN TO PRP VBD RB DT JJ as PRP VBD RB VBN .
PRP MD VB DT NN whose NNS VBZ RP IN DT NN .
PRP VBP RB VBN IN NN which MD VB IN NN TO PRP .
PRP VBP DT NN TO which PRP VBZ .
PRP VBP RB VB DT NN why PRP VBZ JJ NN .
PRP VBP JJ IN JJ NNS who VBP PRP$ NNS IN DT NN IN NN .
PRP VBD PRP JJ NNS which PRP VBD DT NN IN .
PRP VBP RB VBN PDT DT NN as PRP VBD RP .
PRP VBP DT NN that PRP MD VB .
PRP VBP DT NNS that PRP MD VB NN .
PRP VBP DT NNS that VBP VBN IN NN NN .
PRP RB VBD JJ NNS as PRP VBZ .
PRP VBP DT TIME when PRP VBD IN DT NN IN PRP$ NNS .
PRP RB VBP DT TIME when PRP RB VBD TO DT NN .
PRP VBD DT NN whose NN VBZ VBN DT IN DT NN .
PRP VBD RP IN NN IN DT NN where PRP MD VB DT NN .
PRP MD RB VB DT CD NNS that PRP VBD IN DT JJ JJ NN .
If PRP VBP RB IN DT NN , PRP MD RB VB RP DT NN IN WDT PRP VBD RB .
VBZ PRP DT NN that VBZ NNS .
PRP VBZ IN DT NN that PRP RB VBD .
PRP VBZ DT JJ NN that PRP VBD NN NN .
PRP VBD DT JJS NN that PRP RB VBD .
JJ NNS IN DT TIME when PRP MD VB VBG DT NN IN DT NN .
NNP VBD JJ IN DT NNS which DT NN VBD .
NNP NNP VBZ DT NN whom PRP VBD RP IN DT NN .
NNP NNP VBD DT NN who VBD JJ IN VBG IN NNPS .
NN VBZ VBG TO VB DT NN whose JJ NN VBZ IN DT NN NNS .
RB RB IN NNP VBD DT JJ NN which VBD IN DT NNP .
NNP VBZ NN that PRP RB VBP VBG .
NNP VBZ DT RBS JJ JJ NN that PRP VBP RB VBN RP .
VBG TO DT PLACE where PRP VBD TO VB MD VB DT VBG NN .
VB RP RB DT NNS which PRP VBP RB VB NNP TO VB .
PRP VBZ CD IN DT NNS that VBP RB JJ .
PRP VBD DT JJ NN that VBD RB .
DT VBZ DT NN whom PRP VBP .
DT VBZ DT NN how PRP VBP NNP .
DT VBZ DT NN why PRP MD VB RB .
DT VBD DT NN why PRP VBD TO VB IN DT NN .
DT NN CC PRP$ NN that VBD VBN IN DT JJ NN VBD VBN TO DT NN NN .
DT NNS who VBP VBG NN VBP IN NNP CD .
DT NN whose NN VBZ VBN MD RB VB VBN .
DT NN that PRP VBD VBG IN VBD JJ .
DT NN which VBZ NNS VBZ RB RB IN RB .
DT NN which PRP VBD TO VB JJ NN VBD RB JJ IN DT .
DT NN whom DT NN RB VBZ VBZ PRP$ NN .
DT NN IN whom PRP VBD VBN VBG IN CD NNS RB VBD PRP$ NNS CC VBD .
DT PLACE where PRP VBD CD NNS RB VBZ VBN VBN RP .
DT NN , which PRP VBP RB , VBD RB JJ .
DT NN that PRP VBD IN PRP NN VBZ RB JJ .
DT NN who PRP VBD VBZ VBN NNP .
DT NN who VBZ VBG NNS IN PRP$ NN VBZ DT NN .
DT NN whom PRP VBD DT NN TO VBZ DT NN IN NNS .
DT NN whom PRP VBD RB RB VBZ PRP$ JJ NN .
DT NN IN NNS that VBP TO VB DT NN DT NN VBZ CD CD .
DT NN , who VBD VBN RB IN RB CD NNS , VBD TO VB PRP$ NNS .
DT NN whom PRP VBP TO VB VBZ VBN .
DT NN , whose NNS VBZ RB JJ , VBZ JJ IN DT NN .
DT NN VBP VBN IN DT DT NN NNS whom PRP VBP .
DT NN why PRP VBZ JJ VBZ IN PRP$ NN VBD JJ .
DT NN whose NNS VBZ RB VBZ NN .
DT NN which PRP RB VBD RP VBZ RB JJ .
DT NN which PRP VBD VBN IN VBD RB JJ .
DT NNS NN VBZ DT NN which PRP MD RB VB RP .
DT JJ NN that PRP VBD VBD VBN RP IN NN RB .
DT TIME when PRP VBD RB RB VBD .
DT CD NNS VBD JJ IN DT NN , as VBD VBN RB .
DT NNS RB VBP IN DT NN , which VBZ RB JJ TO NNS .
DT JJS NN that PRP VBP JJ IN VBD IN DT NN .
EX VBZ DT JJ NN which VBZ NN TO DT NN .
EX VBZ DT NN that PRP MD VB .
EX VBD JJ TIME when PRP VBD DT NN IN PRP .
PRP VBD RP PDT DT NNS that VBD JJ IN DT JJ NN .
DT MD VB DT VBG NN IN DT NN , who RB VBZ CD JJR NNS IN DT NN .
DT VBZ CD IN DT JJ NNS why DT IN PRP$ NN MD RB VB VBN RB .
DT VBZ DT NN whom PRP VBD NN IN RB .
DT VBZ DT TIME when DT NN VBZ JJ IN NNS .
DT VBZ DT NN which PRP VBD NN .
DT VBZ DT PLACE where PRP VBD DT NN .
DT VBZ DT NN , IN which DT NNS VBP VBN .
DT VBZ DT NN which VBZ VBN IN DT NN IN NNS .
DT VBZ DT JJ NN that PRP VBP VBN VBG IN .
DT VBZ DT NN how PRP RB VBZ PRP .
DT who VBD VBN IN DT NNS RB VBD VBD .
NNP VBD DT TIME when DT NNS POS NNP IN NNP VBD VBN .
NN PRP MD VB RB DT NN which PRP VBD IN .
NNP IN PRP$ JJ VBN NN , which MD VB IN DT NN JJ NN .
NNP VBZ DT JJ NN IN which JJS NN VBP .
PRP MD VB TO VB DT JJ NN whom PRP VBP RB VBN IN .
PRP VBP VBN IN DT NN which MD VB DT NN JJ CD NNS DT NN .
PRP MD RB VB NNS IN DT NN , CC DT VBZ RB NN that MD VB VBN IN .
PRP VBD IN DT NNS CC NNS that PRP VBD IN NN .
PRP MD VB TO VB NNS VB DT NNS that PRP VBP IN PRP$ NNS .
WDT IN DT NNS that PRP VBD NN VBD VBN IN NNP .
MD PRP VB VB DT JJ NNS that PRP VBP .
NN PRP VBD DT NN which VBD IN NNP .
PRP VBP PRP DT NN why PRP VBD DT NN .
PRP MD VB DT NN VBG that PRP MD VB PRP IN PRP$ JJ NN .
PRP MD VB VBN that PRP VBZ RB VB .
PRP MD VB TO VB VBN that PRP$ NNS VBP VBN .
PRP MD VB TO VB VBG that PRP$ NNS VBP VBN .
PRP MD VB VBG that PRP$ NNS VBP VBN .
PRP MD VB RB VBD that_insert DT NN VBZ IN PRP .
PRP MD VB VBN RB RBR if PRP VBD RB VBN VBN IN DT NN .
PRP MD RB VB VBG DT unless PRP VBD JJ IN DT NNS .
If NNS VBP IN NN , PRP VBP NNS .
if PRP VBZ RB JJ , PRP MD VB JJ TO VB PRP$ NN POS NN NN RBR .
If PRP VBD NN , PRP MD RB VB TO DT NN .
If PRP VBD NN , PRP MD RB VB TO DT NN .
If PRP VBD NN , WP VBD PRP VB .
If PRP VBZ VBG PRP MD VB RP .
If DT NN VBZ JJ JJ NN , PRP MD VB RP DT NN .
If PRP VBP JJ NN TO DT NN , PRP MD VB DT JJR NN .
If PRP VBP TO VB NN PRP MD VB JJR NN .
If PRP VBP TO VB NN PRP MD VB JJR NN .
VBG PRP VB PRP$ NN IN DT NN , PRP MD VB VBN RP .
Provided PRP VBP RB TO VB NN RB , PRP RB VBP DT NN .
VBG that PRP VBP JJ NN , EX VBZ DT NN WRB PRP MD RB VB TO DT JJ NN .
VBG PRP VB PRP$ NN IN DT NN , PRP MD VB VBN RP .
VBG that_insert PRP VBP RB TO VB NN RB , PRP RB VBP DT NN .
PRP MD VB IN VBG unless PRP VBZ VBN TO VB .
RB RB as PRP VBP JJ , FW MD VB JJ .
DT NN MD VB VBN IN NN unless EX VBZ DT NN .
DT JJ NNS VBP VBG TO VB RB JJ TO VB , VBD that PRP VBP IN PRP VBZ DT JJ NN .
DT JJ NN MD VB DT NNS , VBN that PRP VBZ VBN RP IN DT JJ NN .
Unless PRP VBZ , DT NN MD VB VBN .
Unless PRP VBP DT NN IN DT NN , PRP VBZ JJ .
Unless PRP VBP RB , PRP MD RB VB DT NN .
PRP MD VB RB if PRP MD RB VB DT NN .
PRP MD VB NN unless PRP VBD NN .
WP MD PRP VB if PRP VBP DT NN IN NN .
WP MD VB if EX VBD DT NN .
PRP MD VB IN NNP unless PRP VBP RBR .
PRP MD VB PRP$ NN VBD that_insert PRP VBP PRP RB .
VBG that_insert PRP VBZ NN CC NN , PRP VBZ RB VB PRP VBZ NN TO VB DT NN .
VBG that PRP VBZ NN CC NN , PRP VBZ RB VB PRP VBZ NN TO VB DT NN .
Although PRP VBZ RB JJ , RB PRP VBZ RB JJ .
Although PRP VBD VBN , RB PRP VBD IN VBG .
Although PRP VBD VBN RP , PRP VBD IN VBG .
Although PRP MD VB , PRP MD VB .
MD PRP VB PRP whether PRP MD VB CC RB NN .
VBG as PRP VBD , PRP VBD WP VBD DT JJ NN TO VB .
NN though PRP VBZ , PRP VBP DT NN .
NN though PRP VBD , PRP VBD WP VBD DT JJ NN TO VB .
RB if PRP VBZ JJ , PRP VBZ PRP .
VB as PRP VBD , PRP MD RB VB DT NN RB RB .
VBN PRP VBP VBN DT NN , PRP MD RB VB VBN .
VBG that PRP VBP VBN DT NN , PRP MD RB VB VBN .
VBG that_insert PRP VBP VBN DT NN , PRP MD RB VB VBN .
VBG as PRP VBZ , PRP VBZ JJ NN .
However JJ PRP MD VB , PRP MD VB PRP .
However JJ PRP VBP VBN , PRP MD RB VB DT NN .
RB RB PRP VBP , DT NN MD VB .
PRP VBD DT JJ NN , although DT NNS VBD VBN .
DT NN how JJ PRP VBP VBN , PRP MD RB VB DT NN .
DT NN what PRP VBP CC WRB PRP VBP PRP , PRP RB VBZ PRP VBP JJ .
DT NN who PRP VBP , PRP MD VB DT NN .
PRP VBD DT NN though PRP VBD RB VBN RB JJ .
Though PDT DT NN VBD IN PRP , PRP MD RB VB TO PRP$ NN .
Though PRP VBZ RB JJ , RB PRP VBZ RB JJ .
Though PRP VBZ JJ , CC PRP VBZ JJ .
Though PRP VBZ JJ , PRP VBZ JJ .
Though PRP VBD DT NN , PRP VBD WP VBD DT JJ NN TO VB .
Though PRP VBD VBN RP , PRP VBD IN VBG .
Though PRP MD VB , PRP MD VB .
VB JJ as PRP MD , PRP RB VBZ JJ TO VB DT NN RB .
PRP MD VB DT NN RB if DT NN VBZ JJ .
PRP MD VB DT NN RB JJ that_insert DT NN VBZ JJ .
PRP MD VB DT NN RB though DT NN VBZ JJ .
PRP MD RB VB VBN RB if PRP VBP CD NNS .
Whatever VBD , PRP MD RB VB .
Whether PRP NNS CC RB , PRP MD VB RP IN DT VBG NN .
JJ NN that_insert PRP VBP , PRP MD VB PRP IN DT NN .
While PRP VBP DT NN , PRP VBP RB VB DT NN .
Whoever PRP VBP , PRP MD VB DT NN .
PRP MD VB TO VB DT NN whether PRP VBP JJ CC JJ .
PRP VBD VBN VBN CC PRP VBD VBN .
PRP VBZ JJ CC PRP VBZ VBG TO VB NN .
PRP VBZ VBG NN CC PRP VBZ RB .
PRP RB JJ VBD PRP DT NN IN NN , CC RB PRP VBD PRP TO VB NNP .
PRP RB JJ VBZ JJ CC RB PRP VBZ JJ .
PRP VBD VBG IN DT NNS NN CC RB PRP VBZ .
PRP$ NN VBZ DT NN CC PRP$ NN VBZ DT NN .
PRP$ NN VBZ DT NN CC PRP$ NN VBZ DT NN .
PRP VBD DT NN CC PRP VBZ PRP RB JJ .
PRP VBP PRP CC PRP VBZ PRP .
PRP VBP NNS CC PRP IN NN NNS , RB .
PRP VBP VBG NN CC PRP VBP VBG NN .
PRP VBP VBG NN , PRP$ NN VBZ VBG NN CC PRP$ NN VBZ VBG NN .
PRP VBP VBG NN CC PRP VBP VBG NN .
PRP RB JJ VBD PRP CC RB PRP VBD PRP .
PRP RB JJ VBD PRP CC RB PRP VBD PRP .
PRP VBD PRP$ JJS , CC PRP VBD RP IN PRP IN JJ .
NNP VBD PRP$ NN CC PRP VBD TO NN .
NNP RB JJ VBZ NN CC RB PRP VBZ NN .
VB VBG DT NN TO DT JJ , CC PRP MD VB NN .
JJ NN NN VBD that_insert NNP CC PRP VBD NNS .
PRP$ NN VBZ DT NN CC PRP$ NN VBZ DT NN .
PRP$ NN VBZ DT NN CC PRP$ NN VBZ DT NN .
DT MD PRP VB DT NN CC VB PRP VB DT NN .
DT MD PRP VB DT NN CC VB PRP VB DT NNS .
DT VBD that_insert DT JJ NN VBP NN CC VBD PRP$ NNS VBP TO VB IN PRP .
DT VBD that_insert DT JJ NN VBP NN CC VBD PRP$ NNS VBP TO VB IN PRP .
DT VBZ PRP VBD PRP$ NN , CC MD PRP VB RB .
DT PRP VBZ PRP CC PRP VBZ PRP IN NN .
DT NN MD VB PRP CC PRP MD VB PRP IN NN .
RB JJ VBP PRP PRP$ NN , CC RB PRP VBP PRP$ NN .
RB JJ VBD DT NN NN PRP , CC PRP VBD RB VBN PRP RB .
RB RB VBD that_insert PRP VBP TO PRP CC RB PRP VBD PRP .
RB RB VBD that_insert PRP VBP TO PRP CC RB PRP VBD PRP .
RB RB PRP VBZ VBG NN , CC RB PRP$ NN VBZ .
RB JJ PRP VBN TO NN RB , CC RB PRP$ NN VBZ .
RB RB PRP VBP IN NN , CC RB PRP$ NN VBZ .
RB JJ VBZ PRP PRP$ NN , CC RB PRP VBZ PRP$ NN .
RB JJ VBZ PRP PRP$ NN , CC RB PRP VBZ PRP$ NN .
PRP RB VBD PRP$ NN , PRP MD CC VBP RB .
PRP RB JJ VBZ JJ CC RB PRP VBZ JJ .
DT NNS IN NNS VBP VBG PRP NN IN VBG CC VBG JJ NN , CC DT VBZ RB JJ VBG DT NN IN NNS .
DT NN RB JJ VBZ PRP DT NN CC RB PRP VBZ PRP NN .
DT NN POS NN VBZ JJ , CC DT NN POS NN VBZ JJ .
DT NN POS NN VBZ NNP NNP CC DT NN POS NN VBZ JJ .
PRP RB JJ VBP CC RB PRP VBP NN .
DT RB JJ VBZ DT NN , CC PRP MD VB VBG DT NN IN PRP IN DT JJ JJ NNS .
VB PRP$ NN , CC PRP MD VB DT NN .
PRP VBD VBG DT NNS , CC PRP RB VBD RB IN NN .
RB PRP VBD , RB , that_insert PRP MD RB VB PRP .
NNS VBP DT JJ NN TO VB IN , CC PRP VBP JJ .
NNP VBZ DT RB JJ CC PRP VBZ RB JJ .
PRP VBZ JJ : RB PRP VBP RB VB PRP .
PRP VBZ JJ while PRP$ JJ NN VBZ JJ .
PRP VBD DT NN , CC PRP MD RB VB VBG PRP .
PRP VBD JJ , RB PRP VBD JJ .
PRP VBD PRP$ NN , CC PRP MD RB VB PRP .
VB RP CC PRP MD VB DT JJ NN .
NNP RB RB PRP MD VB DT JJ NN .
PRP VBP RB IN NN RB CC PRP VBP DT NNS TO VB .
PRP VBP RB JJ IN JJ CC PRP VBP DT JJ NN .
PRP VBP JJ TO VB PRP , CC MD PRP VB PRP DT NN TO DT NN .
PRP VBP RB VB RB , CC PRP VBP DT NN CD .
PRP VBP RB VB NNS CC PRP VBP NN NNS .
PRP VBP RB VB NN CC PRP VBP NN .
PRP VBP RB VB TO VB PRP CC PRP VBP TO .
PRP VBP VBN , CC PRP MD VB RB .
PRP VBP that_insert NNP CC PRP$ JJ VBZ JJ .
PRP VBP NN while PRP VBZ NN .
PRP MD VB TO VB VBN TO DT NN JJ NN CC PRP VBD TO VB JJ NNS TO VB DT NN .
PRP VBZ DT JJ NN IN JJ NNS TO VB , CC PRP VBZ RB JJ JJ NN NN .
PRP VBZ RB JJ , CC JJ CC JJ .
PRP VBZ JJ , CC PRP VBZ JJ .
PRP RB VBZ but PRP VBZ .
NNP VBZ JJ CC PRP VBZ RB JJ TO VB NNS .
NNP DT NN VBZ RB JJ , CC PRP VBP TO VB .
PRP$ NN VBZ DT JJ NN CC PRP$ NNS VBP RB RB VB PRP$ NNS .
PRP$ NN VBZ JJ CC PRP VBP JJ TO VB JJ IN DT NN .
JJ NNS VBG IN CD MD VB CD JJ NNS , CC RB RB CD VBP JJ IN NN .
IN CD JJ NNS VBP JJ IN NN , CC RB DT NN VBZ VBG VBN .
RB RB PRP VBZ CD TO CD NNS TO VB DT NN NN NNS , CC DT VBZ DT RB JJ .
JJ DT NN , RB PRP MD VB .
PRP VBZ DT JJ NN : RB PRP VBP RB VB PRP .
PRP VBZ JJ CC JJ , CC RB NNS VBP PRP .
PRP VBZ RB JJ , CC PRP VBZ RB IN PRP$ CD NNS .
PRP MD VB JJ , CC PRP VBD IN NN .
NNP VBD DT NN IN NNP POS NN , CC PRP$ NNS VBP VBN IN PRP$ JJ NN IN DT NNP NNP .
NNPS MD VB PRP NN CC PRP MD RB RB VB PRP RB .
DT NN VBZ JJ : RB , PRP VBZ JJ PRP .
DT NNP NNP CC JJ JJ NNS RB RB VBD RP NNS IN NN , CC NNP VBZ RB VBD .
DT JJ JJ NN IN NNP VBZ RB CD NNS IN NN , CC PRP VBP VBN DT CD NN NN IN DT IN CD NN NNS IN DT NNP .
DT NN VBN IN NNS IN JJ NNP IN NNS , CC RB PRP MD RB VB DT .
DT NN VBN IN NNS IN NNP IN NNS , CC PRP MD RB VB DT NN .
EX VBP RB CD JJ NNS IN NNP , CC PRP RB VBP RB CD NN IN DT NN POS NN NN .
NNP NNS VBP RB IN JJ NNS , CC NNP VBD JJ TO VB DT NNS .
PRP VBP DT NN IN DT VBG NNS CC DT VBZ VBN IN PRP$ NN TO VB IN NN NNS .
PRP VB DT NN while PRP VB DT NN .
PRP MD VB RB , CC PRP MD VB .
MD PRP VB PRP TO NN CC VB PRP VB TO NN RB JJ .
NNP that_insert PRP VBP PRP TO VB PRP CC VB PRP VBP TO VB PRP PRP .
VBP PRP VB RB CC VBP PRP DT NN RB .
CC NNP VBZ VBG CC PRP$ NNS VBP .
CC NNP VBZ VBG CC PRP$ NNS VBP .
PRP MD VB RB , CC PRP MD VB NNS IN NN .
PRP VBD JJ DT NN , RB PRP MD VB VBN NN IN DT NNS VB .
NNP MD VB JJ IN NN CC PRP MD RB VB VBN VBN .
PRP VBP JJ CC PRP MD VB DT JJ NN .
MD PRP RB VB RB CC VB PRP that_insert VBP VBN RP .
PRP MD VB DT NN IN PRP$ NN CC PRP MD VB PRP .
PRP VB RP , CC RB PRP MD VB JJ .
PRP MD VB RB , RB PRP MD VB DT NN .
PRP VBD IN NN IN DT NN , RB PRP MD VB VBN PRP DT NN .
NNP RB VBZ JJ , IN PRP VBZ TO VB PRP$ NN IN NN .
NN VBD DT NN , IN DT NN VBD VBN IN NN .
JJ NN VBZ JJR NN CC JJR NNS : RB PRP VBZ PRP$ NN TO VB PRP .
PRP VBD DT NN RB , for PRP VBD VBN NNS IN DT NN .
PRP VBD NN CC NN , RB , PRP VBD JJ TO VB DT NNS NN .
PRP VBP VBN DT NN TO VB , IN PRP VBP TO VB RB .
PRP VBD TO PRP , for PRP VBD VBN PRP .
PRP VBZ DT NN , IN PRP VBD PRP IN JJ .
PRP VBZ NN RB , RB DT NN MD VB JJR .
PRP VBZ NN , for DT NNS VBP VBG .
PRP VBZ NN , for DT NNS VBP VBG .
PRP VBZ NN RB , RB DT NN MD VB JJR .
PRP VBZ RB DT RB JJ NN , IN PRP RB VBP PRP$ NN .
DT NNPS VBP RB VBN JJ NN IN NN NN , IN PRP MD VB IN DT IN DT NN IN VBG JJ NN .
DT NN VBZ VBN IN NN RB , IN PRP VBP VBG NNS .
DT NN VBD JJ so PRP VBD IN PRP$ NN .
DT NN VBD RP RB DT NN , so PRP VBD RB VB DT JJ NN .
PRP VBD PRP TO VB , IN PRP VBD .
PRP VBP VBN NN , IN EX VBZ DT NN NN .
PRP VBD PRP TO VB , IN PRP VBP .
PRP VBP IN PRP$ NN NN , IN PRP MD VB JJ NNS IN NN TO VB DT NN IN PRP .
PRP MD RBR VB DT NN IN PRP , for PRP VBZ VBG TO VB .
DT NN that_insert VBZ DT RBR , DT JJR NN PRP VBZ .
PRP VBZ RBR than PRP VBZ JJ IN PRP .
PRP VBZ DT RBR NN than PRP VBD NN .
PRP VBZ RBR RB than PRP$ NN VBZ .
PRP VBD RBR JJ than PRP VBD JJ NN .
PRP VBD RB IN RB as PRP VBD VBN RB .
PRP VBD IN JJ NNS as PRP VBP VBN TO VB VBN .
PRP VBZ RB RB JJ as PRP VBP .
NNP VBD RBR than NNS VBP .
NNP VBZ RBR IN DT NN that_insert PRP VBZ .
NNS VBD DT NN IN NN differently than PRP VBP NN .
PRP VBP RB RB RB as PRP VBZ VBD RP .
DT VBZ RB JJ DT NN as PRP MD VB .
DT NN VBD RBR RB than NN VBP .
DT JJR DT NN VBZ VBN , DT JJR DT NN MD VB .
DT JJR PRP VBP , DT JJR PRP VBP PRP$ NN .
DT JJR PRP VBD , DT JJR NN PRP VBP .
DT NN VBZ RB RB JJ as PRP VBD JJ .
DT NNS IN NNP VBP RB RB JJ as PRP VBP IN NNP .
DT NN VBD RB VB RB RB as PRP VBD .
DT NN IN NN VBP JJR RP than PRP VBD TO VB .
EX VBD JJR NNS than PRP VBD VBN .
DT VBZ RB JJ DT NN as PRP MD VB IN .
PRP VBD TO VB JJ NN RB RB IN VB NN .
NNP VBZ RB JJ IN JJ NN as PRP VBZ JJ IN JJ NN .
PRP VBP PRP RB JJ as PRP VBP .
PRP VBD RP PRP$ NN as if PRP VBD VBN VBN .
PRP RB VBD DT NN as though PRP VBD JJ .
PRP VBZ as if PRP VBD VBN VBN IN NN .
PRP VBZ as if PRP VBZ JJ .
PRP VBZ as though PRP VBD VBN VBN IN NN .
PRP VBD PRP$ NNS as if PRP VBD VBG TO VB NN .
PRP VBZ PRP as if PRP VBP DT NN .
PRP VBD RB RB IN VBG DT NN .
PRP VBD RB IN RB VBG DT NN .
PRP VBP VBN PRP as PRP VBP .
PRP VBP DT JJ NN as if PRP VBD NN .
PRP VBD as if EX MD VB DT JJ NN .
PRP VBZ as if DT NN MD VB RP RB RB .
NNP VBD RB VB as PRP VBD .
DT NNS VBZ VBN as if PRP VBD VBN IN NN .
DT JJ NN VBZ as if PRP VBZ DT JJ NN .
PRP RB VBP DT NNS as if PRP RB VBD .
PRP RB VBP DT NNS as though PRP RB VBD .
PRP VBD DT NN as if PRP VBD PRP$ JJ .
PRP MD VB as PRP$ NNS VBP PRP .
IN DT NNS VBP DT NNS , whose magnificence DT NN RB VBZ IN DT NN .
NNS , whose JJ NN VBZ JJ , MD VB CC VB IN JJ JJ NNS .
As PRP DT VBP , DT NN VBZ NN .
VBP PRP VBN DT NN NN , whose JJ NN VBZ NN JJ .
PRP VBZ DT NN , who VBZ DT NN .
PRP VBZ VBN IN NN , as PRP RB VBD .
PRP MD VB JJ NNS , IN which case PRP MD VB TO VB VBN RP .
PRP VBD that PRP VBD RB VBN PRP RB , WDT VBD RB JJ .
PRP VBD DT NN , which VBD PRP .
PRP MD VB RP DT NN IN NNP , when PRP MD VB JJ .
PRP$ NN RB VBD RP IN DT JJ JJ NNS , IN where PRP MD VB NN CC NNS .
PRP VBP DT NN , who VBZ DT JJ NN .
PRP VBP DT NN , who VBZ VBG DT NN .
IN PRP$ NN EX VBP CD NNS , DT JJS IN whom VBZ NNP NNP .
JJ VBP that_insert PRP VBD DT NNS POS NNP NNP , IN WDT JJ JJ NNS VBP VBN DT NN .
NNP VBZ DT JJ NN IN DT NN , DT NN IN which VBZ CD NNS IN NN .
PRP$ NN , who VBZ VBN IN DT NNP NNP NNP PDT PRP$ NN , VBZ VBG JJ NN .
PRP$ NN , who VBZ RB JJ , VBZ IN EX MD VB DT NNS DT NN .
PRP$ NN , who VBD DT JJ JJ , VBD DT JJ NN .
NNP , whom PRP VBD IN NNP , VBZ RB RB IN NNP .
NNP VBZ , as PRP VBP , DT JJ NN IN NNP .
NNP , which VBD VBN IN NNP , VBZ VBG RBR CC RBR JJ .
PRP VBZ RB JJ , which PRP MD RB VB .
PRP VBZ DT NN , which PRP VBP RB .
PRP VBD RB JJ IN DT NNS , which PRP$ NN RB VBD .
NNP NNP , whom NN VBZ RB JJ , VBZ CD IN DT JJS NNS IN PRP$ NN .
DT NN , which PRP$ NN VBD PRP IN NNP , VBZ RB JJ IN VBG PRP$ NNP NNP .
DT NN , whose NNS VBZ DT NN , VBZ RB JJ .
DT NN , which PRP VBD JJ NN , VBZ RB JJ .
DT PLACE where NN CC NNS VBP .
DT NN , whose NNS VBZ JJ , VBZ JJ IN DT JJ NNS .
DT NN , whose NNS VBZ RB JJ , VBZ JJ IN DT NN .
DT NN VBZ DT NN , which VBZ PRP JJ IN NNS TO VB .
DT CD NNS VBD JJ IN DT NN , as VBD VBN RB .
DT CD NN VBD RB VBN , which IN NN PRP VBD .
EX VBP CD NNS IN DT JJ NN , JJS IN which VBP JJ .
PRP VBD TO VB , where PRP VBD IN CD NNS .
PRP MD VB RP DT NN IN JJ NN , when PRP MD RB VB RB JJ .
NNP VBD CD NNS IN DT NN , IN which NN PRP VBD NN .
When RB VBN IN NN , WDT PRP RB VBD , PRP MD VB DT IN VBG CC VBG .
NNP , which PRP VBD JJ NN , VBZ DT JJ JJ NN .
JJ NNS VBP VBN TO VB how PRP MD VB PRP$ NNS CC NNS IN NNP .
NNP NNP VBZ that_insert DT JJ NN NN VBZ VBG .
NNP VBZ RP whether PRP VBP IN PRP .
VB PRP RB VBN that DT NN IN PRP$ NN MD VB VBN .
PRP VBD that PRP VBD VBG TO PRP .
PRP VBD if PRP VBD VBN TO NNP .
PRP VBD PRP where PRP MD VB NNP .
PRP VBD whose NNS was DT JJS .
PRP VBD RB VB PRP when PRP MD VB RB .
PRP VBD RP whether PRP MD VB CC VB DT NN .
PRP VBD that PRP MD VB RP TO DT NNP RB .
PRP VBD that_insert PRP MD VB DT NN DT NN .
PRP VBD PRP that PRP VBD VBG IN DT JJ NN .
PRP VBD PRP that PRP MD VB TO DT NN DT JJ NN .
PRP VBD PRP that PRP MD VB PRP IN DT JJ NN .
PRP VBP JJ that PRP VBP VBN DT NN .
PRP VBP JJ that PRP VBP VBN PRP RB JJ .
PRP VBP JJ that_insert PRP MD VB DT NN .
PRP VBD PRP whether PRP VBD VBN PDT DT NN PRP CC IN PRP VBD VBN DT NN .
PRP MD RB VB whether CC RB NN MD VB IN NN .
PRP VBP RB VB whether CC RB PRP MD VB .
PRP VBP RB VB if EX MD VB DT NN DT RBR .
PRP VBP RB VB whom PRP MD VB RP .
PRP VBP RB VB that_insert PRP VBZ DT JJ NN .
PRP VBP RB VB that_insert NNS MD VB .
PRP VBP PRP DT NN that PRP VBP RB VBN TO DT NN .
PRP VBD PRP JJ that PRP MD VB PRP IN PDT DT JJ NN .
PRP VBP VBN RP that PDT DT NNS IN DT NN VBP VBN VBN RP .
PRP VBP VBN PRP DT NN that PRP VBP NNS .
PRP VBD that_insert PRP VBD IN PRP VBD VBN RB .
PRP VBP PRP JJ that PRP VBP RB IN JJ NN DT NN .
PRP VBP PRP RB JJ that PRP VBZ RP VBG RB DT NN .
PRP VBD PRP JJ that PRP MD VB DT NN IN RB CD NNS .
PRP VBP TO VB if PRP VBD PRP$ NN NN .
NNP NNP VBZ that_insert DT JJ NN IN DT NNP NNP NNP VBZ TO VB DT JJ NN IN NN VBG NNS IN DT NN .
NN VBD whether PRP MD VB DT NN .
NN IN PRP VBZ where DT JJ NNS MD VB VBN .
PRP$ NN VBD that NNP VBZ DT JJ NN IN DT NN .
PRP$ NN VBD PRP that NN VBZ RB RBR IN NN .
UH VB PRP when PRP MD VB DT NN .
UH VB PRP what PRP VBD IN DT NN NN .
NNS VBP VBN that DT NN VBZ IN DT NN .
PRP VBZ that_insert DT JJ NN NN VBZ RB RB JJ .
VB PRP which VBD PRP VBP IN .
DT NN MD VB PRP what DT JJS NNS VBP .
DT NN VBZ that_insert NN VBZ RB .
DT NN VBD that DT NN VBZ IN DT NN NN .
PRP MD VB VBN NN whether PRP MD VB DT NN CC RB .
PRP DT VBP what PRP VBD TO VB JJ .
PRP DT VBP that PRP MD VB , IN NNS IN PRP$ NN VBP JJR .
PRP DT VBP PRP JJ that PRP VBP DT JJ NN IN DT NN .
PRP VBP VBG RP whether PRP VBP NNS IN PRP$ NN .
PRP VBD what PRP VBD VBN TO VB JJ .
PRP VBP that_insert PRP VBP VBN DT NN .
PRP VBP PRP that PRP MD VB IN PRP .
PRP VBP PRP JJ that PRP VBD DT NN TO NN .
NNP VBZ JJR NNS IN NN that_insert DT NN VBZ JJ .
PRP VBD RB IN NN that_insert PRP MD VB DT NN .
PRP VBD VBN IN NN DT NN MD VB PRP .
PRP VBP VBG PRP that lest PRP MD VB DT NN .
PRP VBD RP RB RB that PRP MD VB DT JJ NN .
JJS NNS VBP TO NN so that PRP MD VB NNS , NNS CC NNS .
PRP VBZ VBN DT NN IN NN that PRP MD VB DT NN NNS .
PRP VBD RB RB that PRP MD RB VB PRP$ NNS .
DT NN VBD DT NN TO VB RP IN DT NNS so that PRP MD VB PRP .
DT NNS VBN lest PRP MD VB DT VBG NN .
DT NN VBD PRP$ NN IN NN that DT NNS IN DT NN MD VB JJR RB .
PRP VBP VBN DT JJ NN so that PRP MD VB TO DT NNS RB .
PRP MD VB RBR so that PRP MD VB VBN IN DT .
IN DT NN , PRP VBD as if PRP MD RB VB IN DT JJ NN .
PRP VBZ VBN what PRP VBD TO VB CD NNS RB .
PRP VBZ RB RB what PRP VBD .
PRP$ JJ NN VBD whether NNP NNP VBD VBN RB .
PRP$ JJ NN VBD that DT NN VBP .
PRP$ NN VBZ that PRP MD VB JJ .
PRP VBZ RB because PRP VBZ RB VB PRP .
PRP VBZ RB as though PRP VBD JJ .
PRP VBD as if PRP VBD VBG TO VB .
PRP$ NN VBZ that PRP MD VB VBG NNS RB RB .
PRP$ NN VBZ who MD VB RP NN IN DT NNP .
NNP NNP VBZ when PRP MD VB .
RB PRP VBD as though PRP VBD VBN NNP IN NNS .
NNP VBZ RB what PRP VBD TO VB .
PRP VBZ VBN where PRP VBD NN IN DT NN .
DT VBZ what PRP VBP TO VB .
DT VBZ where PRP RB VBD PRP .
DT VBZ because PRP VBD TO VB PRP$ JJ NN IN PRP$ NN .
DT VBZ where PRP VBD VBN .
DT VBD when PRP VBD CD .
DT NN VBZ whether PRP VBD NN .
DT NN VBZ that PRP VBZ RB RB VB .
DT NN VBZ where NNP NNP RB VBD .
DT NN VBZ whether PRP MD VB PRP DT NN .
DT NN VBZ how PRP MD VB PRP .
DT NN VBZ how PRP MD VB DT NNS PRP VBP .
DT NN VBZ whether DT NN VBZ JJ VBG .
DT NN VBZ whether PRP MD VB IN PRP .
DT NN VBZ who PRP MD VB .
DT NN VBZ that PRP VBP VBN PRP$ NN .
DT VBZ why PRP VBP JJ .
PRP VBP RB who PRP VBD PRP VBD .
As PRP VBD VBG , PRP VBD IN NN .
As PRP VBP DT NN , PRP MD RB VB PRP .
PRP MD RB VB VBN PRP , for PRP VBD RB RB .
PRP VBD PRP because PRP VBD JJ .
PRP VBP PRP because PRP VBP PRP .
PRP VBP RB because PRP VBP TO VB DT NN NN IN DT NN .
RB that PRP VBP RB , PRP MD RBR VB .
VBG that PRP VBZ VBG , PRP MD VB RB .
Since DT NN VBZ VBN , VB POS VB IN DT NN .
Since PRP VBP DT NN , PRP MD RB VB PRP .
Since PRP VBP RB JJ , PRP MD RB VB PRP IN PRP .
DT MD VB JJ because DT NNP NN VBZ RB VBN TO VB VBN IN NN IN NNP .
DT NN VBZ RB JJ because PRP VBZ JJ .
DT NN VBD because PRP VBD VBN RB .
DT NN VBD because PRP VBD VBN RB .
PRP MD VB DT NNS because DT NN RB VBZ .
PRP VBZ PDT DT JJ NN that PRP MD RB VB PRP .
NNP VBZ RB JJ that PRP MD RB VB DT NN IN PRP DT RB .
PRP VBD JJ JJ NNS that PRP MD RB VB DT NN .
PRP VBZ RB JJ that PRP MD VB TO NN .
PRP VBZ RB RB that DT NN MD VB PRP .
PRP VBD RB JJ that PRP MD RB VB TO VB DT NN .
PRP VBD RB JJ that PRP MD RB VB DT NN .
PRP VBD PDT DT JJ NN that NN VBD TO VB NN .
PRP VBD PDT DT JJ NN that DT IN PRP VBD TO VB PRP RB .
NNP VBZ RB RB RB that PRP RB RB VBP PRP .
PRP$ NN VBZ RB RB VBN that PRP MD VB JJ NNS .
DT NN VBD RB JJ that DT IN PRP VBD TO VB PRP RB .
DT NN VBZ RB JJ NNS that PRP VBP TO VB NN IN PRP .
EX VBZ RB JJ DT increase IN NN that DT NN NN VBZ VBN .
DT CD VBD RB JJ IN NN that PRP RB VBD NNS IN DT JJ .
PRP VBZ DT NN that PRP VBD RB VB .
PRP VBZ DT NN that PRP MD RB VB .
PRP VBZ RB VB PRP whether PRP VBP CC RB .
PRP VBZ RB VB DT NN whether PRP VBZ CC RB .
PRP VBD that PRP VBD IN WDT NN .
PRP VBZ DT NN TO PRP how PRP DT VBD .
PRP VBZ JJ whether PRP MD VB JJ TO VB .
PRP VBZ VBN TO PDT DT JJ NNS IN JJ NNS .
PRP VBZ VBN that NNP NNP VBZ VBN IN NNP .
PRP VBZ TO VB VBN whether PRP MD VB PRP JJ CC JJ .
PRP VBD PRP that NNP VBD RB VB NN WRB PRP VBD .
PRP VBD DT NN whether PRP MD VB PRP .
PRP VBD RB JJ that PRP VBD TO VB TO PRP .
That PRP MD VB VBZ JJ .
DT NN that_insert MD VB RP VBZ JJ .
That PRP VBD DT NN VBZ DT NN .
That PRP VBP RB JJ VBZ PRP .
That PRP VBD RB VB TO DT NN VBD DT NN .
What PRP VBZ VBP DT NNS .
What PRP VBP TO VB VBZ DT .
What PRP VBP VBZ NN .
Whatever PRP VBD VBD JJ .
When PRP MD VB RB VBZ IN DT NN .
When PRP MD VB VBZ DT NN .
When PRP MD VB VBZ RB VBN .
When DT NN VBZ TO VB RP VBZ RB VBN VBN .
When PRP MD VB VBZ RB VBN VBN JJ .
Where DT NN MD VB VBN VBZ RB RB VBN .
Where PRP MD VB PRP VBZ DT NN .
Whether PRP VBZ VBG CC RB VBZ RB VB RB RB .
Whether PRP MD VB PRP VBD DT NN .
NNP IN PRP VBN IN DT NN VBZ RB DT NN .
NNP VBZ that_insert DT NN MD VB VBN .
Whoever VBZ TO VB IN DT NN MD VB DT NN .
NNP VBZ DT NN IN NN NN .
NNP VBZ TO VB DT JJR NN IN VBG NNS IN JJ NN .
PRP VBD PRP DT NNS .
PRP VBD DT NN TO PRP$ NN .
PRP VBZ JJ .
PRP VBZ NNP RB JJ .
PRP MD VB PRP DT JJ NN .
PRP VBD NN .
PRP VBD DT NN JJ .
NNP VBZ PRP JJ .
NNP VBZ DT NN .
PRP$ NN MD VB NN .
NNP VBZ RB VBG IN JJ NNS TO VB DT NN VBN TO VB NNS TO NNP .
NNP VBZ IN NNP NNP NNP .
NNP NNP VBD DT NN IN DT NN NN .
PRP VBD DT NN .
DT NN VBZ DT JJ NN VBN IN DT NN IN NN .
DT NN VBZ VBN DT NN IN PRP$ JJ JJ NN NN .
DT NN VBZ DT JJ NN TO VB NNS TO DT NNS CC NNS .
DT NN MD VB JJ IN NN IN DT RB JJR NN .
DT NNS VBD VBN IN DT NNP NNP CC NNP NNP .
DT NN VBZ DT NN POS NN , NN CC NN .
PRP MD VB DT JJ NN IN DT NN IN CC CC CC CD NNS .
DT NN VBZ JJ , DT NN VBZ JJ CC DT NN VBZ JJ .
PRP RB VBD NNS .
As DT NN VBD IN DT NN VBD JJR .
Before PRP VBP PRP$ NN , VB PRP VB RB CD NNS TO DT JJ NN .
IN DT NN that_insert DT NN VBD , NNS IN NNS VBD NNS .
VB DT NN before PRP VBP DT NN .
DT NN PRP VBD TO VB , PRP MD VB IN PRP .
PRP VBD RB VBN RB when PRP VBD DT JJ NN IN PRP$ NN .
PRP VBD DT RBR VBN PRP$ NN than DT NNS VBD VBG .
PRP VBD IN DT NN IN VBG when NN VBD IN DT NN .
PRP VBD RB VBG when DT NN VBD CC PRP$ NN VBD RP .
PRP MD VB PRP RB RB as PRP VBP NN .
PRP MD VB RB till DT NN VBZ .
PRP VBP VBN IN NNP since PRP VBD .
PRP VBP VBN DT NN IN JJ NNS IN PRP since PRP VBD RB IN RB .
PRP VBD IN TO VB DT NN when DT NN VBD .
PRP VBD JJ IN NN when DT NN VBD .
PRP MD VB PRP when PRP VBP NN .
PRP VBD TO VB RB as PRP VBD NN .
NNP VBD NN while PRP$ NNS VBD VBG PRP$ NN .
PRP VBP , PRP VBD VBG TO VB IN DT NN RB when PRP$ NN VBD VBZ IN NN .
NNP VBD RB JJ when PRP VBD NN IN PRP$ NN TO VB NNP .
PRP VBD RB VBN PRP$ NN when PRP$ NN VBD PRP TO VB VBG DT NN NN .
DT NN VBD NNP when PRP VBD PRP$ NN .
DT NN PRP VBD DT NN , PRP VBN TO DT NN .
DT JJ NN that_insert PRP VBD PRP , PRP VBD VBG NN .
DT NNS VBD VBG PRP$ JJ NN when DT NN VBD RP .
PRP VBD DT RBR VBN DT NN than PRP VBD VBN IN NN .
PRP VBD IN TO VB when PRP VBD RP .
PRP VBD IN TO VB when PRP VBD TO VB .
PRP VBD VBG PRP$ NN when PRP VBD .
When PRP VBP , PRP$ NNS MD VB NN IN PRP .
When PRP VBD IN DT NN , PRP VBD TO VB DT NN IN PRP .
When PRP VBD RP DT NN , PRP VBD TO NN .
When DT NN VBD , NNS VBD VBN VBN .
Whenever PRP VBP TO VB DT NN , PRP VBP RB JJ IN PRP VBP .
While PRP$ NN VBD VBG DT NN , PRP VBD VBG NN .
PRP MD RB VB NN till PRP VBP PRP$ NN .
PRP MD RB VB NN until PRP VBP PRP$ NN .
PRP VBP JJR DT NN that_insert PRP VBP PRP .
PRP MD VB TO VB PRP$ NNS CC PRP$ NN when PRP VBP DT NN .
PRP MD VB JJ when PRP VBP JJ CC JJ .
PRP VBD PRP TO VB where DT NN VBZ JJ .
PRP VBZ JJ wherever PRP VBZ .
PRP VBZ where EX VBP DT NN NN .
PRP VBD PRP$ NN where PRP VBD RP NN .
PRP MD VB DT NN where PRP MD VB PRP .
IN NN , RB , DT NNP NNP VBZ VBN TO VB NN wherever EX VBZ JJ NN .
VB DT NN where PRP VBP DT NN .
VB wherever PRP VBP .
PRP VBD where PRP VBD VBN IN NN CD NNS RB .
PRP MD VB where PRP VBP JJ .
PRP MD RB VB where EX VBZ DT JJ NN .
PRP VBP , VB CC VB where PRP$ NNS VBP VBN CC VBN .
PRP VBP TO VB where NN VBZ TO VB .
PRP MD PLACE where PRP MD VB NN .
PRP VBD RB , where PRP VBD NN .
Where PRP VBP EX VBP RB IN NNS .
Where DT NNP NNP IN NNP VBZ , RB DT NNS VBP JJ .
Where DT NN VBZ , PRP MD VB NN .
Where EX VBZ DT NN , EX VBZ DT NN .
Where EX VBZ DT NN , EX VBZ DT NN .
Where EX VBZ NN , EX VBZ NN .
Where EX VBZ DT NN , NN VBZ JJ CC JJ .
NNP that_insert PRP VBP PRP MD VB VBG IN PRP .
VB PRP VB , PRP MD VB PRP .
VB PRP VB , PRP MD VB RB JJ NN RB RB as PRP VBP JJ TO VB .
IN DT NN , DT NN MD VB where PRP VBZ CC WRB PRP VBZ .
PRP MD VB RB that_insert PRP VBP .
PRP MD VB VBN DT NN where PRP VBD PRP .
